import { randomUUID } from 'node:crypto';
import { expect,test } from '../support/e2e';
test.use({timezoneId:'America/New_York'});
for(const width of [1440,390])test(`BUY decimal ledger and holdings at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});const email=`buy-${randomUUID()}@example.test`,password='synthetic-buy-password';
 await page.request.post('/api/auth/register',{data:{email,password}});await page.goto('/login');await page.getByTestId('locale-select').selectOption('en');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/new$/);await page.getByTestId('locale-select').selectOption('en');
 await page.getByLabel('Diary date',{exact:true}).fill('2026-09-06');await page.getByRole('textbox',{name:'Title',exact:true}).fill('Two careful purchases');await page.getByRole('textbox',{name:'Content',exact:true}).fill('Evidence improved, with position size kept deliberate.');
 for(const [quantity,price] of [['1.2500','10.1000'],['0.7500','12.3000']]){await page.getByRole('button',{name:'Add purchase',exact:true}).click();const row=page.locator('.buy-row').last();await row.getByRole('textbox',{name:'Symbol',exact:true}).fill(' aapl ');await row.getByRole('textbox',{name:'Quantity',exact:true}).fill(quantity!);await row.getByRole('textbox',{name:'Price per share',exact:true}).fill(price!);await row.getByLabel('Trade date and time (device time)',{exact:true}).fill('2026-09-06T10:30');}
 const row=page.locator('.buy-row').first();await row.getByText('Decision notes',{exact:true}).click();await row.getByRole('textbox',{name:'Strategy',exact:true}).fill('Patient accumulation');await row.getByRole('combobox',{name:'Emotion',exact:true}).selectOption('calm');await row.getByRole('textbox',{name:'Trade notes',exact:true}).fill('Confirm the next report.');
 await row.getByLabel('Trade date and time (device time)',{exact:true}).fill('2026-03-08T02:30');await page.getByRole('button',{name:'Save diary',exact:true}).click();await expect(page.getByRole('alert')).toContainText('valid local trade time');
 await row.getByLabel('Trade date and time (device time)',{exact:true}).fill('2026-11-01T01:30');await expect(row.getByRole('combobox',{name:'UTC',exact:true})).toBeVisible();await row.getByRole('combobox',{name:'UTC',exact:true}).selectOption('2026-11-01T06:30:00.000Z');
 await page.route('**/api/diaries',async route=>{if(route.request().method()==='POST')await route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({data:{code:'SYS_INTERNAL_ERROR',requestId:'buy-atomic'}})});else await route.continue();});await page.getByRole('button',{name:'Save diary',exact:true}).click();await expect(page.getByTestId('request-id')).toHaveText('buy-atomic');await expect(row.getByRole('textbox',{name:'Quantity',exact:true})).toHaveValue('1.2500');await expect(row.getByRole('textbox',{name:'Trade notes',exact:true})).toHaveValue('Confirm the next report.');
 if(width===390)await page.getByTestId('theme-select').selectOption('dark');await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo({top:0,behavior:'instant'});});await page.screenshot({path:`.impeccable/review/buy-editor-${width}.png`,fullPage:true});
 await page.unroute('**/api/diaries');await page.getByRole('button',{name:'Save diary',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/\d+$/);await page.reload();await expect(page.locator('.ledger-reading')).toContainText('Patient accumulation');
 const diary=await(await page.request.get('/api/diaries/'+page.url().split('/').at(-1))).json();expect(diary.transactions.find((item:{quantity:string})=>item.quantity==='1.25').tradeDate).toBe('2026-11-01T06:30:00.000Z');
 await page.getByRole('link',{name:'View holdings',exact:true}).click();await expect(page.getByRole('heading',{name:'Cost holdings',exact:true})).toBeVisible();const holding=page.getByRole('row').filter({has:page.getByRole('link',{name:'AAPL',exact:true})});await expect(holding).toContainText('10.925');await expect(holding).toContainText('21.85');expect(await(await page.request.get('/api/stocks/holdings')).json()).toEqual([{symbol:'AAPL',quantity:'2',avgCost:'10.925',totalCost:'21.85'}]);
 for(const [locale,title] of [['zh-TW','成本持倉'],['zh-CN','成本持仓'],['en','Cost holdings']] as const){await page.getByTestId('locale-select').selectOption(locale);await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();}
 for(const header of await page.getByRole('columnheader').all()){const box=await header.boundingBox();expect(box).not.toBeNull();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(width);}
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:`.impeccable/review/buy-holdings-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false);
});
