import { randomUUID } from 'node:crypto';
import { expect,test, selectLocale, selectTheme } from '../support/e2e';
for(const width of [1440,390])test(`Calendar real diary coverage and date navigation at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.clock.setFixedTime(new Date('2026-09-07T03:00:00Z'));
 const email=`calendar-${randomUUID()}@example.test`,password='synthetic-calendar-password';await page.request.post('/api/auth/register',{data:{email,password}});await page.goto('/login');await selectLocale(page, 'en');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/new$/);await selectLocale(page, 'en');
 const csrf=(await page.context().cookies()).find(cookie=>cookie.name==='csrf-token')!.value;
 const timezone=width===1440?'Asia/Taipei':'America/New_York';await page.request.put('/api/user/settings',{headers:{'x-csrf-token':csrf},data:{timezone,excludeHolidaysInStats:true}});
 let id='';for(const date of ['2026-09-06','2026-09-07']){const response=await page.request.post('/api/diaries',{headers:{'x-csrf-token':csrf},data:{date,title:'The reasoning on '+date,content:'Long evidence. '.repeat(500),transactions:date==='2026-09-06'?[{symbol:'AAPL',type:'BUY',quantity:'1',price:'10',tradeDate:'2026-09-06T15:00:00Z'}]:[]}});expect(response.status()).toBe(201);const entry=await response.json();if(date==='2026-09-06')id=entry.id;}
 await page.goto('/calendar');await expect(page.getByRole('heading',{name:'September 2026',exact:true})).toBeVisible();if(width===1440){await expect(page.locator('.desktop-nav a[aria-current=page]')).toHaveCount(1);await expect(page.locator('.desktop-nav a[aria-current=page]')).toHaveText('Calendar');}else{await page.getByTestId('mobile-menu').click();await expect(page.getByTestId('mobile-menu-dialog')).toBeVisible();await expect(page.locator('.mobile-menu-dialog nav a[aria-current=page]')).toHaveCount(1);await expect(page.locator('.mobile-menu-dialog nav a[aria-current=page]')).toHaveText('Calendar');await page.keyboard.press('Escape');await expect(page.getByTestId('mobile-menu-dialog')).toBeHidden();await expect(page.getByTestId('mobile-menu')).toBeFocused();}await expect(page.getByTestId('coverage')).toHaveText('3%');await expect(page.locator('.calendar-grid [aria-current=date]')).toHaveAttribute('data-date',width===1440?'2026-09-07':'2026-09-06');await expect(page.locator('.calendar-grid [data-date="2026-09-06"]')).toHaveAccessibleName(/1 transactions/);await expect(page.locator('[data-heatdate]')).toHaveCount(371);const latest=await page.locator(`[data-heatdate="${width===1440?'2026-09-07':'2026-09-06'}"]`).boundingBox();expect(latest!.x+latest!.width).toBeLessThanOrEqual(width);
 const first=page.locator('.calendar-grid [data-date="2026-09-06"]');await first.focus();await page.keyboard.press('ArrowRight');await expect(page.locator('.calendar-grid [data-date="2026-09-07"]')).toBeFocused();await page.keyboard.press('ArrowDown');await expect(page.locator('.calendar-grid [data-date="2026-09-14"]')).toBeFocused();
 await page.getByRole('button',{name:'Previous month',exact:true}).click();await expect(page.getByRole('heading',{name:'August 2026',exact:true})).toBeVisible();await expect(page.getByText('No diaries recorded this month.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Today',exact:true}).click();await expect(page.getByRole('heading',{name:'September 2026',exact:true})).toBeVisible();
 await page.getByLabel('Month',{exact:true}).fill('2026-03');await expect(page.getByRole('heading',{name:'March 2026',exact:true})).toBeVisible();await expect(page.locator('.calendar-grid [data-date="2026-03-08"]')).toHaveText('8');await page.getByRole('button',{name:'Today',exact:true}).click();await expect(page.getByTestId('coverage')).toHaveText('3%');
 if(width===390)await selectTheme(page, 'dark');await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo({top:0,behavior:'instant'});});await page.screenshot({path:`.impeccable/review/calendar-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false);
 await first.click();await expect(page).toHaveURL(new RegExp(`/diaries/${id}$`));await expect(page.getByRole('heading',{name:'The reasoning on 2026-09-06'})).toBeVisible();await page.goto('/calendar');await page.locator('.calendar-grid [data-date="2026-09-08"]').click();await expect(page).toHaveURL(/\/diaries\/quick\?date=2026-09-08$/);await expect(page.getByLabel('Diary date',{exact:true})).toHaveValue('2026-09-08');
 await page.route('**/api/holidays?*',route=>route.fulfill({status:502,contentType:'application/json',body:JSON.stringify({data:{code:'SYS_EXTERNAL_SERVICE_ERROR'}})}));await page.goto('/calendar');await expect(page.getByText('Holiday exclusions are unavailable. Coverage is not calculated.',{exact:true})).toBeVisible();await expect(page.getByTestId('coverage')).toHaveText('—');await page.unroute('**/api/holidays?*');await page.getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByTestId('coverage')).toHaveText('3%');
 await page.request.put('/api/user/settings',{headers:{'x-csrf-token':csrf},data:{excludeHolidaysInStats:false}});await page.reload();await expect(page.getByTestId('coverage')).toHaveText('7%');
 for(const [locale,heading] of [['zh-TW','日記月曆'],['zh-CN','日记月历'],['en','Diary calendar']] as const){await selectLocale(page, locale);await expect(page.getByRole('heading',{name:heading,exact:true})).toBeVisible();}
});
