import { randomUUID } from 'node:crypto';
import { expect,test, selectLocale, selectTheme } from '../support/e2e';
for(const width of [1440,390])test(`Company associations survive Quick drafts, append and full edits at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});const email=`company-context-${randomUUID()}@example.test`,password='synthetic-context-password';await page.request.post('/api/auth/register',{data:{email,password}});await page.goto('/login?returnTo=%2Fdiaries%2Fnew');await selectLocale(page, 'en');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/new$/);await selectLocale(page, 'en');
 await page.goto('/diaries/quick');await page.getByRole('combobox',{name:'Writing template',exact:true}).selectOption('trading');await page.getByRole('textbox',{name:'Symbols in note',exact:true}).fill('NVDA');await page.getByRole('textbox',{name:'Title',exact:true}).fill('Company context stays separate');await page.getByRole('textbox',{name:'Content',exact:true}).fill('NVDA is in my writing, not a company association.');await page.getByRole('textbox',{name:'Company context',exact:true}).fill(Array.from({length:11},(_,i)=>'S'+i).join(','));await page.getByRole('button',{name:'Create diary',exact:true}).click();await expect(page.getByTestId('api-error')).toContainText('up to 10 unique company symbols');await expect(page.getByRole('textbox',{name:'Content',exact:true})).toHaveValue('NVDA is in my writing, not a company association.');
 await page.getByRole('textbox',{name:'Company context',exact:true}).fill(' aapl, msft, AAPL ');await page.getByRole('textbox',{name:'Content',exact:true}).focus();await expect(page.getByRole('textbox',{name:'Company context',exact:true})).toHaveValue('AAPL, MSFT');await expect.poll(()=>page.evaluate(()=>Object.keys(localStorage).filter(key=>key.startsWith('diary-quick-draft:')).some(key=>JSON.parse(localStorage.getItem(key)!).value.stockSymbols==='AAPL, MSFT'))).toBe(true);await page.reload();await page.getByRole('button',{name:'Restore saved draft',exact:true}).click();await expect(page.getByRole('textbox',{name:'Company context',exact:true})).toHaveValue('AAPL, MSFT');
 if(width===390)await selectTheme(page, 'dark');await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo({top:0,behavior:'instant'});});await page.screenshot({path:`.impeccable/review/company-context-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'Create diary',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/\d+$/);const id=page.url().split('/').at(-1);const read=async()=>await(await page.request.get(`/api/diaries/${id}`)).json();expect((await read()).stockSymbols).toEqual(['AAPL','MSFT']);await expect(page.locator('.diary-companies a')).toHaveText(['AAPL','MSFT']);await expect(page.locator('.diary-companies a').first()).toHaveAttribute('href','/stocks/AAPL');
 await page.goto('/diaries/quick');await page.getByRole('textbox',{name:'Content',exact:true}).fill('A later observation.');await page.getByRole('textbox',{name:'Company context',exact:true}).fill('TSLA, aapl');await page.getByRole('button',{name:'Append to date',exact:true}).click();await expect(page).toHaveURL(new RegExp(`/diaries/${id}$`));expect((await read()).stockSymbols).toEqual(['AAPL','MSFT','TSLA']);expect((await read()).title).toBe('Company context stays separate');
 await page.getByRole('link',{name:'Edit diary',exact:true}).click();await expect(page.getByRole('textbox',{name:'Company context',exact:true})).toHaveValue('AAPL, MSFT, TSLA');await page.getByRole('textbox',{name:'Title',exact:true}).fill('Scalar edit preserves associations');await page.getByRole('button',{name:'Save diary',exact:true}).click();await expect(page).toHaveURL(new RegExp(`/diaries/${id}$`));expect((await read()).stockSymbols).toEqual(['AAPL','MSFT','TSLA']);
 await page.getByRole('link',{name:'Edit diary',exact:true}).click();await page.getByRole('textbox',{name:'Company context',exact:true}).fill('googl, brk.b');await page.getByRole('button',{name:'Save diary',exact:true}).click();await expect(page).toHaveURL(new RegExp(`/diaries/${id}$`));expect((await read()).stockSymbols).toEqual(['BRK.B','GOOGL']);
 await page.getByRole('link',{name:'Edit diary',exact:true}).click();await page.getByRole('textbox',{name:'Company context',exact:true}).fill('');await page.getByRole('button',{name:'Save diary',exact:true}).click();await expect(page).toHaveURL(new RegExp(`/diaries/${id}$`));expect((await read()).stockSymbols).toEqual([]);await expect(page.locator('.diary-companies')).toHaveCount(0);
});
