import { randomUUID } from 'node:crypto';
import { expect,test, selectLocale, selectTheme } from '../support/e2e';

test.use({timezoneId:'America/New_York'});
for(const width of [1440,390]){
 test(`schedule, complete and revise a private diary review at ${width}px`,async({page,context,browser})=>{
  await page.setViewportSize({width,height:900});
  const email=`review-${randomUUID()}@example.test`,password='synthetic-review-password';
  expect((await page.request.post('/api/auth/register',{data:{email,password}})).status()).toBe(200);
  await page.goto('/login');await selectLocale(page, 'en');
  await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/new$/);await selectLocale(page, 'en');
  const headers={'x-csrf-token':(await context.cookies()).find(cookie=>cookie.name==='csrf-token')!.value};
  expect((await page.request.put('/api/user/settings',{headers,data:{timezone:'Asia/Taipei'}})).status()).toBe(200);
  await page.getByLabel('Diary date',{exact:true}).fill('2026-09-07');await page.getByRole('textbox',{name:'Title',exact:true}).fill('Demand needs independent confirmation');await page.getByRole('textbox',{name:'Content',exact:true}).fill('## Evidence\n\n**Demand** still needs confirmation.');
  await page.getByRole('textbox',{name:'Original thesis',exact:true}).fill('A recovery is possible.\nWait for independent evidence.');await page.getByRole('textbox',{name:'Original risk assessment',exact:true}).fill('The sample may be too small.');await page.getByRole('textbox',{name:'Original execution plan',exact:true}).fill('Reassess after the report.');await page.getByRole('button',{name:'Save diary',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/\d+$/);const id=page.url().split('/').at(-1)!;
  await page.getByRole('link',{name:'Review diary',exact:true}).click();await expect(page.getByTestId('review-status')).toHaveText('Not scheduled');
  await page.getByRole('link',{name:'Change review schedule',exact:true}).click();await page.getByLabel('Review due at',{exact:true}).fill('2026-09-08T10:30');await page.getByRole('button',{name:'Save diary',exact:true}).click();await expect(page).toHaveURL(new RegExp(`/diaries/${id}$`));await page.getByRole('link',{name:'Review diary',exact:true}).click();
  await expect(page.getByTestId('review-status')).toHaveText('Review pending');await expect(page.getByTestId('review-timezone')).toContainText('Asia/Taipei');await expect(page.getByTestId('review-due')).toHaveAttribute('datetime','2026-09-08T14:30:00.000Z');
  await expect(page.getByTestId('review-due')).toHaveText(new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Taipei'}).format(new Date('2026-09-08T14:30:00Z')));
  await page.getByRole('radio',{name:'Still unclear',exact:true}).check();await page.getByRole('textbox',{name:'What happened',exact:true}).fill('   ');await page.getByRole('button',{name:'Complete review',exact:true}).click();await expect(page.getByTestId('error-code')).toHaveText('SYS_VALIDATION_ERROR');await expect(page.getByRole('textbox',{name:'What happened',exact:true})).toHaveAttribute('aria-invalid','true');
  await page.getByRole('radio',{name:'Partly confirmed',exact:true}).check();await page.getByRole('textbox',{name:'What happened',exact:true}).fill('Private reflection: the result improved, but the evidence remains mixed.');await page.getByRole('textbox',{name:'What I learned',exact:true}).fill('Separate a price change from a change in demand.\nCheck the same measure next time.');await page.getByRole('textbox',{name:'What I will change',exact:true}).fill('Require two independent observations.');
  await page.route(`**/api/diaries/${id}/review`,async route=>{if(route.request().method()==='PATCH')await route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({data:{code:'SYS_INTERNAL_ERROR',requestId:'review-save'}})});else await route.continue();});
  await page.getByRole('button',{name:'Complete review',exact:true}).click();await expect(page.getByTestId('request-id')).toHaveText('review-save');await expect(page.getByRole('textbox',{name:'What happened',exact:true})).toHaveValue(/Private reflection/);
  if(width===390)await selectTheme(page, 'dark');await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo({top:0,behavior:'instant'});});await page.screenshot({path:`docs/design/evidence/review/form-${width}.png`,fullPage:true});
  await page.unroute(`**/api/diaries/${id}/review`);const before=Date.now();await page.getByRole('button',{name:'Complete review',exact:true}).click();await expect(page.getByRole('heading',{name:'Review completed',exact:true})).toBeFocused();await expect(page.getByTestId('review-status')).toHaveText('Reviewed');
  const completed=await (await page.request.get(`/api/diaries/${id}/review`)).json();expect(Date.parse(completed.reviewedAt)).toBeGreaterThanOrEqual(before);expect(Date.parse(completed.reviewedAt)).toBeLessThanOrEqual(Date.now());expect(completed.reviewOutcome).toBe('PARTIAL');expect(completed.thesis).toBe('A recovery is possible.\nWait for independent evidence.');
  await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo({top:0,behavior:'instant'});});await page.screenshot({path:`docs/design/evidence/review/completed-${width}.png`,fullPage:true});
  await page.getByRole('button',{name:'Edit reflection',exact:true}).click();await page.getByRole('textbox',{name:'What happened',exact:true}).fill('Private reflection: revised after checking the second report.');await page.getByRole('button',{name:'Save review changes',exact:true}).click();await expect(page.getByRole('heading',{name:'Review completed',exact:true})).toBeVisible();await page.reload();await expect(page.locator('.review-reflection')).toContainText('revised after checking the second report.');
  for(const [locale,title] of [['zh-TW','日記複盤'],['zh-CN','日记复盘'],['en','Diary review']] as const){await selectLocale(page, locale);await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();}
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  const outsider=await browser.newContext({baseURL:new URL(page.url()).origin,extraHTTPHeaders:{'x-e2e-test-id':randomUUID()}});
  try{const otherEmail=`outsider-${randomUUID()}@example.test`;await outsider.request.post('/api/auth/register',{data:{email:otherEmail,password}});await outsider.request.post('/api/auth/login',{data:{email:otherEmail,password}});const other=await outsider.newPage();await other.goto(`/diaries/${id}/review`);await selectLocale(other, 'en');await expect(other.getByTestId('error-code')).toHaveText('DIARY_NOT_FOUND');await expect(other.locator('body')).not.toContainText('Private reflection:');await expect(other.locator('body')).not.toContainText('Demand needs independent confirmation');const otherHeaders={'x-csrf-token':(await outsider.cookies()).find(cookie=>cookie.name==='csrf-token')!.value};expect((await outsider.request.patch(`/api/diaries/${id}/review`,{headers:otherHeaders,data:{reviewOutcome:'INTACT',reviewSummary:'Unauthorized change'}})).status()).toBe(404);}finally{await outsider.close();}
 });
}
