import { expect, test, selectLocale, selectTheme } from '../support/e2e';

for (const width of [1440,390]) {
  test(`FIRE assumptions, projection and copy work at ${width}px`, async ({page,context}) => {
    await page.setViewportSize({width,height:900});
    await context.grantPermissions(['clipboard-read','clipboard-write']);
    const apiWrites:string[]=[];
    page.on('request',request=>{if(request.url().includes('/api/')&&request.method()!=='GET'&&!request.url().includes('/api/auth/')) apiWrites.push(request.url());});
    await page.goto('/tools/financial-freedom');
    await selectLocale(page, 'zh-CN');
    await expect(page.getByRole('heading',{name:'财务自由计算',exact:true})).toBeVisible();
    await selectLocale(page, 'zh-TW');
    await expect(page.getByRole('heading',{name:'財務自由計算',exact:true})).toBeVisible();
    await selectLocale(page, 'en');
    if(width===390) await selectTheme(page, 'dark');
    await expect(page.getByTestId('fire-target')).toHaveText('15,000,000');
    await expect(page.getByTestId('fire-projection').locator('tbody tr')).toHaveCount(10);
    await page.getByRole('button',{name:'Show all projected years'}).click();
    expect(await page.getByTestId('fire-projection').locator('tbody tr').count()).toBeGreaterThan(10);
    await page.getByRole('button',{name:'Show the first ten years'}).click();
    await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement) document.activeElement.blur();window.scrollTo({top:0,behavior:'instant'});});
    await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBe(0);
    await page.screenshot({path:`docs/design/evidence/fire/fire-${width}.png`,fullPage:true});
    await page.getByTestId('fire-preset').selectOption('conservative');
    await expect(page.getByTestId('fire-target')).toHaveText('20,000,000');
    await page.getByTestId('fire-preset').selectOption('aggressive');
    await expect(page.getByTestId('fire-target')).toHaveText('12,000,000');
    await page.getByTestId('fire-annualExpenses').fill('');
    await expect(page.getByRole('alert')).toContainText('Complete valid inputs');
    await expect(page.getByTestId('fire-annualExpenses')).toHaveAttribute('aria-invalid','true');
    await expect(page.getByTestId('fire-copy')).toBeDisabled();
    await expect(page.getByTestId('fire-target')).toHaveCount(0);
    await page.getByTestId('fire-annualExpenses').fill('600000');
    await page.getByTestId('fire-preset').selectOption('custom');
    await page.getByTestId('fire-withdrawalRate').fill('0');
    await expect(page.getByTestId('fire-copy')).toBeDisabled();
    await page.getByTestId('fire-withdrawalRate').fill('4');
    await page.getByTestId('fire-currentAssets').fill('0');
    await page.getByTestId('fire-monthlyContribution').fill('0');
    await page.getByTestId('fire-expectedReturn').fill('0');
    await expect(page.getByTestId('fire-years')).toHaveText(/not reached within the 100-year/);
    await page.getByTestId('fire-currentAssets').fill('15000000');
    await page.getByTestId('fire-currentAge').fill('');
    await expect(page.getByTestId('fire-years')).toHaveText('Your stated target is reached');
    await page.getByTestId('fire-copy').focus();
    await page.keyboard.press('Enter');
    await expect(page.getByRole('status')).toHaveText('Results copied, including the first ten years.');
    const copied=await page.evaluate(()=>navigator.clipboard.readText());
    expect(copied).toContain('Target assets: 15,000,000');
    expect(copied).toContain('| Year | Starting assets | Annual contributions | Annual returns | Ending assets | Status |\n|---|---|---|---|---|---|\n| 1 |');
    expect(copied).toContain('| 10 |');
    expect(copied).not.toContain('| 11 |');
    expect(copied).not.toMatch(/Infinity|NaN/);
    await page.evaluate(()=>{Object.defineProperty(navigator.clipboard,'writeText',{configurable:true,value:()=>Promise.reject(new Error('Synthetic clipboard denial'))});});
    await page.getByTestId('fire-copy').click();
    await expect(page.getByRole('status')).toContainText('Clipboard access failed');
    await expect(page.getByLabel('Copyable text',{exact:true})).toBeVisible();
    expect(apiWrites).toEqual([]);
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  });
}
