import { test, expect, selectLocale, selectTheme } from '../support/e2e';

for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) {
  test(`register, sign in and persist a diary at ${viewport.width}px`, async ({ page }) => {
    await page.setViewportSize(viewport);
    const errors: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('/register');
    await selectLocale(page, 'en');
    const email = `e2e-${viewport.width}-${Date.now()}@example.test`;
    await page.getByLabel('Email', { exact: true }).fill(email);
    await page.getByLabel('Password', { exact: true }).fill('e2e-safe-password-123');
    await page.getByLabel('Name', { exact: true }).fill('Test investor');
    await page.getByRole('button', { name: 'Create account', exact: true }).click();
    await expect(page.getByText(/Your account is ready/)).toBeVisible();
    await page.locator('#main').getByRole('link', { name: 'Sign in', exact: true }).click();
    await page.getByLabel('Email', { exact: true }).fill(email);
    await page.getByLabel('Password', { exact: true }).fill('e2e-safe-password-123');
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(page).toHaveURL(/\/diaries\/new$/);
    await selectLocale(page, 'en');
    await page.getByLabel('Diary date', { exact: true }).fill('2026-09-05');
    await page.getByLabel('Title', { exact: true }).fill('Wait for evidence before increasing the position');
    await page.getByRole('textbox', { name: 'Content', exact: true }).fill('The price moved, but the original thesis has not yet been confirmed.\nI will review the next earnings report before changing the position.');
    await page.route('**/api/diaries', route => route.fulfill({ status: 400, contentType: 'application/json', body: JSON.stringify({ statusCode: 400, statusMessage: 'Validation failed', data: { code: 'SYS_VALIDATION_ERROR', details: [{ field: 'content', message: 'Please review the content' }], requestId: 'ui-validation-fixture' } }) }));
    await page.getByRole('button', { name: 'Save diary', exact: true }).click();
    await expect(page.getByRole('textbox', { name: 'Content', exact: true })).toHaveAttribute('aria-invalid', 'true');
    await expect(page.getByText(/ui-validation-fixture/)).toBeVisible();
    await expect(page.getByRole('textbox', { name: 'Content', exact: true })).toHaveValue(/The price moved/);
    await page.screenshot({ path: `test-results/editor-error-${viewport.width}.png`, fullPage: true });
    await page.unroute('**/api/diaries');
    await page.getByRole('button', { name: 'Save diary', exact: true }).click();
    await expect(page).toHaveURL(/\/diaries\/\d+$/);
    await expect(page.getByRole('heading', { name: 'Wait for evidence before increasing the position' })).toBeVisible();
    await page.reload();
    await expect(page.getByText('The price moved, but the original thesis has not yet been confirmed.', { exact: false })).toBeVisible();
    if (viewport.width < 500) await selectTheme(page, 'dark');
    await page.screenshot({ path: `test-results/diary-${viewport.width}.png`, fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    expect(errors).toEqual([]);
    await page.goto('/design-preview');
    await page.screenshot({ path: `test-results/design-${viewport.width}.png`, fullPage: true });
    const quickTrigger = page.getByTestId('open-quick-diary');
    await quickTrigger.click();
    const dialog = page.getByTestId('quick-diary-dialog');
    await expect(dialog).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(dialog).not.toBeVisible();
    await expect(quickTrigger).toBeFocused();
    await quickTrigger.click();
    await dialog.getByLabel('Diary date', { exact: true }).fill('2026-09-06');
    await dialog.getByLabel('Title', { exact: true }).fill('A question to revisit');
    await dialog.getByRole('textbox', { name: 'Content', exact: true }).fill('What would change my original view?');
    await page.screenshot({ path: `test-results/quick-${viewport.width}.png`, fullPage: false });
    await dialog.getByRole('button', { name: 'Save diary', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'A question to revisit', exact: true })).toBeVisible();
    expect(errors).toEqual([]);
  });
}
