import { randomUUID } from 'node:crypto';
import { expect,test } from '../support/e2e';
test('historical transaction edits and diary deletion preserve the complete ledger',async({page})=>{
 const email=`correction-${randomUUID()}@example.test`,password='synthetic-correction-password';await page.request.post('/api/auth/register',{data:{email,password}});await page.goto('/login');await page.getByTestId('locale-select').selectOption('en');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/new$/);await page.getByTestId('locale-select').selectOption('en');
 const csrf=(await page.context().cookies()).find(item=>item.name==='csrf-token')!.value;const at=(days:number)=>new Date(Date.now()-days*86400000).toISOString();const buyAt=at(3),sellAt=at(2),dueAt=at(-7);
 async function create(type:'BUY'|'SELL',date:string,quantity:string,price:string){const response=await page.request.post('/api/diaries',{headers:{'x-csrf-token':csrf},data:{date:date.slice(0,10),title:type+' reasoning',content:'Keep the complete ledger valid.',reviewDueAt:dueAt,transactions:[{symbol:'AAPL',type,quantity,price,tradeDate:date}]}});expect(response.status()).toBe(201);return response.json();}
 const buy=await create('BUY',buyAt,'2','10'),sell=await create('SELL',sellAt,'1','15');
 await page.goto(`/diaries/${buy.id}/edit`);const row=page.locator('.buy-row');await expect(row.getByRole('textbox',{name:'Quantity',exact:true})).toHaveValue('2');await row.getByRole('textbox',{name:'Quantity',exact:true}).fill('0.5');await page.getByRole('button',{name:'Save diary',exact:true}).click();await expect(page.getByTestId('error-code')).toHaveText('SYS_VALIDATION_ERROR');await expect(row.getByRole('textbox',{name:'Quantity',exact:true})).toHaveValue('0.5');
 await page.getByRole('button',{name:'Remove transaction 1',exact:true}).click();await page.getByRole('button',{name:'Save diary',exact:true}).click();await expect(page.getByTestId('error-code')).toHaveText('SYS_VALIDATION_ERROR');expect((await(await page.request.get(`/api/diaries/${buy.id}`)).json()).transactions[0].quantity).toBe('2');
 page.once('dialog',dialog=>dialog.accept());await page.reload();await expect(row.getByRole('textbox',{name:'Quantity',exact:true})).toHaveValue('2');await row.getByRole('textbox',{name:'Price per share',exact:true}).fill('12');await row.getByText('Decision notes',{exact:true}).click();await row.getByRole('textbox',{name:'Trade notes',exact:true}).fill('Corrected execution price.');await page.getByRole('button',{name:'Save diary',exact:true}).click();await expect(page).toHaveURL(new RegExp(`/diaries/${buy.id}$`));
 const saved=await(await page.request.get(`/api/diaries/${buy.id}`)).json();expect(saved.transactions[0]).toMatchObject({id:buy.transactions[0].id,tradeDate:buyAt,price:'12',notes:'Corrected execution price.'});expect(saved.reviewDueAt).toBe(dueAt);expect(await(await page.request.get('/api/stocks/holdings')).json()).toEqual([{symbol:'AAPL',quantity:'1',avgCost:'12',totalCost:'12'}]);expect((await(await page.request.get('/api/stats/recent-trades')).json()).trades[0].realizedPnL).toBe('3');
 await page.getByRole('button',{name:'Delete diary',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Delete diary',exact:true}).click();await expect(page.getByTestId('error-code')).toHaveText('SYS_VALIDATION_ERROR');expect((await page.request.get(`/api/diaries/${buy.id}`)).status()).toBe(200);
 await page.goto(`/diaries/${sell.id}`);await page.getByRole('button',{name:'Delete diary',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Delete diary',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/new$/);expect(await(await page.request.get('/api/stocks/holdings')).json()).toEqual([{symbol:'AAPL',quantity:'2',avgCost:'12',totalCost:'24'}]);
 await page.goto(`/diaries/${buy.id}`);await page.getByRole('button',{name:'Delete diary',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Delete diary',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/new$/);expect(await(await page.request.get('/api/stocks/holdings')).json()).toEqual([]);
});
