import { randomUUID } from 'node:crypto';
import { test, expect, selectLocale, selectTheme, signOut } from '../support/e2e';
const knownExposure = {
  exposure: { highBetaPct: 0, coreIndexPct: 0, megaCapPct: 50, singleStockPct: 0, defensivePct: 0, cashProxyPct: 0, unknownPct: 50, largestTheme: 'mega_cap', concentrationWarning: false, totalValue: 400, skippedCount: 0 },
  gaps: [
    { bucket: 'highBeta', currentPct: 50, targetPct: 60, gapPct: -10, status: 'underweight' },
    { bucket: 'coreIndex', currentPct: 0, targetPct: 30, gapPct: -30, status: 'underweight' },
    { bucket: 'cash', currentPct: 0, targetPct: 10, gapPct: -10, status: 'underweight' },
  ],
  suggestedAllocation: { highBetaTargetPct: 60, coreIndexTargetPct: 30, cashTargetPct: 10 },
  betaAllocation: { suggestedMode: 'aggressive', suggestedBetaLevel: 1.3, highBetaTargetPct: 60, coreIndexTargetPct: 30, cashTargetPct: 10, explanation: 'Market is risk-on with confirming breadth. Suggested posture is aggressive: maintain high beta exposure, but avoid chasing extended names.', warnings: [] },
  marketState: 'risk_on', lastUpdated: '2026-09-04T00:00:00.000Z', marketStateAsOfDate: '2026-09-03', summaryAsOfDate: '2026-09-04',
};
for (const width of [1440, 390]) test(`Portfolio separates exposure and priced concentration at ${width}px`, async ({ page, context }) => {
  await page.setViewportSize({ width, height: 900 }); const email = `exposure-${randomUUID()}@example.test`, password = 'synthetic-exposure-password';
  await page.request.post('/api/auth/register', { data: { email, password } }); await page.goto('/login'); await expect(page.getByTestId('locale-select')).toBeEnabled(); await selectLocale(page, 'en'); await page.getByLabel('Email', { exact: true }).fill(email); await page.getByLabel('Password', { exact: true }).fill(password); await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(page).toHaveURL(/\/diaries\/new$/); await expect(page.getByTestId('locale-select')).toBeEnabled(); await selectLocale(page, 'en');
  await page.goto('/stocks'); const panel = page.getByRole('region', { name: 'Portfolio exposure', exact: true }); await expect(panel).toContainText('No positions to classify.');
  const headers = { 'x-csrf-token': (await context.cookies()).find(cookie => cookie.name === 'csrf-token')!.value };
  expect((await page.request.post('/api/diaries', { headers, data: { date: '2026-09-01', title: 'Synthetic portfolio', content: 'Synthetic', transactions: ['AAPL', 'UNKNOWN'].map(symbol => ({ symbol, type: 'BUY', quantity: '2', price: '100', tradeDate: '2026-09-01T00:00:00Z' })) } })).status()).toBe(201);
  let exposureMode: 'real' | 'known' | 'error' = 'real'; await page.route('**/api/stocks/exposure', async route => { if (route.request().method() !== 'GET' || exposureMode === 'real') return route.continue(); if (exposureMode === 'error') { await route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ data: { code: 'SYS_INTERNAL_ERROR', requestId: 'exposure-retry' } }) }); return; } await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(knownExposure) }); });
  exposureMode = 'known'; await page.reload(); await expect(panel.getByTestId('exposure-megaCapPct')).toHaveText('50%'); await expect(panel.getByTestId('exposure-unknownPct')).toHaveText('50%'); await expect(panel.getByTestId('exposure-market-state')).toHaveText('Risk-on'); await expect(panel.getByTestId('exposure-allocation-mode')).toHaveText('Aggressive'); await expect(panel.getByTestId('exposure-last-updated')).toContainText('Sep 4, 2026'); await expect(panel.getByTestId('exposure-market-state-date')).toContainText('Sep 3, 2026'); await expect(panel.getByTestId('exposure-summary-date')).toContainText('Sep 4, 2026'); await expect(panel.getByRole('region', { name: 'Current versus target allocation', exact: true })).toBeVisible(); await expect(panel.getByTestId('exposure-gap-highBeta')).toHaveText('-10 pp'); await expect(panel.getByTestId('exposure-status-highBeta')).toHaveText('Underweight'); await expect(page.getByTestId('risk-largest')).toContainText('100%'); await expect(page.getByTestId('risk-top3')).toHaveText('100%');
  await page.getByTestId('risk-largest').getByRole('link', { name: 'AAPL', exact: true }).click(); await expect(page).toHaveURL(/\/stocks\/AAPL$/); await page.goBack(); await expect(panel.getByTestId('exposure-unknownPct')).toHaveText('50%');
  const comparison = panel.getByRole('region', { name: 'Current versus target allocation', exact: true }); await comparison.focus(); await expect(comparison).toBeFocused(); if (width === 390) { const metrics = await comparison.evaluate(element => ({ scrollWidth: element.scrollWidth, clientWidth: element.clientWidth })); expect(metrics.scrollWidth).toBeGreaterThan(metrics.clientWidth); await comparison.evaluate(element => { element.scrollLeft = element.scrollWidth; }); await expect(panel.getByTestId('exposure-gap-highBeta')).toBeVisible(); await comparison.evaluate(element => { element.scrollLeft = 0; }); } if (width === 390) await selectTheme(page, 'dark'); await page.evaluate(() => { if (document.activeElement instanceof HTMLElement) document.activeElement.blur(); }); await panel.screenshot({ path: `docs/design/evidence/portfolio-exposure/${width}.png` }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  exposureMode = 'error'; await page.reload(); await expect(panel.getByTestId('request-id')).toHaveText('exposure-retry'); await expect(page.getByTestId('risk-largest')).toContainText('100%'); exposureMode = 'real'; await panel.getByRole('button', { name: 'Try again', exact: true }).click(); await expect(panel.getByTestId('exposure-unknownPct')).toHaveText('50%'); await expect(panel.getByTestId('exposure-comparison-unavailable')).toBeVisible(); await page.unroute('**/api/stocks/exposure');
  for (const [locale, title] of [['zh-TW', '投資組合曝險'], ['zh-CN', '投资组合敞口'], ['en', 'Portfolio exposure']] as const) { await selectLocale(page, locale); await expect(page.getByRole('region', { name: title, exact: true })).toBeVisible(); }
  await signOut(page); await expect(page.getByTestId('exposure-unknownPct')).toHaveCount(0);
});
