import { randomUUID } from 'node:crypto';
import { test, expect } from '../support/e2e';
for (const width of [1440, 390]) test(`price reminder CRUD and rearm at ${width}px`, async ({ page, context }) => {
  await page.setViewportSize({ width, height: 900 });
  const email = `price-ui-${randomUUID()}@example.test`, password = 'synthetic-price-ui-password';
  await page.request.post('/api/auth/register', { data: { email, password } });
  await page.goto('/login'); await page.getByTestId('locale-select').selectOption('en');
  await page.getByLabel('Email', { exact: true }).fill(email); await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(page).toHaveURL(/\/diaries\/new$/); await page.getByTestId('locale-select').selectOption('en');
  await page.goto('/stocks/AAPL');
  await page.locator('main').getByRole('link', { name: 'Price reminders', exact: true }).click();
  await expect(page.getByLabel('Symbol', { exact: true })).toHaveValue('AAPL');
  await page.getByLabel('Price threshold', { exact: true }).fill('123.4567');
  await page.getByLabel('Reminder message', { exact: true }).fill('Check whether the original reasoning still applies at this price.');
  await page.getByRole('button', { name: 'Create price reminder', exact: true }).click();
  const items = page.getByTestId('price-reminder'); await expect(items).toHaveCount(1); await expect(items).toContainText('123.4567'); await expect(items).toContainText('Monitoring');
  await page.getByLabel('Condition', { exact: true }).selectOption('PRICE_BELOW');
  await page.getByLabel('Price threshold', { exact: true }).fill('80');
  await page.getByLabel('Reminder message', { exact: true }).fill('Check the downside level.');
  await page.getByRole('button', { name: 'Create price reminder', exact: true }).click(); await expect(items).toHaveCount(2);
  await page.getByLabel('Condition', { exact: true }).selectOption('CHANGE_PERCENT');
  await expect(page.getByLabel('Signed change (%)', { exact: true })).toBeVisible();
  await expect(page.getByText('Percent from previous close', { exact: true })).toBeVisible();
  await page.getByLabel('Signed change (%)', { exact: true }).fill('-5');
  await page.getByLabel('Reminder message', { exact: true }).fill('Check the signed move.');
  await page.getByRole('button', { name: 'Create price reminder', exact: true }).click(); await expect(items).toHaveCount(3);
  await page.getByLabel('Condition', { exact: true }).selectOption('MOVING_AVG');
  await expect(page.getByLabel('Moving average period', { exact: true })).toBeVisible();
  await expect(page.getByText('Completed-session period', { exact: true })).toBeVisible();
  await page.getByLabel('Moving average period', { exact: true }).selectOption('50');
  await page.getByLabel('Direction', { exact: true }).selectOption('below');
  await page.getByLabel('Reminder message', { exact: true }).fill('Check the completed-session average.');
  await page.getByRole('button', { name: 'Create price reminder', exact: true }).click(); await expect(items).toHaveCount(4);
  const headers = { 'x-csrf-token': (await context.cookies()).find(cookie => cookie.name === 'csrf-token')!.value };
  const alerts = await (await page.request.get('/api/stocks/alerts')).json(); expect(alerts).toHaveLength(4);
  for (const alert of alerts) expect((await page.request.put(`/api/stocks/alerts/${alert.id}`, { headers, data: { isTriggered: true, triggeredAt: '2026-01-01T00:00:00.123Z' } })).status()).toBe(200);
  await page.reload(); await expect(items).toHaveCount(4); await expect(page.getByText('Triggered', { exact: true })).toHaveCount(4);
  const averageItem = items.filter({ hasText: '50-session' });
  await averageItem.getByRole('button', { name: 'Edit', exact: true }).click();
  await expect(page.getByLabel('Moving average period', { exact: true })).toBeFocused();
  await expect(page.getByLabel('Moving average period', { exact: true })).toHaveValue('50'); await expect(page.getByLabel('Direction', { exact: true })).toHaveValue('below');
  await page.getByLabel('Moving average period', { exact: true }).selectOption('20'); await page.getByLabel('Direction', { exact: true }).selectOption('above');
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  const editedAverageItem = items.filter({ hasText: '20-session' }); await expect(editedAverageItem).toContainText('Triggered');
  const percentItem = items.filter({ hasText: '-5.0000%' });
  await percentItem.getByRole('button', { name: 'Edit', exact: true }).click(); await expect(page.getByLabel('Signed change (%)', { exact: true })).toBeFocused();
  await page.getByLabel('Signed change (%)', { exact: true }).fill('5'); await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  const editedPercentItem = items.filter({ hasText: '5.0000%' }); await expect(editedPercentItem).toContainText('Triggered');
  const aboveItem = items.filter({ hasText: '123.4567' });
  await aboveItem.getByRole('button', { name: 'Edit', exact: true }).click(); await expect(page.getByLabel('Price threshold', { exact: true })).toBeFocused();
  await page.getByLabel('Price threshold', { exact: true }).fill('120.0001'); await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  const editedItem = items.filter({ hasText: '120.0001' }); await expect(editedItem).toContainText('Triggered');
  if (width === 390) await page.getByTestId('theme-select').selectOption('dark');
  await page.locator('main').screenshot({ path: `docs/design/evidence/price-alerts/${width}.png` }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await editedItem.getByRole('button', { name: 'Monitor again', exact: true }).click(); await expect(editedItem).toContainText('Monitoring');
  for (const [locale, title] of [['zh-TW', '價格提醒'], ['zh-CN', '价格提醒'], ['en', 'Price reminders']] as const) { await page.getByTestId('locale-select').selectOption(locale); await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible(); }
  await editedItem.getByRole('button', { name: 'Delete reminder', exact: true }).click(); await expect(editedItem).toHaveCount(0);
  await page.getByTestId('sign-out').click(); await expect(page.getByRole('button', { name: 'Create price reminder', exact: true })).toHaveCount(0);
});
