import { randomUUID } from 'node:crypto';
import { expect,test, selectLocale, selectTheme } from '../support/e2e';
for(const width of [1440,390])test(`reflection selects real closed trades and restores decimals at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});const email=`related-${randomUUID()}@example.test`,password='synthetic-related-password';await page.request.post('/api/auth/register',{data:{email,password}});await page.goto('/login');await selectLocale(page, 'en');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/new$/);await selectLocale(page, 'en');
 const csrf=(await page.context().cookies()).find(item=>item.name==='csrf-token')!.value;
 for(const [type,days] of [['BUY',3],['SELL',2]] as const){const at=new Date(Date.now()-days*86400000).toISOString();expect((await page.request.post('/api/diaries',{headers:{'x-csrf-token':csrf},data:{date:at.slice(0,10),title:type+' source',content:'Controlled transaction.',transactions:[{symbol:'AAPL',type,quantity:'0.0001',price:type==='BUY'?'10.1':'20.2',tradeDate:at}]}})).status()).toBe(201);}
 let requests=0;await page.route('**/api/stats/recent-trades',async route=>{requests++;await route.fulfill({status:502,contentType:'application/json',body:JSON.stringify({data:{code:'SYS_EXTERNAL_SERVICE_ERROR',requestId:'related-retry'}})});});
 await page.goto('/diaries/quick');await expect(page.getByRole('combobox',{name:'Writing template',exact:true})).toBeVisible();expect(requests).toBe(0);await page.getByRole('combobox',{name:'Writing template',exact:true}).selectOption('reflection');await expect(page.getByTestId('request-id')).toHaveText('related-retry');await page.unroute('**/api/stats/recent-trades');await page.getByRole('button',{name:'Try again',exact:true}).click();
 const selector=page.getByRole('region',{name:'Related trade review',exact:true});await expect(selector.getByRole('checkbox',{name:/AAPL/})).toBeVisible();await expect(selector).toContainText('Quantity: 0.0001');await page.getByRole('textbox',{name:'Content',exact:true}).fill('My original reasoning remains here.');await selector.getByRole('checkbox',{name:/AAPL/}).check();await expect(page.getByRole('textbox',{name:'Content',exact:true})).toHaveValue('My original reasoning remains here.');await page.getByRole('button',{name:'Apply template changes',exact:true}).click();await expect(page.getByRole('textbox',{name:'Content',exact:true})).toHaveValue(/My original reasoning remains here/);await expect(page.getByRole('textbox',{name:'Content',exact:true})).toHaveValue(/Related Trade Review/);
 await expect.poll(()=>page.evaluate(()=>Object.keys(localStorage).filter(key=>key.startsWith('diary-quick-draft:')).some(key=>JSON.parse(localStorage.getItem(key)!).value.data.relatedTrades?.[0]?.sellQuantity==='0.0001'))).toBe(true);
 await page.reload();await page.getByRole('button',{name:'Restore saved draft',exact:true}).click();await expect(selector.getByRole('checkbox',{name:/AAPL/})).toBeChecked();await expect(page.getByRole('textbox',{name:'Content',exact:true})).toHaveValue(/My original reasoning remains here/);
 if(width===390)await selectTheme(page, 'dark');await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo({top:0,behavior:'instant'});});await page.screenshot({path:`.impeccable/review/quick-related-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'Create diary',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/\d+$/);await expect(page.getByRole('heading',{name:'Related Trade Review',exact:true})).toBeVisible();await expect(page.locator('.safe-markdown')).toContainText('0.0001');await expect(page.locator('.safe-markdown')).toContainText('My original reasoning remains here.');
});
