import { randomUUID } from 'node:crypto';
import { test,expect,clickNav, focusQuickTrigger, openQuick, selectLocale, selectTheme, signOut } from '../support/e2e';
for(const width of [1440,390])test(`Quick templates, drafts, snippets and append at ${width}px`,async({page})=>{
 await page.addInitScript(()=>{let starts=0;class FakeSpeechRecognition{lang='';continuous=false;interimResults=false;onresult:((event:unknown)=>void)|null=null;onerror:((event:unknown)=>void)|null=null;onend:(()=>void)|null=null;start(){queueMicrotask(()=>{if(starts++===0)this.onresult?.({resultIndex:0,results:[{isFinal:true,0:{transcript:'Spoken evidence.'}}]});else this.onerror?.({error:'not-allowed'});this.onend?.();});}stop(){this.onend?.();}abort(){}}Object.defineProperty(window,'SpeechRecognition',{value:FakeSpeechRecognition,configurable:true});});
 await page.setViewportSize({width,height:900});const email=`quick-${randomUUID()}@example.test`,password='synthetic-quick-password';await page.request.post('/api/auth/register',{data:{email,password}});
 await page.goto('/login');await selectLocale(page, 'en');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/new$/);await selectLocale(page, 'en');
 await page.getByRole('textbox',{name:'Title',exact:true}).focus();await page.keyboard.press('Control+j');await expect(page.getByRole('dialog')).not.toBeVisible();let accountFails=true;await page.route('**/api/auth/me',async route=>{if(accountFails){accountFails=false;await route.fulfill({status:500,body:'{}'});}else await route.continue();});await page.route('**/api/diaries/by-date?*',route=>route.fulfill({status:500,body:'{}'}));await focusQuickTrigger(page);await page.keyboard.press('Control+j');const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();await dialog.getByRole('button',{name:'Try again',exact:true}).click();await expect(dialog.getByRole('combobox',{name:'Writing template',exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'Try again',exact:true})).toBeVisible();await page.unroute('**/api/diaries/by-date?*');await dialog.getByRole('button',{name:'Try again',exact:true}).click();await page.unroute('**/api/auth/me');
 await dialog.getByRole('combobox',{name:'Writing template',exact:true}).selectOption('trading');await dialog.getByRole('combobox',{name:'Operation',exact:true}).selectOption('none');await dialog.getByRole('textbox',{name:'Quick notes',exact:true}).fill('Observed without entering.');await dialog.getByLabel('Diary date',{exact:true}).fill('2026-09-08');
 await expect(dialog.getByRole('textbox',{name:'Content',exact:true})).toHaveValue(/Observed without entering/);await dialog.getByRole('textbox',{name:'Content',exact:true}).fill('My own evidence.');await dialog.getByRole('combobox',{name:'Writing template',exact:true}).selectOption('observation');await dialog.getByRole('textbox',{name:'Topic',exact:true}).fill('Breadth');await dialog.getByRole('textbox',{name:'Observation content',exact:true}).fill('Wait for confirmation.');await expect(dialog.getByRole('textbox',{name:'Content',exact:true})).toHaveValue('My own evidence.');await dialog.getByRole('button',{name:'Apply template changes',exact:true}).click();await expect(dialog.getByRole('textbox',{name:'Content',exact:true})).toHaveValue(/My own evidence.[\s\S]*Wait for confirmation/);
 await dialog.getByRole('button',{name:'Close',exact:true}).click();await expect(page.getByTestId(width < 768 ? 'mobile-menu' : 'quick-entry')).toBeFocused();await openQuick(page);await dialog.getByRole('button',{name:'Restore saved draft',exact:true}).click();await expect(dialog.getByRole('textbox',{name:'Content',exact:true})).toHaveValue(/My own evidence/);
 await dialog.locator('summary').filter({hasText:'Saved snippets'}).click();await expect(dialog.getByRole('combobox',{name:'Saved snippets',exact:true}).locator('option')).toHaveCount(6);await dialog.getByRole('button',{name:'Manage snippets',exact:true}).click();await dialog.getByRole('textbox',{name:'Snippet name',exact:true}).fill('Evidence checklist');await dialog.getByRole('textbox',{name:'Saved snippets',exact:true}).fill('Confirm the primary source.');await dialog.getByRole('button',{name:'Save snippet',exact:true}).click();await expect(dialog.getByRole('combobox',{name:'Saved snippets',exact:true}).locator('option')).toHaveCount(7);await dialog.getByRole('combobox',{name:'Saved snippets',exact:true}).selectOption({label:'Evidence checklist'});await dialog.getByRole('button',{name:'Insert snippet',exact:true}).click();await expect(dialog.getByRole('textbox',{name:'Content',exact:true})).toHaveValue(/Confirm the primary source/);await dialog.getByRole('button',{name:'Delete snippet',exact:true}).click();await expect(dialog.getByRole('combobox',{name:'Saved snippets',exact:true}).locator('option')).toHaveCount(6);
 await dialog.locator('summary').filter({hasText:'Saved snippets'}).click();await dialog.getByRole('button',{name:'Start voice input',exact:true}).click();await expect(dialog.getByRole('textbox',{name:'Content',exact:true})).toHaveValue(/Spoken evidence/);await dialog.getByRole('button',{name:'Start voice input',exact:true}).click();await expect(dialog.getByText('Microphone input failed or permission was denied. Check browser permission and retry, or keep typing.',{exact:true})).toBeVisible();
 await dialog.locator('summary').filter({hasText:'Capture reminder'}).click();await dialog.getByLabel('Custom reminder time',{exact:true}).fill('2000-01-01T12:00');await dialog.getByRole('button',{name:'Set reminder',exact:true}).click();await expect(dialog.getByText('Time to record a quick diary.',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Tomorrow',exact:true}).click();await expect(dialog.getByRole('button',{name:'Clear reminder',exact:true})).toBeVisible();await dialog.locator('summary').filter({hasText:'Capture reminder'}).click();
 await dialog.getByRole('textbox',{name:'Title',exact:true}).fill('Preserve this title');if(width===390){await dialog.getByRole('button',{name:'Close',exact:true}).click();await selectTheme(page, 'dark');await openQuick(page);await dialog.getByRole('button',{name:'Restore saved draft',exact:true}).click();}
 await page.evaluate(()=>{const d=document.querySelector<HTMLDialogElement>('dialog[open]');if(d)d.scrollTop=0;if(document.activeElement instanceof HTMLElement)document.activeElement.blur();});await page.screenshot({path:`docs/design/evidence/quick/composer-${width}.png`,fullPage:false});
 await dialog.getByRole('button',{name:'Create diary',exact:true}).click();await expect(dialog).not.toBeVisible();await openQuick(page);await dialog.getByLabel('Diary date',{exact:true}).fill('2026-09-08');await expect(dialog.getByRole('combobox',{name:'Save mode',exact:true})).toHaveValue('append');await dialog.getByRole('textbox',{name:'Title',exact:true}).fill('This must not replace the title');await dialog.getByRole('textbox',{name:'Content',exact:true}).fill('A later observation.');
 await page.route('**/api/diaries',async route=>{if(route.request().method()==='POST')await route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({data:{code:'SYS_INTERNAL_ERROR',requestId:'quick-retry'}})});else await route.continue();});await dialog.getByRole('button',{name:'Append to date',exact:true}).click();await expect(dialog.getByTestId('request-id')).toHaveText('quick-retry');await page.screenshot({path:`docs/design/evidence/quick/retry-${width}.png`,fullPage:false});await expect(dialog.getByRole('textbox',{name:'Content',exact:true})).toHaveValue('A later observation.');await page.unroute('**/api/diaries');await dialog.getByRole('button',{name:'Append to date',exact:true}).click();await expect(dialog).not.toBeVisible();
 const result=await page.request.get('/api/diaries/by-date?date=2026-09-08');const diary=await result.json();expect(diary.title).toBe('Preserve this title');expect(diary.date).toBe('2026-09-08');expect(diary.content).toContain('My own evidence.');expect(diary.content).toContain('\n\n---\n\nA later observation.');
 const user=(await (await page.request.get('/api/auth/me')).json()).data;await page.evaluate(id=>localStorage.setItem(`diary-quick-draft:${id}`,JSON.stringify({at:Date.now(),value:{date:'2026-09-08',title:'bad',content:'bad',tags:42,kind:'reflection',data:null}})),user.id);await page.evaluate(()=>{Object.defineProperty(window,'SpeechRecognition',{value:undefined,configurable:true});Object.defineProperty(window,'webkitSpeechRecognition',{value:undefined,configurable:true});});await clickNav(page,'Quick diary');await expect(page.getByText('Voice input is unavailable in this browser. You can keep typing.',{exact:true})).toBeVisible();await expect(page).toHaveURL(/\/diaries\/quick$/);for(const [locale,heading] of [['zh-TW','快速記錄'],['zh-CN','快速记录'],['en','Quick diary']] as const){await selectLocale(page, locale);await expect(page.getByRole('heading',{name:heading,exact:true})).toBeVisible();}
 await page.getByRole('textbox',{name:'Content',exact:true}).fill('Clear this private draft on logout.');await expect(page.getByText('Draft saved on this device for 24 hours.',{exact:true})).toBeVisible();await signOut(page);expect(await page.evaluate(()=>Object.keys(localStorage).filter(key=>key.startsWith('diary-quick-draft:')))).toEqual([]);
});

test('SPX reflection recovery preserves manual condition and writing',async({page})=>{
 const email=`quick-spx-${randomUUID()}@example.test`,password='synthetic-quick-password';await page.request.post('/api/auth/register',{data:{email,password}});await page.goto('/login');await selectLocale(page, 'en');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/new$/);await selectLocale(page, 'en');await clickNav(page,'Quick diary');
 await page.getByRole('combobox',{name:'Writing template',exact:true}).selectOption('reflection');await page.getByRole('combobox',{name:'Market condition',exact:true}).selectOption('rangeBound');await page.getByRole('textbox',{name:'Content',exact:true}).fill('Keep my handwritten reasoning.');
 let failed=true;await page.route('**/api/market/spx-session',route=>failed?route.fulfill({status:502,contentType:'application/json',body:JSON.stringify({data:{code:'MARKET_PROVIDER_UNAVAILABLE',requestId:'spx-fixture-error'}})}):route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({symbol:'SPX',sourceSymbol:'SPY',condition:'strongUp',price:101.5,previousClose:100,open:100,high:102,low:99,change:1.5,changePercent:1.5,intradayMovePercent:1.5,openGapPercent:0,asOf:'2026-09-05T12:00:00.000Z'})}));
 await page.getByRole('button',{name:'Use SPX session',exact:true}).click();await expect(page.getByTestId('request-id')).toHaveText('spx-fixture-error');await expect(page.getByRole('combobox',{name:'Market condition',exact:true})).toHaveValue('rangeBound');failed=false;await page.getByRole('button',{name:'Use SPX session',exact:true}).click();await expect(page.getByRole('combobox',{name:'Market condition',exact:true})).toHaveValue('strongUp');await expect(page.getByRole('textbox',{name:'Content',exact:true})).toHaveValue('Keep my handwritten reasoning.');await page.getByRole('button',{name:'Apply template changes',exact:true}).click();await expect(page.getByRole('textbox',{name:'Content',exact:true})).toHaveValue(/Keep my handwritten reasoning.[\s\S]*Strong rally/);
});
