import { expect, test, selectLocale } from '../support/e2e'

test('relative value and seasonality preserve scoped history and real capture destinations', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/login')
  await selectLocale(page, 'en')
  await page.getByLabel('Email', { exact: true }).fill('rotation-admin@example.test')
  await page.getByLabel('Password', { exact: true }).fill('synthetic-rotation-admin-password')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page).toHaveURL(/\/diaries\/new$/)

  await page.goto('/tools/relative-value')
  await selectLocale(page, 'en')
  await expect(page.getByRole('heading', { level: 1, name: 'Relative value', exact: true })).toBeVisible()
  await expect(page.getByRole('row').filter({ hasText: 'Primary price' }).first()).toBeVisible()
  await expect(page.getByText(/Primary ÷ comparison/)).toBeVisible()
  await page.screenshot({ path: 'docs/design/evidence/relative-value/desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('.market-history-chart')).toBeVisible()
  await page.screenshot({ path: 'docs/design/evidence/relative-value/mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 900 })

  const capture = page.getByRole('region', { name: 'Research capture', exact: true })
  await capture.getByRole('button', { name: 'Capture this read', exact: true }).click()
  await expect(capture.getByRole('textbox', { name: 'Editable observation', exact: true })).toHaveValue(/# Relative value/)
  const evidenceSave = page.waitForResponse(response => response.url().includes('/api/stocks/GSPC/evidence') && response.request().method() === 'POST')
  await capture.getByRole('combobox', { name: 'Destination', exact: true }).selectOption('evidence')
  await capture.getByRole('button', { name: 'Save', exact: true }).click()
  expect((await evidenceSave).status()).toBe(200)
  await expect(capture.getByRole('status')).toHaveText('Saved.')

  await capture.getByRole('button', { name: 'Capture this read', exact: true }).click()
  await capture.getByRole('button', { name: 'Capture this read', exact: true }).click()
  await capture.getByRole('combobox', { name: 'Destination', exact: true }).selectOption('diary-append')
  const diarySave = page.waitForResponse(response => response.url().endsWith('/api/diaries') && response.request().method() === 'POST')
  await capture.getByRole('button', { name: 'Save', exact: true }).click()
  expect((await diarySave).status()).toBe(201)

  await page.goto('/tools/seasonality')
  await selectLocale(page, 'en')
  await expect(page.getByRole('heading', { level: 1, name: 'Seasonality', exact: true })).toBeVisible()
  await expect(page.getByText('S&P 500 · monthly averages · 1950+', { exact: true })).toBeVisible()
  await expect(page.getByRole('table')).toHaveCount(1)
  await expect(page.getByRole('row')).toHaveCount(13)
  await selectLocale(page, 'zh-TW')
  await expect(page.getByText('S&P 500・月度平均・1950 年起', { exact: true })).toBeVisible()
  await selectLocale(page, 'en')
  const seasonalityCapture = page.getByRole('region', { name: 'Research capture', exact: true })
  await seasonalityCapture.getByRole('button', { name: 'Capture this read', exact: true }).click()
  await expect(seasonalityCapture.getByRole('combobox', { name: 'Destination', exact: true })).toHaveValue('diary-append')
  const seasonalitySave = page.waitForResponse(response => response.url().endsWith('/api/diaries') && response.request().method() === 'POST')
  await seasonalityCapture.getByRole('button', { name: 'Save', exact: true }).click()
  expect((await seasonalitySave).status()).toBe(201)
})
