import { randomUUID } from 'node:crypto';
import { expect,test, selectLocale, selectTheme } from '../support/e2e';
test.use({timezoneId:'UTC'});
for(const width of [1440,390])test(`SELL partial close, oversell rollback and full close at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});const email=`sell-${randomUUID()}@example.test`,password='synthetic-sell-password';await page.request.post('/api/auth/register',{data:{email,password}});await page.goto('/login?returnTo=%2Fdiaries%2Fnew');await selectLocale(page, 'en');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/new$/);await selectLocale(page, 'en');
 const csrf=(await page.context().cookies()).find(item=>item.name==='csrf-token')!.value;const instant=(days:number)=>new Date(Date.now()-days*86400000).toISOString();const buyAt=instant(3),sellAt=instant(2),closeAt=instant(1);
 expect((await page.request.post('/api/diaries',{headers:{'x-csrf-token':csrf},data:{date:buyAt.slice(0,10),title:'Initial purchases',content:'Two fills.',transactions:[{symbol:'AAPL',type:'BUY',quantity:'1.25',price:'10.1',tradeDate:buyAt},{symbol:'AAPL',type:'BUY',quantity:'0.75',price:'12.3',tradeDate:buyAt}]}})).status()).toBe(201);
 async function sale(at:string,quantity:string,price:string){await page.goto('/diaries/new');await page.getByLabel('Diary date',{exact:true}).fill(at.slice(0,10));await page.getByRole('textbox',{name:'Title',exact:true}).fill('Realized decision');await page.getByRole('textbox',{name:'Content',exact:true}).fill('Follow the recorded exit conditions.');await page.getByRole('button',{name:'Add sale',exact:true}).click();const row=page.locator('.buy-row');await row.getByRole('textbox',{name:'Symbol',exact:true}).fill('AAPL');await row.getByRole('textbox',{name:'Quantity',exact:true}).fill(quantity);await row.getByRole('textbox',{name:'Price per share',exact:true}).fill(price);await row.getByLabel('Trade date and time (device time)',{exact:true}).fill(at.slice(0,16));return row;}
 const row=await sale(sellAt,'3','20');await page.getByRole('button',{name:'Save diary',exact:true}).click();await expect(page.getByTestId('error-code')).toHaveText('SYS_VALIDATION_ERROR');await expect(page.getByText(/A sale cannot exceed the balance/)).toBeVisible();await expect(row.getByRole('textbox',{name:'Quantity',exact:true})).toHaveValue('3');expect(await(await page.request.get('/api/diaries/by-date?date='+sellAt.slice(0,10))).json()).toBeNull();
 await row.getByRole('textbox',{name:'Quantity',exact:true}).fill('0.5');if(width===390)await selectTheme(page, 'dark');await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo({top:0,behavior:'instant'});});await page.screenshot({path:`.impeccable/review/sell-editor-${width}.png`,fullPage:true});await page.getByRole('button',{name:'Save diary',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/\d+$/);await page.getByRole('link',{name:'View holdings',exact:true}).click();expect(await(await page.request.get('/api/stocks/holdings')).json()).toEqual([{symbol:'AAPL',quantity:'1.5',avgCost:'10.925',totalCost:'16.3875'}]);await expect(page.locator('.realized-results')).toContainText('4.54');
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:`.impeccable/review/sell-holdings-${width}.png`,fullPage:true});
 await sale(closeAt,'1.5','8');await page.getByRole('button',{name:'Save diary',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/\d+$/);await page.goto('/stocks');await expect(page.getByText('No open holdings. Record a purchase in a diary to begin.',{exact:true})).toBeVisible();expect(await(await page.request.get('/api/stocks/holdings')).json()).toEqual([]);await expect(page.locator('.realized-results')).toContainText('-4.39');const recent=await(await page.request.get('/api/stats/recent-trades')).json();expect(recent.trades.map((trade:{realizedPnL:string})=>trade.realizedPnL)).toEqual(['-4.39','4.54']);
});
