import { test, expect, selectLocale, selectTheme } from '../support/e2e'
import { configureSyntheticAi } from '../support/ai-e2e'

test('admin manages immutable defaults, synthetic testing, activation and rollback at desktop and mobile widths', async ({ page, browser }) => {
  const provider = await configureSyntheticAi(browser)
  try {
    expect((await page.request.post('/api/auth/login', { data: { email: 'ai-admin@example.test', password: 'synthetic-ai-admin-password' } })).status()).toBe(200)
    expect((await page.request.get('/api/auth/me')).status()).toBe(200)
    await page.setViewportSize({ width: 1440, height: 900 })
    const preferences = page.waitForResponse(response => new URL(response.url()).pathname === '/api/user/settings' && response.request().method() === 'GET' && response.ok())
    await page.goto('/admin/ai/prompts'); await preferences; await selectLocale(page, 'en')
    await expect(page.getByRole('heading', { name: 'Prompt registry' })).toBeVisible()
    await expect(page.getByRole('textbox', { name: 'User template', exact: true })).toHaveAttribute('readonly', '')
    await expect(page.getByRole('button', { name: 'Save new version', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Preview', exact: true }).click()
    await expect(page.getByTestId('prompt-playground-result')).toContainText('Preview only')
    await page.screenshot({ path: 'docs/design/evidence/shared-prompts/default-1440.png', fullPage: true })

    await page.getByRole('button', { name: 'Create from default', exact: true }).click()
    await expect(page.getByLabel('Version name', { exact: true })).toHaveValue('Custom prompt')
    await page.getByLabel('Version name', { exact: true }).fill('Synthetic weekly guidance')
    await page.getByRole('textbox', { name: 'User template', exact: true }).fill('Review {{period_label}} in {{locale}}. Ask only evidence-based review questions.')
    await expect(page.getByRole('button', { name: 'Run synthetic test', exact: true })).toBeDisabled()
    await page.getByRole('button', { name: 'Save new version', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Run synthetic test', exact: true })).toBeEnabled()
    await page.getByRole('button', { name: 'Run synthetic test', exact: true }).click()
    await expect(page.getByTestId('prompt-playground-result')).toContainText('Output validation passed')
    await expect(page.locator('.admin-prompt-audit')).toContainText('registry.test.passed')
    await page.getByText('Test usage', { exact: true }).click()
    await expect(page.getByTestId('prompt-playground-result')).toContainText('"scope": "test"')
    await page.getByRole('button', { name: 'Activate', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Disable override', exact: true })).toBeVisible()
    const activated = await page.getByRole('combobox', { name: 'Prompt version', exact: true }).inputValue()
    await page.getByRole('button', { name: 'Duplicate', exact: true }).click()
    await expect(page.getByLabel('Version name', { exact: true })).toHaveValue('Synthetic weekly guidance (copy)')
    await page.getByRole('button', { name: 'Run synthetic test', exact: true }).click()
    await expect(page.getByTestId('prompt-playground-result')).toContainText('Output validation passed')
    await page.getByRole('button', { name: 'Activate', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
    await page.getByRole('combobox', { name: 'Prompt version', exact: true }).selectOption(activated)
    await page.getByRole('button', { name: 'Roll back to version', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Activate', exact: true })).toBeDisabled()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: 'docs/design/evidence/shared-prompts/override-1440.png', fullPage: true })

    await page.setViewportSize({ width: 390, height: 844 }); await page.evaluate(() => scrollTo(0, 0))
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: 'docs/design/evidence/shared-prompts/override-390.png', fullPage: true })
    await selectTheme(page, 'dark')
    await page.screenshot({ path: 'docs/design/evidence/shared-prompts/override-390-dark.png', fullPage: true })
    await page.getByRole('button', { name: 'Disable override', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
    await expect(page.locator('.admin-prompt-state')).toContainText('System Default')
    await page.getByRole('combobox', { name: 'Prompt version', exact: true }).selectOption(activated)
    await page.getByRole('button', { name: 'Archive', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
    await expect(page.getByRole('textbox', { name: 'User template', exact: true })).toHaveAttribute('readonly', '')
    await page.getByRole('combobox', { name: 'Prompt', exact: true }).selectOption('ai-report.monthly')
    await expect(page.getByRole('combobox', { name: 'Prompt version', exact: true })).toHaveValue('')
    await expect(page.getByRole('heading', { name: 'System Default', exact: true })).toBeVisible()
    await selectLocale(page, 'zh-TW')
    await expect(page.getByRole('heading', { name: '提示詞管理', exact: true })).toBeVisible()
    await selectLocale(page, 'zh-CN')
    await expect(page.getByRole('heading', { name: '提示词管理', exact: true })).toBeVisible()
  } finally { await provider.close() }
})
