import { randomUUID } from 'node:crypto';
import { test, expect } from '../support/e2e';
for (const width of [1440, 390]) test(`Company notes edit and recover at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 });
  const email = `notes-${randomUUID()}@example.test`, password = 'synthetic-notes-password';
  await page.request.post('/api/auth/register', { data: { email, password } });
  await page.goto('/login'); await page.getByTestId('locale-select').selectOption('en');
  await page.getByLabel('Email', { exact: true }).fill(email); await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(page).toHaveURL(/\/diaries\/new$/);
  await page.getByTestId('locale-select').selectOption('en'); await page.goto('/stocks/AAPL');
  const notes = page.getByRole('region', { name: 'Company notes', exact: true });
  await expect(notes.getByText('No notes yet.', { exact: true })).toBeVisible();
  await notes.getByRole('button', { name: 'New note', exact: true }).click();
  await notes.getByLabel('Note title', { exact: true }).fill('My current view');
  await notes.getByLabel('Note content (Markdown)').fill('## A thesis\n\n**Strong evidence** with [safe source](https://example.test).\n\n<script>alert(1)</script>');
  await notes.getByLabel('Note date (UTC)').fill('2026-09-05T10:30');
  await notes.getByRole('button', { name: 'Save note', exact: true }).click();
  await expect(notes.getByTestId('stock-note')).toHaveCount(1); await expect(notes.getByTestId('stock-note')).toContainText('6:30 PM · Asia/Taipei');
  await expect(notes.getByRole('heading', { name: 'A thesis', exact: true })).toBeVisible(); await expect(notes.locator('script')).toHaveCount(0);
  await page.reload(); await expect(notes.getByTestId('stock-note')).toHaveCount(1);
  await notes.getByRole('button', { name: 'Edit note', exact: true }).click();
  await notes.getByLabel('Note title', { exact: true }).fill('Updated view');
  await page.route('**/api/stocks/AAPL/notes/*', route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ data: { code: 'SYS_INTERNAL_ERROR', requestId: 'note-retry' } }) }));
  await notes.getByRole('button', { name: 'Save note', exact: true }).click(); await expect(notes.getByTestId('request-id')).toHaveText('note-retry'); await expect(notes.getByLabel('Note title', { exact: true })).toHaveValue('Updated view');
  await page.unroute('**/api/stocks/AAPL/notes/*'); await notes.getByRole('button', { name: 'Save note', exact: true }).click();
  await expect(notes.getByTestId('stock-note')).toContainText('Updated view'); await expect(notes.getByTestId('stock-note')).toHaveCount(1);
  if (width === 390) await page.getByTestId('theme-select').selectOption('dark');
  await notes.screenshot({ path: `docs/design/evidence/stock-notes/${width}.png` }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await notes.getByLabel('Note source').selectOption('AGENT'); await expect(notes.getByText('No notes yet.', { exact: true })).toBeVisible(); await notes.getByLabel('Note source').selectOption('USER'); await expect(notes.getByTestId('stock-note')).toHaveCount(1);
  for (const [locale, title] of [['zh-TW', '公司筆記'], ['zh-CN', '公司笔记'], ['en', 'Company notes']] as const) { await page.getByTestId('locale-select').selectOption(locale); await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible(); }
  page.once('dialog', dialog => dialog.accept()); await notes.getByRole('button', { name: 'Delete note', exact: true }).click(); await expect(notes.getByTestId('stock-note')).toHaveCount(0);
});

test('Company note pagination, exact instant preservation and unsaved navigation', async ({ page, context }) => {
  const email = `notes-pages-${randomUUID()}@example.test`, password = 'synthetic-notes-password';
  await page.request.post('/api/auth/register', { data: { email, password } });
  await page.goto('/login'); await page.getByTestId('locale-select').selectOption('en');
  await page.getByLabel('Email', { exact: true }).fill(email); await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(page).toHaveURL(/\/diaries\/new$/); await page.getByTestId('locale-select').selectOption('en');
  const headers = { 'x-csrf-token': (await context.cookies()).find(cookie => cookie.name === 'csrf-token')!.value };
  for (let i = 0; i < 21; i++) expect((await page.request.post('/api/stocks/AAPL/notes', { headers, data: { title: `Research ${i}`, content: 'Synthetic long research.\n\n'.repeat(100), date: '2026-09-05T10:30:45.123Z' } })).status()).toBe(200);
  await page.goto('/stocks/AAPL'); const notes = page.getByRole('region', { name: 'Company notes', exact: true });
  await expect(notes.getByTestId('stock-note')).toHaveCount(20); await expect(notes.getByTestId('stock-note').first()).toContainText('Research 20');
  await notes.getByRole('button', { name: 'Next notes', exact: true }).click(); await expect(notes.getByTestId('stock-note')).toHaveCount(1); await expect(notes.getByTestId('stock-note')).toContainText('Research 0');
  await notes.getByRole('button', { name: 'Edit note', exact: true }).click(); await notes.getByLabel('Note title', { exact: true }).fill('Preserve precise time');
  page.once('dialog', dialog => dialog.dismiss()); await page.getByRole('link', { name: 'Watchlist', exact: true }).click(); await expect(page).toHaveURL(/\/stocks\/AAPL$/); await expect(notes.getByLabel('Note title', { exact: true })).toHaveValue('Preserve precise time');
  await notes.locator('.plan-form').screenshot({ path: '.impeccable/review/stock-notes-editor.png' });
  await notes.getByRole('button', { name: 'Save note', exact: true }).click(); await expect(notes.getByTestId('stock-note')).toContainText('Preserve precise time');
  const listed = await (await page.request.get('/api/stocks/AAPL/notes?page=2&limit=20')).json(); expect(listed.data[0].date).toBe('2026-09-05T10:30:45.123Z');
  page.once('dialog', dialog => dialog.accept()); await notes.getByRole('button', { name: 'Delete note', exact: true }).click(); await expect(notes.getByTestId('stock-note')).toHaveCount(20); await expect(notes.getByRole('button', { name: 'Next notes', exact: true })).toBeDisabled();
  await notes.getByRole('button', { name: 'New note', exact: true }).click(); await notes.getByLabel('Note title', { exact: true }).fill('Discard me');
  page.once('dialog', dialog => dialog.accept()); await page.getByRole('link', { name: 'Watchlist', exact: true }).click(); await expect(page).toHaveURL(/\/stocks\/watchlist$/);
  await page.goto('/stocks/AAPL'); await expect(notes.getByTestId('stock-note')).toHaveCount(20); await page.getByTestId('sign-out').click(); await expect(page.getByTestId('stock-note')).toHaveCount(0);
});
