import {randomUUID} from 'node:crypto';
import {test,expect, selectLocale, selectTheme} from '../support/e2e';
for(const width of [1440,390])test(`trade plan exact decimals, lifecycle and diary link at ${width}px`,async({page,context})=>{
 await page.setViewportSize({width,height:900});const email=`plan-${randomUUID()}@example.test`,password='synthetic-plan-password';await page.request.post('/api/auth/register',{data:{email,password}});await page.goto('/login?returnTo=%2Fdiaries%2Fnew');await selectLocale(page, 'en');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/diaries\/new$/);await selectLocale(page, 'en');
 const headers={'x-csrf-token':(await context.cookies()).find(c=>c.name==='csrf-token')!.value};const diary=await(await page.request.post('/api/diaries',{headers,data:{title:'Evidence for the plan',content:'Original reasoning',date:'2026-09-05'}})).json();
 await page.goto('/trade-plans');await expect(page.getByText('No trade plans match these filters.')).toBeVisible();await page.getByRole('link',{name:'New trade plan',exact:true}).click();await expect(page).toHaveURL(/\/trade-plans\/new$/);await expect(page.getByRole('heading',{name:'New trade plan',exact:true})).toBeVisible();await page.getByRole('textbox',{name:'Symbol',exact:true}).fill('aapl');await page.getByRole('textbox',{name:'Setup',exact:true}).fill('Independent demand confirmation');
 const values={ 'Entry price':'123.123456','Entry zone low':'120.000001','Entry zone high':'125.123456','Stop loss':'115.000001','Target price':'150.999999','Maximum position size':'9007199254740991.01'};for(const [name,value]of Object.entries(values))await page.getByRole('textbox',{name,exact:true}).fill(value);
 await page.getByRole('textbox',{name:'Invalidation condition',exact:true}).fill('Two consecutive reports contradict the original thesis.');await page.getByRole('textbox',{name:'Notes',exact:true}).fill('Preserve exact price levels.\nRevisit after the next report.');await page.getByRole('combobox',{name:'Linked diary',exact:true}).selectOption(diary.id);
 await page.getByRole('textbox',{name:'Entry zone high',exact:true}).fill('100');await page.getByRole('button',{name:'Save trade plan',exact:true}).click();await expect(page.getByRole('textbox',{name:'Entry zone high',exact:true})).toHaveAttribute('aria-invalid','true');await page.getByRole('textbox',{name:'Entry zone high',exact:true}).fill(values['Entry zone high']);
 await page.getByRole('button',{name:'Save trade plan',exact:true}).click();await expect(page).toHaveURL(/\/trade-plans\/\d+$/);const id=page.url().split('/').at(-1)!;const persisted=await(await page.request.get(`/api/trade-plans/${id}`)).json();expect(persisted.maxPositionSize).toBe('9007199254740991.01');expect(persisted.entryPrice).toBe('123.123456');expect(persisted.status).toBe('draft');
 await page.getByRole('combobox',{name:'Status',exact:true}).selectOption('active');await page.route(`**/api/trade-plans/${id}`,async route=>{if(route.request().method()==='PUT')await route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({data:{code:'SYS_INTERNAL_ERROR',requestId:'plan-save'}})});else await route.continue();});await page.getByRole('button',{name:'Save trade plan',exact:true}).click();await expect(page.getByTestId('request-id')).toHaveText('plan-save');await expect(page.getByRole('textbox',{name:'Entry price',exact:true})).toHaveValue('123.123456');if(width===390)await selectTheme(page, 'dark');await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();scrollTo({top:0,behavior:'instant'});});await page.screenshot({path:`docs/design/evidence/trade-plans/form-${width}.png`,fullPage:true});
 await page.unroute(`**/api/trade-plans/${id}`);await page.getByRole('button',{name:'Save trade plan',exact:true}).click();await expect(page.getByText('Trade plan saved.',{exact:true})).toBeVisible();await page.getByRole('link',{name:/Read linked diary:/}).click();await expect(page).toHaveURL(new RegExp(`/diaries/${diary.id}$`));
 await page.goto(`/trade-plans/${id}`);await expect(page.getByRole('combobox',{name:'Status',exact:true})).toHaveValue('active');await page.getByRole('combobox',{name:'Linked diary',exact:true}).selectOption('');await page.getByRole('combobox',{name:'Status',exact:true}).selectOption('closed');await page.getByRole('button',{name:'Save trade plan',exact:true}).click();await expect(page.getByText('Trade plan saved.',{exact:true})).toBeVisible();expect((await(await page.request.get(`/api/trade-plans/${id}`)).json()).diaryId).toBeNull();
 await page.goto('/trade-plans');await page.getByRole('combobox',{name:'Status',exact:true}).selectOption('active');await page.getByRole('button',{name:'Apply filters',exact:true}).click();await expect(page.getByText('No trade plans match these filters.')).toBeVisible();await page.getByRole('combobox',{name:'Status',exact:true}).selectOption('closed');await page.getByRole('button',{name:'Apply filters',exact:true}).click();await expect(page.getByRole('link',{name:'AAPL · Independent demand confirmation'})).toBeVisible();await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:`docs/design/evidence/trade-plans/list-${width}.png`,fullPage:true});
 for(const[locale,title]of[['zh-TW','交易計劃'],['zh-CN','交易计划'],['en','Trade plans']]as const){await selectLocale(page, locale);await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('link',{name:'AAPL · Independent demand confirmation'}).click();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Delete trade plan',exact:true}).click();await expect(page).toHaveURL(/\/trade-plans$/);expect((await page.request.get(`/api/trade-plans/${id}`)).status()).toBe(404);
});

test('Trade Plan guest errors offer a safe sign-in return', async ({page}) => {
 await page.goto('/trade-plans'); await selectLocale(page, 'en');
 await expect(page.getByRole('link',{name:'Sign in',exact:true})).toHaveAttribute('href','/login?returnTo=%2Ftrade-plans');
 await page.goto('/trade-plans/1');
 await expect(page.getByRole('link',{name:'Sign in',exact:true})).toHaveAttribute('href','/login?returnTo=%2Ftrade-plans%2F1');
});
