type AiLocale = 'zh-TW' | 'zh-CN' | 'en';

export const aiCopy = {
  en: {
    title: 'AI reports',
    lede: 'Private review reports you trigger yourself. Pick a period, check the local data scope, agree once per data recipient, then generate. Nothing is ever generated on its own.',
    sectionGenerate: 'Generate a report',
    weekly: 'Weekly', monthly: 'Monthly', retrySubmission: 'Retry original request',
    period: 'Period', periodHint: 'Defaults to the last finished period. The current week or month can be selected and is marked partial.',
    previewAction: 'Check local data',
    previewPending: 'Checking your saved records…',
    previewHint: 'Reads your own saved records only. Nothing is sent to any provider.',
    coverageTitle: 'Data coverage',
    coverageDiaries: 'Diaries', coverageTransactions: 'Transactions', coverageHoldings: 'Holdings', coverageDisciplines: 'Discipline rules',
    partialPeriod: 'This period has not ended. Totals are cut off at the snapshot time and never include later records.',
    metricsTitle: 'Period statistics · computed by the server',
    metricUnavailable: 'Not computable from the recorded data.',
    consentTitle: 'Third-party data processing consent',
    consentRecipient: 'Data recipient',
    consentAccept: 'Agree and continue',
    consentCurrent: 'You agreed to the current recipient on {date}.',
    consentWithdraw: 'Withdraw consent',
    consentWithdrawConfirm: 'Withdraw consent? Queued work is cancelled and running work is aborted where possible. Data already sent to the provider cannot be recalled. Existing reports stay until you delete them.',
    consentWithdrawn: 'Consent withdrawn.',
    generate: 'Generate report',
    generateNeedPreview: 'Run the local data check first — generation needs a fresh scope confirmation.',
    generateQueued: 'Generation queued. You can leave this page; the job keeps running and you can come back to it here.',
    generateReused: 'An identical report already exists for this data. Opened it without spending quota.',
    activeJobTitle: 'Job in progress',
    statusQueued: 'Queued', statusRunning: 'Generating', statusSucceeded: 'Completed', statusFailed: 'Failed', statusCancelled: 'Cancelled',
    cancelJob: 'Cancel job',
    cancelConfirm: 'Cancel this job? A queued job is cancelled without contacting the provider. A running job is aborted where possible; if it was already sent, the attempt stays recorded and its result is discarded.',
    cancelDone: 'Job cancelled.',
    regenerate: 'Regenerate',
    regenerateConfirm: 'Regenerate? A new revision is created from the currently saved data and active settings. It can consume quota, and this version is kept.',
    deleteReport: 'Delete report',
    deleteConfirm: 'Delete this report? Its content is removed and cannot be recovered. Already-spent quota is not refunded.',
    deleteDone: 'Report deleted.',
    historyTitle: 'History', historyEmpty: 'No reports yet. Generate the first one above.', loadMore: 'Load more',
    quotaLine: 'Remaining quota this month: {n} of {total}',
    gateDisabled: 'AI reports are paused for the whole site right now.',
    gateLocked: 'Your account does not have AI report access. An administrator can grant it.',
    gateNotConfigured: 'Generation is not configured yet. An administrator needs to finish the provider setup.',
    gateConsent: 'Agree to third-party data processing before generating.',
    gateQuota: 'This month’s quota is used up.',
    gateWorker: 'No generation worker is available right now. Existing reports stay readable.',
    reportLanguageNote: 'The report language is fixed at generation time. Switching the interface language later does not translate or regenerate it.',
    metaPeriod: 'Period', metaTimezone: 'Timezone', metaLocale: 'Language', metaGeneratedAt: 'Generated at', metaModel: 'Model', metaPromptVersion: 'Prompt version', metaSchemaVersion: 'Schema version', metaSnapshot: 'Data captured at', metaRevision: 'Revision',
    quotaChargeNote: 'Each dispatched generation uses one quota unit even when it fails. Cancelling before dispatch releases the reservation.',
    sourceCurrent: 'Sources are unchanged since generation.',
    sourceChanged: 'Sources may have changed after generation. Re-check them against current records.',
    sourceInvalidated: 'A source was deleted. This report’s content has been invalidated.',
    sectionSummary: 'Summary', sectionDecision: 'Decisions and execution', sectionPosition: 'Position review', sectionMarket: 'Market observations review',
    sectionMarketNote: 'These are the views you recorded at the time — not verified market facts.',
    sectionDiscipline: 'Discipline comparison', sectionNext: 'Focus for next period', sectionLimitations: 'Limitations',
    evidenceRecorded: 'Recorded', evidenceInterpretation: 'Interpretation', evidenceInsufficient: 'Insufficient data',
    assessmentSupported: 'Supported by records', assessmentDeviation: 'Possible deviation', assessmentInsufficient: 'Insufficient evidence',
    followUp: 'Follow-up question',
    sourcesLabel: 'Sources',
    sourceDiary: 'Diary', sourceTransaction: 'Transaction', sourceDiscipline: 'Discipline rule', sourceHolding: 'Holding',
    analysisEmpty: 'Nothing recorded for this section.',
    reportNone: 'Select a report from the history, or generate a new one.',
    reportLoading: 'Loading report…',
    partialBadge: 'Partial period',
    revisionShort: 'rev. {n}',
  },
  'zh-TW': {
    title: 'AI 報告',
    lede: '由你自己手動觸發的私人檢討報告。選擇期間、檢查本地資料範圍、對資料接收方同意一次，再按生成；不會有任何自動生成。',
    sectionGenerate: '生成報告',
    weekly: '週報', monthly: '月報', retrySubmission: '重試原本的提交',
    period: '期間', periodHint: '預設為上一個已結束的週期；也可以選本週或本月，會標示為未結束。',
    previewAction: '檢查本地資料',
    previewPending: '正在讀取你已儲存的紀錄…',
    previewHint: '只讀取你自己已儲存的紀錄，不會傳送給任何接收方。',
    coverageTitle: '資料涵蓋',
    coverageDiaries: '日記', coverageTransactions: '交易', coverageHoldings: '持倉', coverageDisciplines: '交易紀律',
    partialPeriod: '這個期間尚未結束。統計以資料擷取時間截斷，不包含之後的紀錄。',
    metricsTitle: '本期統計・由伺服器計算',
    metricUnavailable: '以已記錄的資料無法計算。',
    consentTitle: '第三方資料處理同意',
    consentRecipient: '資料接收方',
    consentAccept: '同意並繼續',
    consentCurrent: '你已於 {date} 同意目前的接收方。',
    consentWithdraw: '撤回同意',
    consentWithdrawConfirm: '撤回同意？排隊中的工作會被取消，執行中的工作會盡可能中止。已傳送給接收方的資料無法取回；已生成的報告會保留，直到你自行刪除。',
    consentWithdrawn: '已撤回同意。',
    generate: '生成報告',
    generateNeedPreview: '請先檢查本地資料；生成需要最新的範圍確認。',
    generateQueued: '已加入生成佇列。你可以離開本頁，工作會繼續處理，稍後回到這裡查看。',
    generateReused: '相同資料已有報告，已直接開啟，不扣除額度。',
    activeJobTitle: '進行中的工作',
    statusQueued: '排隊中', statusRunning: '生成中', statusSucceeded: '已完成', statusFailed: '失敗', statusCancelled: '已取消',
    cancelJob: '取消工作',
    cancelConfirm: '取消這個工作？排隊中的工作會直接取消，不會聯絡接收方；執行中的工作會盡可能中止。若已送出，該次成本仍會記錄，結果不會發佈。',
    cancelDone: '工作已取消。',
    regenerate: '重新生成',
    regenerateConfirm: '重新生成？會以目前儲存的資料與現行設定建立新修訂版，可能扣除額度；這一版會保留。',
    deleteReport: '刪除報告',
    deleteConfirm: '刪除這份報告？內容會被移除且無法復原；已消耗的額度不會退回。',
    deleteDone: '報告已刪除。',
    historyTitle: '歷史報告', historyEmpty: '還沒有報告。從上方生成第一份。', loadMore: '載入更多',
    quotaLine: '本月剩餘額度：{n} / {total}',
    gateDisabled: 'AI 報告功能目前全站暫停。',
    gateLocked: '你的帳戶尚未獲得 AI 報告授權，可請管理員開通。',
    gateNotConfigured: '生成尚未設定完成，請管理員先完成資料接收方設定。',
    gateConsent: '生成前請先同意第三方資料處理。',
    gateQuota: '本月生成額度已用完。',
    gateWorker: '目前沒有可用的生成 worker；已生成的報告仍可閱讀。',
    reportLanguageNote: '報告語言在生成時固定；之後切換介面語言不會自動翻譯或重新生成。',
    metaPeriod: '期間', metaTimezone: '時區', metaLocale: '語言', metaGeneratedAt: '生成時間', metaModel: '模型', metaPromptVersion: '提示詞版本', metaSchemaVersion: '資料結構版本', metaSnapshot: '資料擷取時間', metaRevision: '修訂版',
    quotaChargeNote: '每次送出的生成會消耗一個額度單位，即使失敗也一樣；送出前取消則釋放預留。',
    sourceCurrent: '生成後來源未變更。',
    sourceChanged: '來源在生成後可能已變更，請對照目前紀錄重新核對。',
    sourceInvalidated: '來源已被刪除，這份報告的內容已標記失效。',
    sectionSummary: '本期摘要', sectionDecision: '決策與執行', sectionPosition: '持倉檢討', sectionMarket: '大市觀察檢討',
    sectionMarketNote: '以下是你當時記錄的觀點，不是查證後的市場事實。',
    sectionDiscipline: '紀律對照', sectionNext: '下一期重點', sectionLimitations: '限制',
    evidenceRecorded: '有紀錄支持', evidenceInterpretation: '解讀', evidenceInsufficient: '資料不足',
    assessmentSupported: '紀錄支持', assessmentDeviation: '可能偏離', assessmentInsufficient: '證據不足',
    followUp: '後續追問',
    sourcesLabel: '來源',
    sourceDiary: '日記', sourceTransaction: '交易', sourceDiscipline: '紀律規則', sourceHolding: '持倉',
    analysisEmpty: '此區塊沒有內容。',
    reportNone: '從歷史報告選擇一份，或生成新報告。',
    reportLoading: '正在載入報告…',
    partialBadge: '未結束期間',
    revisionShort: '第 {n} 版',
  },
  'zh-CN': {
    title: 'AI 报告',
    lede: '由你自己手动触发的私人检讨报告。选择期间、检查本地数据范围、对数据接收方同意一次，再点击生成；不会有任何自动生成。',
    sectionGenerate: '生成报告',
    weekly: '周报', monthly: '月报', retrySubmission: '重试原来的提交',
    period: '期间', periodHint: '默认为上一个已结束的周期；也可以选本周或本月，会标示为未结束。',
    previewAction: '检查本地数据',
    previewPending: '正在读取你已保存的记录…',
    previewHint: '只读取你自己已保存的记录，不会传送给任何接收方。',
    coverageTitle: '数据涵盖',
    coverageDiaries: '日记', coverageTransactions: '交易', coverageHoldings: '持仓', coverageDisciplines: '交易纪律',
    partialPeriod: '这个期间尚未结束。统计以数据撷取时间截断，不包含之后的记录。',
    metricsTitle: '本期统计・由服务器计算',
    metricUnavailable: '以已记录的数据无法计算。',
    consentTitle: '第三方数据处理同意',
    consentRecipient: '数据接收方',
    consentAccept: '同意并继续',
    consentCurrent: '你已于 {date} 同意目前的接收方。',
    consentWithdraw: '撤回同意',
    consentWithdrawConfirm: '撤回同意？排队中的工作会被取消，执行中的工作会尽可能中止。已传送给接收方的数据无法取回；已生成的报告会保留，直到你自行删除。',
    consentWithdrawn: '已撤回同意。',
    generate: '生成报告',
    generateNeedPreview: '请先检查本地数据；生成需要最新的范围确认。',
    generateQueued: '已加入生成队列。你可以离开本页，工作会继续处理，稍后回到这里查看。',
    generateReused: '相同数据已有报告，已直接打开，不扣除额度。',
    activeJobTitle: '进行中的工作',
    statusQueued: '排队中', statusRunning: '生成中', statusSucceeded: '已完成', statusFailed: '失败', statusCancelled: '已取消',
    cancelJob: '取消工作',
    cancelConfirm: '取消这个工作？排队中的工作会直接取消，不会联络接收方；执行中的工作会尽可能中止。若已送出，该次成本仍会记录，结果不会发布。',
    cancelDone: '工作已取消。',
    regenerate: '重新生成',
    regenerateConfirm: '重新生成？会以目前保存的数据与现行设置建立新修订版，可能扣除额度；这一版会保留。',
    deleteReport: '删除报告',
    deleteConfirm: '删除这份报告？内容会被移除且无法复原；已消耗的额度不会退回。',
    deleteDone: '报告已删除。',
    historyTitle: '历史报告', historyEmpty: '还没有报告。从上方生成第一份。', loadMore: '加载更多',
    quotaLine: '本月剩余额度：{n} / {total}',
    gateDisabled: 'AI 报告功能目前全站暂停。',
    gateLocked: '你的账户尚未获得 AI 报告授权，可请管理员开通。',
    gateNotConfigured: '生成尚未设置完成，请管理员先完成数据接收方设置。',
    gateConsent: '生成前请先同意第三方数据处理。',
    gateQuota: '本月生成额度已用完。',
    gateWorker: '目前没有可用的生成 worker；已生成的报告仍可阅读。',
    reportLanguageNote: '报告语言在生成时固定；之后切换界面语言不会自动翻译或重新生成。',
    metaPeriod: '期间', metaTimezone: '时区', metaLocale: '语言', metaGeneratedAt: '生成时间', metaModel: '模型', metaPromptVersion: '提示词版本', metaSchemaVersion: '数据结构版本', metaSnapshot: '数据撷取时间', metaRevision: '修订版',
    quotaChargeNote: '每次送出的生成会消耗一个额度单位，即使失败也一样；送出前取消则释放预留。',
    sourceCurrent: '生成后来源未变更。',
    sourceChanged: '来源在生成后可能已变更，请对照目前记录重新核对。',
    sourceInvalidated: '来源已被删除，这份报告的内容已标示失效。',
    sectionSummary: '本期摘要', sectionDecision: '决策与执行', sectionPosition: '持仓检讨', sectionMarket: '大市观察检讨',
    sectionMarketNote: '以下是你当时记录的观点，不是查证后的市场事实。',
    sectionDiscipline: '纪律对照', sectionNext: '下期重点', sectionLimitations: '限制',
    evidenceRecorded: '有纪录支持', evidenceInterpretation: '解读', evidenceInsufficient: '数据不足',
    assessmentSupported: '纪录支持', assessmentDeviation: '可能偏离', assessmentInsufficient: '证据不足',
    followUp: '后续追问',
    sourcesLabel: '来源',
    sourceDiary: '日记', sourceTransaction: '交易', sourceDiscipline: '纪律规则', sourceHolding: '持仓',
    analysisEmpty: '此区块没有内容。',
    reportNone: '从历史报告选择一份，或生成新报告。',
    reportLoading: '正在加载报告…',
    partialBadge: '未结束期间',
    revisionShort: '第 {n} 版',
  },
} as const;

export type AiCopy = (typeof aiCopy)[AiLocale];

/** Fixed English strings that the domain layer emits for metrics, units and coverage notes. */
const aiDomainMetricLabels: Record<string, string> = {
  'diary.count': 'Recorded diaries',
  'diary.recorded_days': 'Recorded diary days',
  'period.calendar_days': 'Period calendar days',
  'transaction.count': 'Recorded transactions',
  'transaction.buy_count': 'Recorded buys',
  'transaction.sell_count': 'Recorded sells',
  'transaction.symbol_count': 'Traded symbols',
  'ledger.closed_trade_count': 'Closed trade cases',
  'holding.open_count': 'Open holdings',
  'discipline.count': 'Current discipline rules',
  'ledger.realized_pnl': 'Realized P&L aggregate',
};
const aiDomainUnits: Record<string, string> = {
  count: 'count', calendar_days: 'calendar days', shares_or_units: 'shares/units', currency_unknown: 'currency unknown',
};
const aiDomainNotes: Record<string, string> = {
  'The selected period is partial and is capped at snapshotCapturedAt.': 'partial-period note',
  'No transactions are recorded inside the selected period.': 'no transactions',
  'No date-only diary is recorded inside the selected period.': 'no diaries',
  'No open holding is supported by the recorded ledger at the cutoff.': 'no holdings',
  'Discipline content is a generation-time snapshot; historical effective dates are unavailable.': 'discipline snapshot note',
  'Transaction currency and account scope are not recorded; cross-currency totals are unavailable.': 'currency note',
};

export const aiMetricCopy: Record<AiLocale, {
  labels: Record<string, string>
  units: Record<string, string>
  notes: Record<string, string>
}> = {
  en: {
    labels: Object.fromEntries(Object.entries(aiDomainMetricLabels).map(([id, label]) => [id, label])),
    units: { ...aiDomainUnits },
    notes: {
      'partial-period note': 'The selected period is partial and is capped at the snapshot time.',
      'no transactions': 'No transactions are recorded inside the selected period.',
      'no diaries': 'No diary is recorded inside the selected period.',
      'no holdings': 'No open holding is supported by the recorded ledger at the cutoff.',
      'discipline snapshot note': 'Discipline content is a generation-time snapshot; historical effective dates are unavailable.',
      'currency note': 'Transaction currency is not recorded; cross-currency totals are unavailable.',
    },
  },
  'zh-TW': {
    labels: {
      'diary.count': '已記錄日記', 'diary.recorded_days': '有日記的天數', 'period.calendar_days': '期間日曆天數',
      'transaction.count': '已記錄交易', 'transaction.buy_count': '已記錄買入', 'transaction.sell_count': '已記錄賣出',
      'transaction.symbol_count': '交易股票數', 'ledger.closed_trade_count': '已平倉交易案例', 'holding.open_count': '未平倉持倉',
      'discipline.count': '現行交易紀律', 'ledger.realized_pnl': '已實現損益合計',
    },
    units: { count: '筆', calendar_days: '天', shares_or_units: '股/單位', currency_unknown: '幣別不明' },
    notes: {
      'partial-period note': '所選期間尚未結束，統計以資料擷取時間截斷。',
      'no transactions': '所選期間內沒有已記錄的交易。',
      'no diaries': '所選期間內沒有已記錄的日記。',
      'no holdings': '在截斷時間點，帳本沒有支持任何未平倉持倉。',
      'discipline snapshot note': '交易紀律是生成當下的快照；無法查證歷史生效日期。',
      'currency note': '交易未記錄幣別；無法進行跨幣別合計。',
    },
  },
  'zh-CN': {
    labels: {
      'diary.count': '已记录日记', 'diary.recorded_days': '有日记的天数', 'period.calendar_days': '期间日历天数',
      'transaction.count': '已记录交易', 'transaction.buy_count': '已记录买入', 'transaction.sell_count': '已记录卖出',
      'transaction.symbol_count': '交易股票数', 'ledger.closed_trade_count': '已平仓交易案例', 'holding.open_count': '未平仓持仓',
      'discipline.count': '现行交易纪律', 'ledger.realized_pnl': '已实现损益合计',
    },
    units: { count: '笔', calendar_days: '天', shares_or_units: '股/单位', currency_unknown: '币别不明' },
    notes: {
      'partial-period note': '所选期间尚未结束，统计以数据撷取时间截断。',
      'no transactions': '所选期间内没有已记录的交易。',
      'no diaries': '所选期间内没有已记录的日记。',
      'no holdings': '在截断时间点，账本没有支持任何未平仓持仓。',
      'discipline snapshot note': '交易纪律是生成当下的快照；无法查证历史生效日期。',
      'currency note': '交易未记录币别；无法进行跨币别合计。',
    },
  },
};

/** Localize a domain metric label/unit/coverage note; unknown values fall back to the server text. */
export function aiMetricText(kind: 'labels' | 'units' | 'notes', value: string, locale: AiLocale): string {
  const table = aiMetricCopy[locale][kind];
  if (table[value]) return table[value];
  if (kind === 'labels') {
    const id = Object.entries(aiDomainMetricLabels).find(([, label]) => label === value)?.[0];
    if (id) return table[id] ?? value;
    const holding = /^(\S+) recorded (quantity|cost basis)$/.exec(value);
    if (holding && locale !== 'en') return `${holding[1]} ${locale === 'zh-TW' ? (holding[2] === 'quantity' ? '已記錄數量' : '已記錄成本基礎') : (holding[2] === 'quantity' ? '已记录数量' : '已记录成本基础')}`;
    return aiDomainMetricLabels[value] ?? value;
  }
  if (kind === 'units') return aiDomainUnits[value] ?? value;
  return table[aiDomainNotes[value] ?? ''] ?? value;
}

/** User-facing text for the AI-specific error codes; never echoes provider bodies. */
const aiErrorMessages: Record<string, [string, string, string]> = {
  AI_REPORTS_DISABLED: ['AI 報告功能目前全站暫停。', 'AI 报告功能目前全站暂停。', 'AI reports are paused for the whole site right now.'],
  AI_NOT_CONFIGURED: ['管理員尚未完成 AI 設定，暫時無法生成。', '管理员尚未完成 AI 设置，暂时无法生成。', 'Generation is not configured yet. An administrator needs to finish the setup.'],
  AI_ACCESS_DENIED: ['你的帳戶沒有這項 AI 操作的授權。', '你的账户没有这项 AI 操作的授权。', 'Your account does not have access to this AI action.'],
  AI_CONSENT_REQUIRED: ['請先同意第三方資料處理。', '请先同意第三方数据处理。', 'Agree to third-party data processing first.'],
  AI_CONFIG_CHANGED: ['AI 設定已變更，請重新檢查資料範圍後再試。', 'AI 设置已变更，请重新检查数据范围后再试。', 'The AI configuration changed. Re-run the local check and try again.'],
  AI_PREVIEW_CHANGED: ['資料範圍已變更，請重新檢查本地資料並確認後再生成。', '数据范围已变更，请重新检查本地数据并确认后再生成。', 'The data scope changed. Re-run the local check and confirm before generating.'],
  AI_REPORT_NO_DATA: ['這個期間沒有可分析的日記、交易或持倉；未呼叫模型，也沒有扣除額度。', '这个期间没有可分析的日记、交易或持仓；未调用模型，也没有扣除额度。', 'No analyzable diaries, transactions or holdings for this period. No model call was made and no quota was spent.'],
  AI_REPORT_CONTEXT_TOO_LARGE: ['這個期間的資料超出單次上限。可以改用週報，或請管理員調整設定。', '这个期间的数据超出单次上限。可以改用周报，或请管理员调整设置。', 'This period exceeds the single-request limit. Try a weekly report, or ask an administrator to adjust the settings.'],
  AI_REPORT_ALREADY_RUNNING: ['你已有一個進行中的生成工作，完成後再試。', '你已有一个进行中的生成工作，完成后再试。', 'You already have a generation job in progress. Try again after it finishes.'],
  AI_QUOTA_EXCEEDED: ['本月生成額度已用完。', '本月生成额度已用完。', 'This month’s generation quota is used up.'],
  AI_PROVIDER_RATE_LIMITED: ['接收方暫時限流，請稍後再手動重試。', '接收方暂时限流，请稍后手动重试。', 'The provider is rate-limiting right now. Retry manually later.'],
  AI_PROVIDER_TIMEOUT: ['接收方逾時，這次生成失敗；額度可能已消耗。', '接收方超时，这次生成失败；额度可能已消耗。', 'The provider timed out and this generation failed; quota may have been spent.'],
  AI_PROVIDER_OUTCOME_UNKNOWN: ['無法確認這次呼叫的結果；系統已保守記錄成本，不會自動重送。', '无法确认这次调用的结果；系统已保守记录成本，不会自动重送。', 'The outcome of this call is unknown. The cost is recorded conservatively and nothing is re-sent automatically.'],
  AI_OUTPUT_INVALID: ['模型輸出未通過驗證，這份報告不會顯示；可以重新生成。', '模型输出未通过验证，这份报告不会显示；可以重新生成。', 'The model output failed validation. This report is not shown; you can regenerate.'],
  AI_SOURCE_INVALIDATED: ['相關來源已被刪除，這份報告已失效。', '相关来源已被删除，这份报告已失效。', 'A related source was deleted and this report is invalidated.'],
  AI_WORKER_UNAVAILABLE: ['目前沒有可用的生成 worker，請稍後再試。', '目前没有可用的生成 worker，请稍后再试。', 'No generation worker is available right now. Try again later.'],
};

export function aiFailureText(code: string | undefined, locale: AiLocale): string | null {
  if (!code) return null;
  const entry = aiErrorMessages[code];
  return entry ? entry[locale === 'zh-TW' ? 0 : locale === 'zh-CN' ? 1 : 2] : null;
}

export const adminAiCopy = {
  en: {
    title: 'AI administration',
    lede: 'Configure the data recipient, review prompts, grant per-user access, and read content-free usage and audit records. Administrators never see other users’ report content.',
    denied: 'You do not have permission to manage AI settings.',
    sectionProvider: 'Provider', sectionPrompts: 'Prompts', sectionAccess: 'Access', sectionUsage: 'Usage & audit',
    generationEnabled: 'Allow generation site-wide',
    generationEnabledNote: 'Switching off stops new generation and cancels unfinished jobs. Existing reports stay readable to granted owners.',
    workerOnline: 'Worker online · last heartbeat {time}',
    workerOffline: 'Worker offline or no heartbeat recorded yet.',
    providerEmpty: 'No provider configuration yet. Save a draft, run the paid test, then publish.',
    fieldDisplayName: 'Display name', fieldBaseUrl: 'Base URL', fieldModel: 'Model ID', refreshModels: 'Load model list', modelsReady: 'Model list loaded from the provider.',
    fieldThinking: 'Thinking mode', thinkingEnabled: 'Enabled', thinkingDisabled: 'Disabled',
    fieldMaxInput: 'Max input tokens', fieldMaxOutput: 'Max output tokens', fieldTimeout: 'Timeout (ms)', fieldBudget: 'Monthly budget (cents)',
    fieldRecipientName: 'Recipient name shown to users', fieldDisclosureVersion: 'Disclosure version', fieldDisclosureText: 'Disclosure text',
    pricingHeading: 'Pricing (estimates only)',
    fieldPricingCurrency: 'Currency (ISO code)', fieldPricingVersion: 'Price version', fieldInputPrice: 'Input price per million tokens (cents)', fieldOutputPrice: 'Output price per million tokens (cents)', fieldReservation: 'Cost reserved per generation (cents)',
    keyHeading: 'API key', keyStored: 'A key is stored and is never shown again.', keyMissing: 'No key stored.',
    keyKeep: 'Keep current key', keyReplace: 'Replace key', keyClear: 'Clear stored key', fieldApiKey: 'New key',
    saveDraft: 'Save draft', testProvider: 'Run paid test', publishProvider: 'Publish',
    testConfirm: 'Run the paid connection test? It sends one synthetic request to the configured provider and the cost is recorded site-wide.',
    publishConfirm: 'Publish this configuration? Queued jobs depending on the replaced version are cancelled and running jobs are aborted where possible; their results are not published. When the data recipient changes, users must consent again.',
    statusDraft: 'Draft', statusPublished: 'Published',
    lastTest: 'Last test', testPassed: 'passed', testFailed: 'failed', testNever: 'not run',
    revision: 'Revision {n}',
    saved: 'Saved.', revisionConflict: 'The settings changed while you were editing. Reload the page and try again.',
    promptWeekly: 'Weekly prompt', promptMonthly: 'Monthly prompt', promptTemplate: 'Template',
    promptHint: 'Allowed placeholders: {{locale}}, {{period_label}}, {{period_start}}, {{period_end}}. The data package is added by the system and cannot be changed here.',
    promptSave: 'Save draft', promptTest: 'Paid test (synthetic data)', promptPublish: 'Publish new version', promptRestore: 'Restore default template',
    promptPublishConfirm: 'Publish this prompt version? Jobs queued for the replaced version are cancelled; running jobs are aborted where possible and their results are not published.',
    promptRestoreConfirm: 'Restore the default template? This records a new version; earlier versions are kept.',
    promptTestResult: 'Synthetic test output', promptTestRunning: 'Running the synthetic test…',
    promptHistory: 'Version history', promptNone: 'No prompt version yet.',
    versionDraft: 'draft', versionPublished: 'published', versionDefault: 'default',
    accessSearch: 'Search email or name', accessSearchAction: 'Search', accessEmail: 'Email', accessName: 'Name', accessEnabled: 'Granted', accessQuota: 'Monthly quota', accessSave: 'Save', accessEmpty: 'No matching accounts.',
    usageMonth: 'Month (UTC)', usageUser: 'User ID (optional)', usageOwner: 'Owner', usageReserved: 'Reserved', usageReservedCost: 'Reserved cost (cents)', usageConsumed: 'Consumed', usageReleased: 'Released', usageUnknown: 'Unknown outcome', usageInputTokens: 'Input tokens', usageOutputTokens: 'Output tokens', usageEstimated: 'Estimated cost (cents)', usageEmpty: 'No usage recorded for this selection.', usageGlobal: 'Global', usageCap: 'Showing at most 50 rows; usage is aggregated per owner and UTC month.',
    auditHeading: 'Audit log', auditEmpty: 'No audit events yet.', auditActor: 'Actor', auditAction: 'Action', auditTarget: 'Target', auditSummary: 'Summary', auditTime: 'Time',
    loadMore: 'Load more',
  },
  'zh-TW': {
    title: 'AI 報告管理',
    lede: '設定資料接收方、審閱提示詞、逐人授權，並查看不包含私人內容的用量與操作紀錄。管理員無法查看其他使用者的報告內容。',
    denied: '你沒有管理 AI 設定的權限。',
    sectionProvider: '資料接收方', sectionPrompts: '提示詞', sectionAccess: '使用授權', sectionUsage: '用量與稽核',
    generationEnabled: '全站開放生成',
    generationEnabledNote: '關閉後停止新生成並取消未完成工作；已生成報告對獲授權的擁有者仍可閱讀。',
    workerOnline: 'Worker 在線・最近心跳 {time}',
    workerOffline: 'Worker 離線，或尚未記錄心跳。',
    providerEmpty: '尚未設定資料接收方。請先儲存草稿、執行付費測試，再發佈。',
    fieldDisplayName: '顯示名稱', fieldBaseUrl: 'Base URL', fieldModel: '模型 ID', refreshModels: '載入模型清單', modelsReady: '已從接收方載入模型清單。',
    fieldThinking: 'Thinking 模式', thinkingEnabled: '開啟', thinkingDisabled: '關閉',
    fieldMaxInput: '輸入上限 (tokens)', fieldMaxOutput: '輸出上限 (tokens)', fieldTimeout: '逾時 (毫秒)', fieldBudget: '每月預算 (分)',
    fieldRecipientName: '向使用者顯示的接收方名稱', fieldDisclosureVersion: '揭露說明版本', fieldDisclosureText: '揭露說明內容',
    pricingHeading: '計價（僅供估算）',
    fieldPricingCurrency: '幣別 (ISO)', fieldPricingVersion: '價格版本', fieldInputPrice: '輸入每百萬 tokens 價格 (分)', fieldOutputPrice: '輸出每百萬 tokens 價格 (分)', fieldReservation: '每次生成預留成本 (分)',
    keyHeading: 'API 金鑰', keyStored: '已儲存金鑰，之後不會再顯示。', keyMissing: '尚未儲存金鑰。',
    keyKeep: '保留現有金鑰', keyReplace: '更換金鑰', keyClear: '清除已儲存金鑰', fieldApiKey: '新金鑰',
    saveDraft: '儲存草稿', testProvider: '執行付費測試', publishProvider: '發佈',
    testConfirm: '執行付費連線測試？會向已設定的接收方發送一次合成請求，費用計入全站用量。',
    publishConfirm: '發佈這份設定？依賴被替換版本的排隊工作會被取消，執行中的工作會嘗試中止，結果不會發佈。資料接收方變更時，使用者需要重新同意。',
    statusDraft: '草稿', statusPublished: '已發佈',
    lastTest: '上次測試', testPassed: '通過', testFailed: '失敗', testNever: '尚未測試',
    revision: '第 {n} 版',
    saved: '已儲存。', revisionConflict: '你編輯期間設定已被其他管理員更新，請重新載入後再試。',
    promptWeekly: '週報提示詞', promptMonthly: '月報提示詞', promptTemplate: '模板',
    promptHint: '可用佔位符：{{locale}}、{{period_label}}、{{period_start}}、{{period_end}}。資料包由系統加入，無法在這裡變更。',
    promptSave: '儲存草稿', promptTest: '付費測試（合成資料）', promptPublish: '發佈新版本', promptRestore: '還原預設模板',
    promptPublishConfirm: '發佈這個提示詞版本？依賴被替換版本的排隊工作會被取消；執行中的工作會嘗試中止，結果不會發佈。',
    promptRestoreConfirm: '還原預設模板？會記錄一個新版本；之前的版本保留。',
    promptTestResult: '合成測試輸出', promptTestRunning: '正在執行合成測試…',
    promptHistory: '版本紀錄', promptNone: '尚無提示詞版本。',
    versionDraft: '草稿', versionPublished: '已發佈', versionDefault: '預設',
    accessSearch: '搜尋電郵或名稱', accessSearchAction: '搜尋', accessEmail: '電郵', accessName: '名稱', accessEnabled: '已授權', accessQuota: '每月額度', accessSave: '儲存', accessEmpty: '沒有符合的帳戶。',
    usageMonth: '月份 (UTC)', usageUser: '使用者 ID（選填）', usageOwner: '擁有者', usageReserved: '已預留', usageReservedCost: '預留成本 (分)', usageConsumed: '已消耗', usageReleased: '已釋放', usageUnknown: '未知結果', usageInputTokens: '輸入 tokens', usageOutputTokens: '輸出 tokens', usageEstimated: '預估成本 (分)', usageEmpty: '此條件下沒有用量紀錄。', usageGlobal: '全站', usageCap: '最多顯示 50 列；用量按擁有者與 UTC 月份合計。',
    auditHeading: '稽核紀錄', auditEmpty: '尚無稽核事件。', auditActor: '操作者', auditAction: '動作', auditTarget: '對象', auditSummary: '摘要', auditTime: '時間',
    loadMore: '載入更多',
  },
  'zh-CN': {
    title: 'AI 报告管理',
    lede: '设置数据接收方、审阅提示词、逐人授权，并查看不包含私人内容的用量与操作纪录。管理员无法查看其他用户的报告内容。',
    denied: '你没有管理 AI 设置的权限。',
    sectionProvider: '数据接收方', sectionPrompts: '提示词', sectionAccess: '使用授权', sectionUsage: '用量与稽核',
    generationEnabled: '全站开放生成',
    generationEnabledNote: '关闭后停止新生成并取消未完成工作；已生成报告对获授权的拥有者仍可阅读。',
    workerOnline: 'Worker 在线・最近心跳 {time}',
    workerOffline: 'Worker 离线，或尚未记录心跳。',
    providerEmpty: '尚未设置数据接收方。请先保存草稿、执行付费测试，再发布。',
    fieldDisplayName: '显示名称', fieldBaseUrl: 'Base URL', fieldModel: '模型 ID', refreshModels: '加载模型清单', modelsReady: '已从接收方加载模型清单。',
    fieldThinking: 'Thinking 模式', thinkingEnabled: '开启', thinkingDisabled: '关闭',
    fieldMaxInput: '输入上限 (tokens)', fieldMaxOutput: '输出上限 (tokens)', fieldTimeout: '超时 (毫秒)', fieldBudget: '每月预算 (分)',
    fieldRecipientName: '向用户显示的接收方名称', fieldDisclosureVersion: '披露说明版本', fieldDisclosureText: '披露说明内容',
    pricingHeading: '计价（仅供估算）',
    fieldPricingCurrency: '币别 (ISO)', fieldPricingVersion: '价格版本', fieldInputPrice: '输入每百万 tokens 价格 (分)', fieldOutputPrice: '输出每百万 tokens 价格 (分)', fieldReservation: '每次生成预留成本 (分)',
    keyHeading: 'API 密钥', keyStored: '已保存密钥，之后不会再显示。', keyMissing: '尚未保存密钥。',
    keyKeep: '保留现有密钥', keyReplace: '更换密钥', keyClear: '清除已保存密钥', fieldApiKey: '新密钥',
    saveDraft: '保存草稿', testProvider: '执行付费测试', publishProvider: '发布',
    testConfirm: '执行付费连接测试？会向已设置的接收方发送一次合成请求，费用计入全站用量。',
    publishConfirm: '发布这份设置？依赖被替换版本的排队工作会被取消，执行中的工作会尝试中止，结果不会发布。数据接收方变更时，用户需要重新同意。',
    statusDraft: '草稿', statusPublished: '已发布',
    lastTest: '上次测试', testPassed: '通过', testFailed: '失败', testNever: '尚未测试',
    revision: '第 {n} 版',
    saved: '已保存。', revisionConflict: '你编辑期间设置已被其他管理员更新，请重新加载后再试。',
    promptWeekly: '周报提示词', promptMonthly: '月报提示词', promptTemplate: '模板',
    promptHint: '可用占位符：{{locale}}、{{period_label}}、{{period_start}}、{{period_end}}。数据包由系统加入，无法在这里变更。',
    promptSave: '保存草稿', promptTest: '付费测试（合成数据）', promptPublish: '发布新版本', promptRestore: '还原默认模板',
    promptPublishConfirm: '发布这个提示词版本？依赖被替换版本的排队工作会被取消；执行中的工作会尝试中止，结果不会发布。',
    promptRestoreConfirm: '还原默认模板？会记录一个新版本；之前的版本保留。',
    promptTestResult: '合成测试输出', promptTestRunning: '正在执行合成测试…',
    promptHistory: '版本纪录', promptNone: '尚无提示词版本。',
    versionDraft: '草稿', versionPublished: '已发布', versionDefault: '默认',
    accessSearch: '搜索邮箱或名称', accessSearchAction: '搜索', accessEmail: '邮箱', accessName: '名称', accessEnabled: '已授权', accessQuota: '每月额度', accessSave: '保存', accessEmpty: '没有符合条件的账户。',
    usageMonth: '月份 (UTC)', usageUser: '用户 ID（选填）', usageOwner: '拥有者', usageReserved: '已预留', usageReservedCost: '预留成本 (分)', usageConsumed: '已消耗', usageReleased: '已释放', usageUnknown: '未知结果', usageInputTokens: '输入 tokens', usageOutputTokens: '输出 tokens', usageEstimated: '预估成本 (分)', usageEmpty: '此条件下没有用量纪录。', usageGlobal: '全站', usageCap: '最多显示 50 列；用量按拥有者与 UTC 月份合计。',
    auditHeading: '稽核纪录', auditEmpty: '尚无稽核事件。', auditActor: '操作者', auditAction: '动作', auditTarget: '对象', auditSummary: '摘要', auditTime: '时间',
    loadMore: '加载更多',
  },
} as const;

export type AdminAiCopy = (typeof adminAiCopy)[AiLocale];
