import { localTradeChoices,localTradeValue } from './trade-time';
import { useUi } from './ui';
import { ledgerCopy,ledgerEmotions } from './ledger-copy';
import './ledger.css';
export type BuyDraft={key:string;id?:string;type:'BUY'|'SELL';symbol:string;quantity:string;price:string;tradeDate:string;notes:string;strategy:string;emotion:string;instant:string};
export function BuyTransactionFields({value,onChange,pending}:{value:BuyDraft[];onChange:(value:BuyDraft[])=>void;pending:boolean}){
 const {locale}=useUi();const l=ledgerCopy[locale];
 function update(index:number,field:Exclude<keyof BuyDraft,'key'|'id'|'type'>,text:string){onChange(value.map((row,i)=>i===index?{...row,[field]:text,...(field==='tradeDate'?{instant:''}:{})}:row));}
 return <fieldset className="buy-fields" disabled={pending}><legend>{l.title}</legend><p className="muted">{l.hint}</p><p className="muted">{Intl.DateTimeFormat().resolvedOptions().timeZone}</p>{value.map((row,index)=><section className="buy-row" key={row.key} aria-label={`${row.type==='BUY'?l.buy:l.sell} ${index+1}`}><div className="buy-heading"><h3>{row.type==='BUY'?l.buy:l.sell} {index+1}</h3><button type="button" className="secondary" onClick={()=>onChange(value.filter(item=>item.key!==row.key))}>{l.remove} {index+1}</button></div><label>{l.type}<select value={row.type} onChange={event=>onChange(value.map((item,i)=>i===index?{...item,type:event.target.value==='SELL'?'SELL':'BUY'}:item))}><option value="BUY">{l.buy}</option><option value="SELL">{l.sell}</option></select></label><div className="buy-grid">{(['symbol','quantity','price','tradeDate'] as const).map(field=><label key={field}>{l[field]}<input value={row[field]} onChange={e=>update(index,field,e.target.value)} required type={field==='tradeDate'?'datetime-local':'text'} inputMode={field==='quantity'||field==='price'?'decimal':undefined} maxLength={field==='symbol'?20:undefined}/></label>)}</div>{localTradeChoices(row.tradeDate,row.instant).length>1&&<label>UTC<select required value={row.instant} onChange={e=>update(index,'instant',e.target.value)}><option value="">—</option>{localTradeChoices(row.tradeDate,row.instant).map(instant=><option key={instant} value={instant}>{instant}</option>)}</select></label>}<details><summary>{l.details}</summary><div className="buy-grid"><label>{l.strategy}<input value={row.strategy} maxLength={100} onChange={e=>update(index,'strategy',e.target.value)}/></label><label>{l.emotion}<select value={row.emotion} onChange={e=>update(index,'emotion',e.target.value)}><option value="">—</option>{Object.entries(ledgerEmotions[locale]).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label></div><label>{l.notes}<textarea value={row.notes} rows={2} maxLength={10000} onChange={e=>update(index,'notes',e.target.value)}/></label></details></section>)}<p className="muted">{l.precision}</p><div className="actions">{(['BUY','SELL'] as const).map(type=><button key={type} type="button" className="secondary" disabled={value.length>=100} onClick={()=>onChange([...value,{key:crypto.randomUUID(),type,symbol:'',quantity:'',price:'',tradeDate:localTradeValue(new Date()),instant:'',notes:'',strategy:'',emotion:''}])}>{type==='BUY'?l.add:l.addSell}</button>)}</div></fieldset>;
}
