export const calendarCopy = {
  en: {
    title: 'Diary calendar',
    hint: 'Find the day. Revisit the reasoning. Your account timezone controls today and date display; US market closure dates are fixed.',
    month: 'Month',
    previous: 'Previous month',
    next: 'Next month',
    today: 'Today',
    recorded: 'Recorded',
    empty: 'No diary',
    holiday: 'US market closed',
    coverage: 'Monthly coverage',
    entries: 'Recorded days',
    heatmap: 'Past 371 days',
    allDays: 'All calendar days included',
    excluded: 'US market weekends and full closures excluded; early-close half-days remain eligible',
    monthUnavailable: 'US market closure data is available for 2025–2028 only. Coverage is unavailable for this month; diary dates remain accessible.',
    heatmapUnavailable: 'This 371-day range includes an unsupported year. No partial US market closure exclusions are applied.',
    unavailable: 'US market closure data is unavailable. Coverage is not calculated.',
    settings: 'Review preferences',
    transactions: 'transactions',
    emptyMonth: 'No diaries recorded this month.',
    timezone: 'Account timezone',
    select: 'Choose a date',
    heatmapHint: 'Select a day to open its diary or start a quick entry.',
  },
  'zh-TW': {
    title: '日記月曆',
    hint: '找到那一天，重看當時的判斷。帳戶時區只控制今天與日期顯示；美股休市日期固定按市場資料判定。',
    month: '月份',
    previous: '上一個月',
    next: '下一個月',
    today: '今天',
    recorded: '已記錄',
    empty: '未有日記',
    holiday: '美股休市日',
    coverage: '本月覆蓋率',
    entries: '記錄天數',
    heatmap: '過去 371 天',
    allDays: '計算所有日曆日',
    excluded: '已排除週末與美股全日休市日；提早收市日仍可計入',
    monthUnavailable: '美股休市資料目前只涵蓋 2025–2028 年。本月份覆蓋率暫不可用；日記日期仍可使用。',
    heatmapUnavailable: '這段 371 天範圍包含未支援年份，暫不套用美股休市日的部分排除。',
    unavailable: '美股休市資料暫時無法取得，未計算覆蓋率。',
    settings: '查看偏好設定',
    transactions: '筆交易',
    emptyMonth: '這個月尚未有日記。',
    timezone: '帳戶時區',
    select: '選擇日期',
    heatmapHint: '選擇日期以開啟日記，或開始快速記錄。',
  },
  'zh-CN': {
    title: '日记月历',
    hint: '找到那一天，重看当时的判断。账户时区只控制今天与日期显示；美股休市日期固定按市场资料判定。',
    month: '月份',
    previous: '上一个月',
    next: '下一个月',
    today: '今天',
    recorded: '已记录',
    empty: '未有日记',
    holiday: '美股休市日',
    coverage: '本月覆盖率',
    entries: '记录天数',
    heatmap: '过去 371 天',
    allDays: '计算所有日历日',
    excluded: '已排除周末与美股全日休市日；提前收市日仍可计入',
    monthUnavailable: '美股休市资料目前只涵盖 2025–2028 年。本月份覆盖率暂不可用；日记日期仍可使用。',
    heatmapUnavailable: '这段 371 天范围包含未支持年份，暂不套用美股休市日的部分排除。',
    unavailable: '美股休市资料暂时无法取得，未计算覆盖率。',
    settings: '查看偏好设置',
    transactions: '笔交易',
    emptyMonth: '这个月尚未有日记。',
    timezone: '账户时区',
    select: '选择日期',
    heatmapHint: '选择日期以打开日记，或开始快速记录。',
  },
};
