export const diaryListCopy = {
  'en': {
    title: 'Diary library', intro: 'Find the reasoning you recorded, by words, dates or review status.',
    search: 'Search title or content', symbol: 'Company symbol', from: 'From date', to: 'Through date', sort: 'Sort diaries', status: 'Review status', limit: 'Diaries per page',
    newest: 'Newest date first', oldest: 'Oldest date first', titleAsc: 'Title A to Z', titleDesc: 'Title Z to A',
    all: 'All reviews', none: 'Not scheduled', pending: 'Due for review', reviewed: 'Reviewed',
    moreFilters: 'More filters', activeFilters: 'filters active', context: 'Investment context', trades: 'trades',
    apply: 'Apply filters', reset: 'Clear filters', results: 'Matching diaries', empty: 'No diaries match these filters.',
    first: 'Your diary library is empty.', start: 'Write your first diary', previous: 'Previous page', next: 'Next page',
    page: 'Page', of: 'of', total: 'diaries', invalid: 'Check the filters and try again.', tags: 'Tags',
  },
  'zh-TW': {
    title: '日記資料庫', intro: '透過文字、日期或複盤狀態，找回當時記錄的判斷。',
    search: '搜尋標題或內容', symbol: '公司代號', from: '開始日期', to: '結束日期', sort: '日記排序', status: '複盤狀態', limit: '每頁日記數',
    newest: '日期由新到舊', oldest: '日期由舊到新', titleAsc: '標題正序', titleDesc: '標題倒序',
    all: '所有複盤狀態', none: '未安排複盤', pending: '已到期待複盤', reviewed: '已複盤',
    moreFilters: '更多篩選', activeFilters: '項篩選生效中', context: '投資脈絡', trades: '筆交易',
    apply: '套用篩選', reset: '清除篩選', results: '符合條件的日記', empty: '沒有符合這些條件的日記。',
    first: '日記資料庫還未有記錄。', start: '寫第一篇日記', previous: '上一頁', next: '下一頁',
    page: '第', of: '／', total: '篇日記', invalid: '請檢查篩選條件後再試。', tags: '標籤',
  },
  'zh-CN': {
    title: '日记资料库', intro: '通过文字、日期或复盘状态，找回当时记录的判断。',
    search: '搜索标题或内容', symbol: '公司代号', from: '开始日期', to: '结束日期', sort: '日记排序', status: '复盘状态', limit: '每页日记数',
    newest: '日期由新到旧', oldest: '日期由旧到新', titleAsc: '标题正序', titleDesc: '标题倒序',
    all: '所有复盘状态', none: '未安排复盘', pending: '已到期待复盘', reviewed: '已复盘',
    moreFilters: '更多筛选', activeFilters: '项筛选生效中', context: '投资脉络', trades: '笔交易',
    apply: '应用筛选', reset: '清除筛选', results: '符合条件的日记', empty: '没有符合这些条件的日记。',
    first: '日记资料库还没有记录。', start: '写第一篇日记', previous: '上一页', next: '下一页',
    page: '第', of: '／', total: '篇日记', invalid: '请检查筛选条件后重试。', tags: '标签',
  },
}
