export const disciplineCopy = {
 'en': { title: 'Trading principles', intro: 'Keep the rules you want to remember before your next decision.', content: 'Principle', create: 'Add principle', addHeading: 'Add a principle', edit: 'Edit', editingLabel: 'Edit principle {n}', save: 'Save changes', cancel: 'Cancel', remove: 'Delete principle', up: 'Move up', down: 'Move down', emptyHeading: 'No principles yet', empty: 'Add one rule you want to keep practising before your next decision.', exampleLabel: 'For example', example: 'Define the risk and the exit before placing a trade.', draw: 'Read a random principle', drawAnother: 'Draw another', custom: 'From your principles', fallback: 'A reminder to keep writing', number: 'Principle {n}', added: 'Principle added.', updated: 'Principle updated.', deleted: 'Principle deleted.', reordered: 'Order updated.', invalid: 'Enter a principle of 1–255 characters.', uncertain: 'The create result is uncertain. The list was checked; keep this draft and refresh before deciding whether to retry.', discardTitle: 'Discard your unsaved principle?', discard: 'Leaving this page now drops what you have typed. Nothing is saved.', discardConfirm: 'Discard and leave', stay: 'Keep writing', confirmTitle: 'Delete this principle?', confirmBody: 'This removes the principle permanently. It cannot be undone.', createdAt: 'Created', list: 'Your principles', count: '{n} principles', countOne: '1 principle', remaining: '{n} characters left', editingNotice: 'The other rows stay locked until you save or cancel this edit.', shortcut: 'Save with' },
 'zh-TW': { title: '交易紀律', intro: '留下下一次決策前，你希望記住的原則。', content: '紀律內容', create: '新增紀律', addHeading: '新增一條紀律', edit: '編輯', editingLabel: '編輯第 {n} 條紀律', save: '儲存修改', cancel: '取消', remove: '刪除紀律', up: '上移', down: '下移', emptyHeading: '尚未有紀律', empty: '先加入一條你希望在下次決策前持續實踐的原則。', exampleLabel: '例如', example: '下單之前，先寫下風險與離場條件。', draw: '隨機讀一條紀律', drawAnother: '再抽一條', custom: '來自你的紀律', fallback: '提醒自己繼續記錄', number: '第 {n} 條', added: '紀律已新增。', updated: '紀律已更新。', deleted: '紀律已刪除。', reordered: '次序已更新。', invalid: '請輸入 1–255 字的紀律。', uncertain: '建立結果尚未確定。系統已檢查清單；請保留草稿並重新整理後再決定是否重試。', discardTitle: '放棄尚未儲存的紀律？', discard: '現在離開這一頁會丟掉剛輸入的內容，系統不會儲存。', discardConfirm: '放棄並離開', stay: '繼續編寫', confirmTitle: '刪除這條紀律？', confirmBody: '這會永久刪除此紀律，之後無法復原。', createdAt: '建立時間', list: '你的紀律', count: '共 {n} 條紀律', countOne: '共 1 條紀律', remaining: '還可輸入 {n} 字', editingNotice: '儲存或取消這次編輯之前，其他列會暫停操作。', shortcut: '儲存快速鍵' },
 'zh-CN': { title: '交易纪律', intro: '留下下一次决策前，你希望记住的原则。', content: '纪律内容', create: '新增纪律', addHeading: '新增一条纪律', edit: '编辑', editingLabel: '编辑第 {n} 条纪律', save: '保存修改', cancel: '取消', remove: '删除纪律', up: '上移', down: '下移', emptyHeading: '尚未有纪律', empty: '先加入一条你希望在下次决策前持续实践的原则。', exampleLabel: '例如', example: '下单之前，先写下风险与离场条件。', draw: '随机读一条纪律', drawAnother: '再抽一条', custom: '来自你的纪律', fallback: '提醒自己继续记录', number: '第 {n} 条', added: '纪律已新增。', updated: '纪律已更新。', deleted: '纪律已删除。', reordered: '次序已更新。', invalid: '请输入 1–255 字的纪律。', uncertain: '创建结果尚未确定。系统已检查清单；请保留草稿并刷新后再决定是否重试。', discardTitle: '放弃尚未保存的纪律？', discard: '现在离开这一页会丢掉刚输入的内容，系统不会保存。', discardConfirm: '放弃并离开', stay: '继续编写', confirmTitle: '删除这条纪律？', confirmBody: '这会永久删除此纪律，之后无法恢复。', createdAt: '创建时间', list: '你的纪律', count: '共 {n} 条纪律', countOne: '共 1 条纪律', remaining: '还可输入 {n} 字', editingNotice: '保存或取消这次编辑之前，其他行会暂停操作。', shortcut: '保存快捷键' },
};
export type DisciplineLocale = keyof typeof disciplineCopy;
/** "Principle 03" / "第 03 條": the numbered pointer a list row and the drawn block share. */
export function principleNumber(locale: DisciplineLocale, order: number) {
 return disciplineCopy[locale].number.replace('{n}', String(order).padStart(2, '0'));
}
/** The list count beside the heading; English needs its own singular. */
export function principleCount(locale: DisciplineLocale, total: number) {
 return total === 1 ? disciplineCopy[locale].countOne : disciplineCopy[locale].count.replace('{n}', String(total));
}
