import type { Locale } from './destinations'

const copy = {
  en: {
    activity: 'Latest Guru moves', portfolio: 'Portfolio', changes: 'Changes', history: 'History', filings: 'Filings',
    search: 'Search ticker or company', sector: 'Sector', securityType: 'Security type', quantityType: 'Position type', actionFilter: 'Action filter',
    all: 'All', shares: 'Shares', principal: 'Principal', newOnly: 'New positions', increasedOnly: 'Increased positions', reducedOnly: 'Reduced positions',
    sort: 'Sort by', rank: 'Position rank', weight: 'Portfolio weight', value: 'Reported value', change: 'Share change',
    loading: 'Loading prepared portfolio data…', failed: 'Guru portfolio data is temporarily unavailable.', retry: 'Try again', empty: 'No matching data for this quarter.',
    noPeriods: 'No ingested filing periods are available.', noFilings: 'No 13F filings are available.', quarter: 'Reported quarter', status: 'Data state', reportedValue: 'Reported portfolio value', positions: 'Positions',
    topFive: 'Top 5 concentration', topTen: 'Top 10 concentration', hhi: 'HHI', turnover: 'Turnover', coverage: 'Mapping coverage',
    export: 'Export CSV', sharesChange: 'Share change', previous: 'Previous', current: 'Current', previousWeight: 'Previous weight', currentWeight: 'Current weight',
    previousRank: 'Previous rank', currentRank: 'Current rank', rankChange: 'Rank change', largestWeight: 'Largest weight changes', largestRank: 'Largest rank changes',
    newPositions: 'New positions', increased: 'Increased positions', reduced: 'Reduced positions', exited: 'Exited positions', noMoves: 'No comparable position changes.',
    disclosed: '13F holdings are delayed quarter-end disclosures and may not represent the manager’s current or complete portfolio.',
    period: 'Period', filed: 'Filed', accession: 'Accession', form: 'Form', filingState: 'Filing state', amendment: 'Amendment', parser: 'Parser version', source: 'SEC source', documents: 'Source documents',
    company: 'Company', ticker: 'Ticker', type: 'Security type', putCall: 'Put / call', position: 'Position', action: 'Action', reported: 'Reported', rankLabel: 'Rank', details: 'Position history',
    qoqSharesChange: 'QoQ share change', qoqWeightChange: 'QoQ weight change (pp)',
    minimumWeight: 'Minimum portfolio weight (%)', minimumChange: 'Minimum share change (%)', guru: 'Guru', symbol: 'Ticker',
    periodEnd: 'Reported period', sectorAllocation: 'Sector allocation', dataPartial: 'This quarter is partial. The figures and actions below are withheld until its data is ready.',
    statusLabel: (value: string) => value === 'READY' ? 'Ready' : value === 'PARTIAL' ? 'Partial' : value === 'ERROR' ? 'Error' : 'Pending',
  },
  'zh-TW': {
    activity: '大師最新動作', portfolio: '持倉', changes: '變化', history: '歷史', filings: '申報',
    search: '搜尋代號或公司', sector: '產業', securityType: '證券類別', quantityType: '持倉類型', actionFilter: '動作篩選',
    all: '全部', shares: '普通股', principal: '本金證券', newOnly: '新建持倉', increasedOnly: '增加持倉', reducedOnly: '減少持倉',
    sort: '排序方式', rank: '持倉排名', weight: '組合權重', value: '申報價值', change: '股數變化',
    loading: '正在載入已整理的組合資料…', failed: '暫時無法載入大師持倉資料。', retry: '重試', empty: '本季度沒有符合條件的資料。',
    noPeriods: '目前沒有已匯入的申報季度。', noFilings: '目前沒有 13F 申報。', quarter: '申報季度', status: '資料狀態', reportedValue: '申報組合價值', positions: '持倉數',
    topFive: '前五大集中度', topTen: '前十大集中度', hhi: 'HHI', turnover: '換手率', coverage: '映射覆蓋率',
    export: '匯出 CSV', sharesChange: '股數變化', previous: '之前', current: '目前', previousWeight: '之前權重', currentWeight: '目前權重',
    previousRank: '前季排名', currentRank: '目前排名', rankChange: '排名變化', largestWeight: '權重變化最大', largestRank: '排名變化最大',
    newPositions: '新建持倉', increased: '增加持倉', reduced: '減少持倉', exited: '已退出持倉', noMoves: '沒有可比較的持倉變化。',
    disclosed: '13F 是延遲發布的季末持倉披露，未必反映管理人目前或完整的投資組合。',
    period: '申報期間', filed: '申報日期', accession: '申報編號', form: '表格', filingState: '申報狀態', amendment: '修訂資訊', parser: '解析器版本', source: 'SEC 來源', documents: '來源文件',
    company: '公司', ticker: '代號', type: '證券類別', putCall: '認沽／認購', position: '持倉', action: '動作', reported: '申報資料', rankLabel: '排名', details: '持倉歷史',
    qoqSharesChange: '季比股數變化', qoqWeightChange: '季比權重變化（百分點）',
    minimumWeight: '最低組合權重（%）', minimumChange: '最低股數變化（%）', guru: '投資大師', symbol: '代號',
    periodEnd: '申報期間', sectorAllocation: '產業配置', dataPartial: '本季度資料不完整。資料就緒前會隱藏持倉指標與動作。',
    statusLabel: (value: string) => value === 'READY' ? '資料就緒' : value === 'PARTIAL' ? '資料不完整' : value === 'ERROR' ? '資料錯誤' : '等待處理',
  },
  'zh-CN': {
    activity: '大师最新动作', portfolio: '持仓', changes: '变化', history: '历史', filings: '申报',
    search: '搜索代码或公司', sector: '行业', securityType: '证券类别', quantityType: '持仓类型', actionFilter: '动作筛选',
    all: '全部', shares: '普通股', principal: '本金证券', newOnly: '新建持仓', increasedOnly: '增加持仓', reducedOnly: '减少持仓',
    sort: '排序方式', rank: '持仓排名', weight: '组合权重', value: '申报价值', change: '股数变化',
    loading: '正在加载已整理的组合资料…', failed: '暂时无法加载大师持仓数据。', retry: '重试', empty: '本季度没有符合条件的数据。',
    noPeriods: '目前没有已导入的申报季度。', noFilings: '目前没有 13F 申报。', quarter: '申报季度', status: '资料状态', reportedValue: '申报组合价值', positions: '持仓数',
    topFive: '前五大集中度', topTen: '前十大集中度', hhi: 'HHI', turnover: '换手率', coverage: '映射覆盖率',
    export: '导出 CSV', sharesChange: '股数变化', previous: '之前', current: '目前', previousWeight: '之前权重', currentWeight: '目前权重',
    previousRank: '前季排名', currentRank: '目前排名', rankChange: '排名变化', largestWeight: '权重变化最大', largestRank: '排名变化最大',
    newPositions: '新建持仓', increased: '增加持仓', reduced: '减少持仓', exited: '已退出持仓', noMoves: '没有可比较的持仓变化。',
    disclosed: '13F 是延迟发布的季末持仓披露，不一定反映管理人当前或完整的投资组合。',
    period: '申报期间', filed: '申报日期', accession: '申报编号', form: '表格', filingState: '申报状态', amendment: '修订信息', parser: '解析器版本', source: 'SEC 来源', documents: '来源文件',
    company: '公司', ticker: '代码', type: '证券类别', putCall: '认沽／认购', position: '持仓', action: '动作', reported: '申报资料', rankLabel: '排名', details: '持仓历史',
    qoqSharesChange: '季比股数变化', qoqWeightChange: '季比权重变化（百分点）',
    minimumWeight: '最低组合权重（%）', minimumChange: '最低股数变化（%）', guru: '投资大师', symbol: '代码',
    periodEnd: '申报期间', sectorAllocation: '行业配置', dataPartial: '本季度资料不完整。资料就绪前会隐藏持仓指标与动作。',
    statusLabel: (value: string) => value === 'READY' ? '数据就绪' : value === 'PARTIAL' ? '资料不完整' : value === 'ERROR' ? '数据错误' : '等待处理',
  },
} satisfies Record<Locale, Record<string, string | ((value: string) => string)>>

export function guruResearchCopy(locale: Locale) {
  return copy[locale]
}
