import type { Locale } from './destinations'

const copy = {
  en: {
    directory: 'Guru directory', consensus: 'Consensus', stocks: 'Stocks', sectors: 'Sectors', compare: 'Compare Gurus',
    consensusTitle: 'Guru consensus', stocksTitle: 'Most-owned stocks', sectorsTitle: 'Sector direction',
    consensusIntro: 'See where tracked investors overlap, and which positions they are adding or reducing.',
    stocksIntro: 'Rank securities by Guru ownership breadth, reported actions, and aggregate portfolio weight.',
    sectorsIntro: 'Compare buyers, sellers, and portfolio allocation across sectors, industries, and mapped themes.',
    warning: '13F holdings are delayed quarter-end disclosures and may not represent the manager’s current or complete portfolio.',
    quarter: 'Reported quarter', source: 'Source', reportedPeriod: 'Reported period',
    active: 'Tracked Gurus', ready: 'Ready portfolios', quarterCoverage: 'Quarter coverage', mappingCoverage: 'Mapping coverage',
    partial: 'Partial', errors: 'Errors', pending: 'Pending', noFiling: 'No filing', comparable: 'Comparable managers',
    search: 'Search ticker or company', sector: 'Sector', all: 'All', classification: 'Direction',
    accumulation: 'Accumulation', neutral: 'Neutral', distribution: 'Distribution',
    sort: 'Rank by', ranking: 'Rank by', dimension: 'Group by', industry: 'Industry', theme: 'Theme',
    sortDirection: 'Sort by', buyers: 'Most buyers', weightChange: 'Weight change', aggregateWeight: 'Aggregate weight', holders: 'Most holders',
    netBuyers: 'Net buyers', mostHeld: 'Most held', mostAdded: 'Most added', mostReduced: 'Most reduced',
    mostNew: 'Most new positions', mostExited: 'Most exits', largestWeight: 'Largest aggregate weight',
    fastestRising: 'Fastest rising interest', fastestFalling: 'Fastest falling interest',
    stock: 'Stock', company: 'Company', heldBy: 'Held by', new: 'New', add: 'Add', unchanged: 'Unchanged', reduce: 'Reduce', exit: 'Exit',
    net: 'Net buyers', averageChange: 'Average share change', medianChange: 'Median share change',
    averageWeight: 'Average portfolio weight', breadth: 'Ownership breadth', trend: 'Quarter trend',
    rising: 'Increasing', stable: 'Stable', falling: 'Decreasing', unavailable: 'Not comparable',
    group: 'Sector / group', direction: 'Direction', sellers: 'Sellers', actionCounts: 'New · Add · Reduce · Exit',
    allocatedWeight: 'Aggregate weight', comparableChange: 'Comparable weight change', allocationCoverage: 'Allocation coverage',
    loading: 'Loading prepared Guru data…', failed: 'Guru intelligence could not be loaded.', retry: 'Try again',
    empty: 'No prepared data is available for this quarter.', noMatches: 'No rows match these filters.',
    export: 'Export CSV', resultCount: (count: number) => `${count.toLocaleString()} results`,
    previous: 'Previous', next: 'Next', page: (page: number, pages: number) => `Page ${page} of ${pages}`,
    noClassification: 'No comparable action data',
  },
  'zh-TW': {
    directory: '大師名錄', consensus: '共識', stocks: '個股排行', sectors: '板塊方向', compare: '比較大師',
    consensusTitle: '大師持倉共識', stocksTitle: '大師最常持有的股票', sectorsTitle: '板塊資金方向',
    consensusIntro: '查看追蹤投資者的共同持倉，以及最近增持或減持的股票。',
    stocksIntro: '按持有大師數、申報動作及合計持倉權重排列證券。',
    sectorsIntro: '比較各板塊、行業與已映射主題的大師買賣動作及持倉配置。',
    warning: '13F 是延遲披露的季度末持倉，未必代表管理人目前或完整的投資組合。',
    quarter: '申報季度', source: '來源', reportedPeriod: '申報期間',
    active: '追蹤大師', ready: '可用組合', quarterCoverage: '季度涵蓋率', mappingCoverage: '映射涵蓋率',
    partial: '部分資料', errors: '錯誤', pending: '處理中', noFiling: '未有申報', comparable: '可比較的大師',
    search: '搜尋代號或公司', sector: '板塊', all: '全部', classification: '方向分類',
    accumulation: '累積買入', neutral: '中性', distribution: '累積賣出',
    sort: '排列方式', ranking: '排行榜', dimension: '分組方式', industry: '行業', theme: '主題',
    sortDirection: '排序依據', buyers: '買方數量', weightChange: '權重變化', aggregateWeight: '合計權重', holders: '持有大師數',
    netBuyers: '淨買方', mostHeld: '最多大師持有', mostAdded: '最多增持', mostReduced: '最多減持',
    mostNew: '最多新建倉', mostExited: '最多退出', largestWeight: '合計權重最高',
    fastestRising: '大師關注升幅最快', fastestFalling: '大師關注跌幅最快',
    stock: '股票', company: '公司', heldBy: '持有大師', new: '新建倉', add: '增持', unchanged: '不變', reduce: '減持', exit: '退出',
    net: '淨買方', averageChange: '平均股數變化', medianChange: '股數變化中位數',
    averageWeight: '平均組合權重', breadth: '持有廣度', trend: '季度趨勢',
    rising: '增加中', stable: '穩定', falling: '減少中', unavailable: '無法比較',
    group: '板塊／分類', direction: '方向', sellers: '賣方', actionCounts: '新建倉 · 增持 · 減持 · 退出',
    allocatedWeight: '合計權重', comparableChange: '可比較權重變化', allocationCoverage: '配置涵蓋率',
    loading: '正在載入預先計算的大師資料…', failed: '無法載入大師機構持倉資料。', retry: '重試',
    empty: '此季度暫無已整理資料。', noMatches: '沒有符合篩選條件的資料。',
    export: '匯出 CSV', resultCount: (count: number) => `${count.toLocaleString()} 項結果`,
    previous: '上一頁', next: '下一頁', page: (page: number, pages: number) => `第 ${page} / ${pages} 頁`,
    noClassification: '沒有可比較的動作資料',
  },
  'zh-CN': {
    directory: '大师名录', consensus: '共识', stocks: '个股排行', sectors: '板块方向', compare: '比较大师',
    consensusTitle: '大师持仓共识', stocksTitle: '大师最常持有的股票', sectorsTitle: '板块资金方向',
    consensusIntro: '查看追踪投资者的共同持仓，以及最近增持或减持的股票。',
    stocksIntro: '按持有大师数、申报动作及合计持仓权重排列证券。',
    sectorsIntro: '比较各板块、行业与已映射主题的大师买卖动作及持仓配置。',
    warning: '13F 是延迟披露的季度末持仓，未必代表管理人目前或完整的投资组合。',
    quarter: '申报季度', source: '来源', reportedPeriod: '申报期间',
    active: '追踪大师', ready: '可用组合', quarterCoverage: '季度覆盖率', mappingCoverage: '映射覆盖率',
    partial: '部分数据', errors: '错误', pending: '处理中', noFiling: '未有申报', comparable: '可比较的大师',
    search: '搜索代码或公司', sector: '板块', all: '全部', classification: '方向分类',
    accumulation: '累积买入', neutral: '中性', distribution: '累积卖出',
    sort: '排列方式', ranking: '排行榜', dimension: '分组方式', industry: '行业', theme: '主题',
    sortDirection: '排序依据', buyers: '买方数量', weightChange: '权重变化', aggregateWeight: '合计权重', holders: '持有大师数',
    netBuyers: '净买方', mostHeld: '最多大师持有', mostAdded: '最多增持', mostReduced: '最多减持',
    mostNew: '最多新建仓', mostExited: '最多退出', largestWeight: '合计权重最高',
    fastestRising: '大师关注升幅最快', fastestFalling: '大师关注跌幅最快',
    stock: '股票', company: '公司', heldBy: '持有大师', new: '新建仓', add: '增持', unchanged: '不变', reduce: '减持', exit: '退出',
    net: '净买方', averageChange: '平均股数变化', medianChange: '股数变化中位数',
    averageWeight: '平均组合权重', breadth: '持有广度', trend: '季度趋势',
    rising: '增加中', stable: '稳定', falling: '减少中', unavailable: '无法比较',
    group: '板块／分类', direction: '方向', sellers: '卖方', actionCounts: '新建仓 · 增持 · 减持 · 退出',
    allocatedWeight: '合计权重', comparableChange: '可比较权重变化', allocationCoverage: '配置覆盖率',
    loading: '正在加载预先计算的大师数据…', failed: '无法加载大师机构持仓数据。', retry: '重试',
    empty: '此季度暂无已整理数据。', noMatches: '没有符合筛选条件的数据。',
    export: '导出 CSV', resultCount: (count: number) => `${count.toLocaleString()} 项结果`,
    previous: '上一页', next: '下一页', page: (page: number, pages: number) => `第 ${page} / ${pages} 页`,
    noClassification: '没有可比较的动作数据',
  },
} as const

export function guruIntelligenceCopy(locale: Locale) { return copy[locale] }
