import { useEffect, useState } from 'react';
import { portfolioExposureResponseSchema, type PortfolioExposureResponse } from '@diary/contracts/portfolio-exposure';
import { api, useUi } from './ui';
import { apiFailure, FailureNotice, type Failure } from './api-error';
import { localizeAllocationMode, localizeMarketState, localizePolicyExplanation, localizePolicyWarning } from './market-policy-copy';
import './portfolio-exposure.css';
const copy = {
  en: { title: 'Portfolio exposure', basis: 'Percentages use the full cost basis, including positions without quotes. These categories are not measured beta values.', unknown: 'Unclassified positions need manual review.', missing: 'Market context is unavailable. Showing current exposure; target comparison is unavailable.', empty: 'No positions to classify.', warning: 'One classified category exceeds 50% of total cost.', highBetaPct: 'High-beta funds', coreIndexPct: 'Core index', megaCapPct: 'Mega-cap stocks', singleStockPct: 'Other classified stocks', defensivePct: 'Defensive assets', cashProxyPct: 'Cash proxies', unknownPct: 'Unclassified', skipped: 'Invalid cost records excluded', context: 'Market context comparison', state: 'Market state', mode: 'Allocation mode', snapshotDate: 'Rotation snapshot date', marketStateDate: 'Market-state date', summaryDate: 'Breadth summary date', explanation: 'Source explanation', comparison: 'Current versus target allocation', category: 'Category', current: 'Current', target: 'Target', difference: 'Difference (pp)', status: 'Status', highBeta: 'High beta', coreIndex: 'Core index', cash: 'Cash and defensive', unavailable: 'Target comparison is unavailable until a qualified market context is available.', riskOn: 'Risk-on', neutral: 'Neutral', defensive: 'Defensive', riskOff: 'Risk-off', unknownState: 'Unknown', aggressive: 'Aggressive', balanced: 'Balanced', capitalPreservation: 'Capital preservation', unknownMode: 'Unknown', underweight: 'Underweight', balancedStatus: 'Balanced', overweight: 'Overweight' },
  'zh-TW': { title: '投資組合曝險', basis: '比例按全部持倉成本計算，包括缺報價持倉。分類並非量測所得的 beta 值。', unknown: '未分類持倉需要自行檢視。', missing: '市場背景資料暫時不可用，現階段只顯示目前曝險，無法作目標比較。', empty: '尚無持倉可分類。', warning: '有一個已分類類別超過總成本的 50%。', highBetaPct: '高 beta 基金', coreIndexPct: '核心指數', megaCapPct: '大型股', singleStockPct: '其他已分類個股', defensivePct: '防禦資產', cashProxyPct: '現金替代資產', unknownPct: '未分類', skipped: '已排除無效成本記錄', context: '市場背景比較', state: '市場狀態', mode: '配置模式', snapshotDate: '輪動快照日期', marketStateDate: '市場狀態日期', summaryDate: '市場廣度摘要日期', explanation: '來源說明', comparison: '目前與目標配置比較', category: '類別', current: '目前', target: '目標', difference: '差距（百分點）', status: '狀態', highBeta: '高 beta', coreIndex: '核心指數', cash: '現金及防禦資產', unavailable: '尚無合格市場背景，暫時無法作目標比較。', riskOn: '風險偏好', neutral: '中性', defensive: '防禦', riskOff: '風險規避', unknownState: '未知', aggressive: '積極', balanced: '平衡', capitalPreservation: '資本保全', unknownMode: '未知', underweight: '低於目標', balancedStatus: '符合目標', overweight: '高於目標' },
  'zh-CN': { title: '投资组合敞口', basis: '比例按全部持仓成本计算，包括缺报价持仓。分类并非测量所得的 beta 值。', unknown: '未分类持仓需要自行检查。', missing: '市场背景数据暂时不可用，现阶段只显示当前敞口，无法进行目标比较。', empty: '尚无持仓可分类。', warning: '有一个已分类类别超过总成本的 50%。', highBetaPct: '高 beta 基金', coreIndexPct: '核心指数', megaCapPct: '大型股', singleStockPct: '其他已分类个股', defensivePct: '防御资产', cashProxyPct: '现金替代资产', unknownPct: '未分类', skipped: '已排除无效成本记录', context: '市场背景比较', state: '市场状态', mode: '配置模式', snapshotDate: '轮动快照日期', marketStateDate: '市场状态日期', summaryDate: '市场广度摘要日期', explanation: '来源说明', comparison: '当前与目标配置比较', category: '类别', current: '当前', target: '目标', difference: '差距（百分点）', status: '状态', highBeta: '高 beta', coreIndex: '核心指数', cash: '现金及防御资产', unavailable: '尚无合格市场背景，暂时无法进行目标比较。', riskOn: '风险偏好', neutral: '中性', defensive: '防御', riskOff: '风险规避', unknownState: '未知', aggressive: '积极', balanced: '平衡', capitalPreservation: '资本保全', unknownMode: '未知', underweight: '低于目标', balancedStatus: '符合目标', overweight: '高于目标' },
};
const buckets = ['highBetaPct', 'coreIndexPct', 'megaCapPct', 'singleStockPct', 'defensivePct', 'cashProxyPct', 'unknownPct'] as const;
export function PortfolioExposure() {
  const { locale, t } = useUi(), c = copy[locale];
  const [data, setData] = useState<PortfolioExposureResponse | null>(null), [error, setError] = useState<Failure | null>(null), [attempt, retry] = useState(0);
  useEffect(() => {
    const controller = new AbortController(); setData(null); setError(null);
    api.GET('/api/stocks/exposure', { signal: controller.signal }).then(result => {
      if (controller.signal.aborted) return;
      const parsed = portfolioExposureResponseSchema.safeParse(result.data);
      if (result.response.ok && parsed.success) setData(parsed.data); else setError(apiFailure(result.error, t('failed')));
    }).catch(() => { if (!controller.signal.aborted) setError(apiFailure(null, t('connection'))); });
    return () => controller.abort();
  }, [attempt]);
  const number = (value: number) => new Intl.NumberFormat(locale, { maximumFractionDigits: 1 }).format(value);
  const signed = (value: number) => `${new Intl.NumberFormat(locale, { maximumFractionDigits: 1, signDisplay: 'always' }).format(value)} pp`;
  const stateLabel = localizeMarketState(data?.marketState ?? 'unknown', locale);
  const modeLabel = localizeAllocationMode(data?.betaAllocation.suggestedMode ?? 'unknown', locale);
  const gapLabels = { highBeta: c.highBeta, coreIndex: c.coreIndex, cash: c.cash };
  const gapStatuses = { underweight: c.underweight, balanced: c.balancedStatus, overweight: c.overweight };
  const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeZone: 'UTC' }).format(new Date(value.includes('T') ? value : `${value}T00:00:00Z`)) : c.unknownState;
  const observed = formatDate(data?.lastUpdated ?? null), marketStateDate = formatDate(data?.marketStateAsOfDate ?? null), summaryDate = formatDate(data?.summaryAsOfDate ?? null);
  return <section className="portfolio-exposure" aria-label={c.title}><h2>{c.title}</h2>{error ? <><FailureNotice failure={error} id="exposure-error"/><button onClick={() => retry(value => value + 1)}>{t('retry')}</button></> : !data ? <p role="status">{t('loading')}</p> : data.exposure.totalValue === 0 ? <p>{c.empty}</p> : <><p>{c.basis}</p><dl>{buckets.map(bucket => <div key={bucket}><dt>{c[bucket]}</dt><dd data-testid={`exposure-${bucket}`}>{number(data.exposure[bucket])}%</dd><meter min={0} max={100} value={data.exposure[bucket]} aria-label={c[bucket]}/></div>)}</dl>{data.exposure.concentrationWarning && <p role="status">{c.warning}</p>}{data.exposure.unknownPct > 0 && <p>{c.unknown}</p>}{data.exposure.skippedCount > 0 && <p>{c.skipped}: {data.exposure.skippedCount}</p>}<section className="portfolio-exposure-context" aria-labelledby="portfolio-exposure-context-title"><h3 id="portfolio-exposure-context-title">{c.context}</h3><dl className="portfolio-exposure-context-meta"><div><dt>{c.state}</dt><dd data-testid="exposure-market-state">{stateLabel}</dd></div><div><dt>{c.mode}</dt><dd data-testid="exposure-allocation-mode">{modeLabel}</dd></div><div><dt>{c.snapshotDate}</dt><dd data-testid="exposure-last-updated">{observed}</dd></div><div><dt>{c.marketStateDate}</dt><dd data-testid="exposure-market-state-date">{marketStateDate}</dd></div><div><dt>{c.summaryDate}</dt><dd data-testid="exposure-summary-date">{summaryDate}</dd></div></dl><p>{localizePolicyExplanation(data.betaAllocation.explanation, locale)}</p>{data.betaAllocation.warnings.length > 0 && <ul className="portfolio-exposure-policy-warnings">{data.betaAllocation.warnings.map(warning => <li key={warning}>{localizePolicyWarning(warning, locale)}</li>)}</ul>}{data.marketState === 'unknown' || data.gaps.length === 0 ? <p role="status" data-testid="exposure-comparison-unavailable">{c.unavailable}</p> : <div className="portfolio-exposure-table-scroll" tabIndex={0} role="region" aria-label={c.comparison}><table><caption>{c.comparison}</caption><thead><tr><th scope="col">{c.category}</th><th scope="col">{c.current}</th><th scope="col">{c.target}</th><th scope="col">{c.difference}</th><th scope="col">{c.status}</th></tr></thead><tbody>{data.gaps.map(gap => <tr key={gap.bucket}><th scope="row">{gapLabels[gap.bucket as keyof typeof gapLabels]}</th><td data-testid={`exposure-current-${gap.bucket}`}>{number(gap.currentPct)}%</td><td data-testid={`exposure-target-${gap.bucket}`}>{number(gap.targetPct)}%</td><td data-testid={`exposure-gap-${gap.bucket}`}>{signed(gap.gapPct)}</td><td data-testid={`exposure-status-${gap.bucket}`}>{gapStatuses[gap.status]}</td></tr>)}</tbody></table></div>}</section></>}</section>;
}
