export const priceAlertCopy = {
 en: {
  title: 'Price reminders', intro: 'Keep a price condition beside the decision it may change.', scope: 'Latest 100 reminders. Checked every five minutes using a fresh available quote.', symbol: 'Symbol', type: 'Condition', threshold: 'Threshold', priceThreshold: 'Price threshold', percentThreshold: 'Signed change (%)', period: 'Moving average period', direction: 'Direction', message: 'Reminder message', above: 'At or above', below: 'At or below', percent: 'Change percent', movingAverage: 'Moving average', movingAverageAbove: 'Price at or above {period}-session moving average', movingAverageBelow: 'Price at or below {period}-session moving average', priceUnit: 'Currency price', percentUnit: 'Percent from previous close', periodUnit: 'Completed-session period', percentHelp: 'Uses the current regular-market price versus the previous regular-session close. Positive and negative thresholds keep their sign; equality qualifies.', movingAverageHelp: 'Uses the simple average of completed regular-session closes. Equality qualifies; checks run every five minutes.', create: 'Create price reminder', edit: 'Edit', save: 'Save changes', cancel: 'Cancel', remove: 'Delete reminder', rearm: 'Monitor again', armed: 'Monitoring', triggered: 'Triggered', empty: 'No price reminders yet.', rearmHint: 'Changing a price or message keeps the trigger state. Choose Monitor again to rearm.', invalid: 'Enter a valid symbol and threshold. Prices and signed percentages allow up to six integer digits and four decimal places; moving averages use 20, 50 or 200.', success: 'Reminder saved.', deleted: 'Reminder deleted.', timezone: 'Times shown in', discard: 'Discard unsaved reminder changes?',
 },
 'zh-TW': {
  title: '價格提醒', intro: '記下可能改變決策的價格條件。', scope: '最近 100 筆提醒，每五分鐘以可取得的新報價檢查。', symbol: '股票代號', type: '條件', threshold: '門檻', priceThreshold: '價格門檻', percentThreshold: '帶正負號的漲跌幅（%）', period: '均線期間', direction: '方向', message: '提醒訊息', above: '達到或高於', below: '達到或低於', percent: '漲跌幅', movingAverage: '移動平均', movingAverageAbove: '價格達到或高於 {period} 日均線', movingAverageBelow: '價格達到或低於 {period} 日均線', priceUnit: '貨幣價格', percentUnit: '相對前一個正常交易日收盤價', periodUnit: '已完成交易日收盤', percentHelp: '以目前正常市場價格和前一個正常交易日收盤價比較；門檻保留正負號，相等時也會觸發。', movingAverageHelp: '以已完成正常交易日收盤價計算簡單平均；相等時也會觸發，每五分鐘檢查。', create: '建立價格提醒', edit: '編輯', save: '儲存修改', cancel: '取消', remove: '刪除提醒', rearm: '重新監測', armed: '監測中', triggered: '已觸發', empty: '目前沒有價格提醒。', rearmHint: '修改價格或訊息會保留觸發狀態。請選擇重新監測來再次啟用。', invalid: '請輸入有效代號及門檻。價格與帶正負號的漲跌幅最多六位整數及四位小數；均線使用 20、50 或 200。', success: '已儲存提醒。', deleted: '已刪除提醒。', timezone: '時間顯示時區', discard: '放棄未儲存的提醒修改？',
 },
 'zh-CN': {
  title: '价格提醒', intro: '记下可能改变决策的价格条件。', scope: '最近 100 条提醒，每五分钟以可取得的新报价检查。', symbol: '股票代码', type: '条件', threshold: '门槛', priceThreshold: '价格门槛', percentThreshold: '带正负号的涨跌幅（%）', period: '均线期间', direction: '方向', message: '提醒消息', above: '达到或高于', below: '达到或低于', percent: '涨跌幅', movingAverage: '移动平均', movingAverageAbove: '价格达到或高于 {period} 日均线', movingAverageBelow: '价格达到或低于 {period} 日均线', priceUnit: '货币价格', percentUnit: '相对前一个正常交易日收盘价', periodUnit: '已完成交易日收盘', percentHelp: '以当前正常市场价格和前一个正常交易日收盘价比较；门槛保留正负号，相等时也会触发。', movingAverageHelp: '以已完成正常交易日收盘价计算简单平均；相等时也会触发，每五分钟检查。', create: '创建价格提醒', edit: '编辑', save: '保存修改', cancel: '取消', remove: '删除提醒', rearm: '重新监测', armed: '监测中', triggered: '已触发', empty: '目前没有价格提醒。', rearmHint: '修改价格或消息会保留触发状态。请选择重新监测来再次启用。', invalid: '请输入有效代码及门槛。价格与带正负号的涨跌幅最多六位整数及四位小数；均线使用 20、50 或 200。', success: '已保存提醒。', deleted: '已删除提醒。', timezone: '时间显示时区', discard: '放弃未储存的提醒修改？',
 },
};
