import { useEffect,useState } from 'react';
import type { RecentClosedTrade } from '@diary/domain';
import { api,useUi } from './ui';
import { apiFailure,FailureNotice,type Failure } from './api-error';
const copy={en:{title:'Related trade review',hint:'Select from your latest 50 sales in the past 30 days.',empty:'No recent sales to select.',selected:'Selected',quantity:'Quantity',pnl:'Realized gain / loss',pct:'Return'},'zh-TW':{title:'相關交易回顧',hint:'從過去 30 天最近 50 筆賣出選擇。',empty:'暫時沒有可選的近期賣出。',selected:'已選取',quantity:'數量',pnl:'已實現損益',pct:'回報率'},'zh-CN':{title:'相关交易回顾',hint:'从过去 30 天最近 50 笔卖出选择。',empty:'暂时没有可选的近期卖出。',selected:'已选取',quantity:'数量',pnl:'已实现损益',pct:'回报率'}};
export function QuickRelatedTrades({value,onChange}:{value:RecentClosedTrade[];onChange:(trades:RecentClosedTrade[])=>void}){const {locale,t}=useUi();const l=copy[locale];const [trades,setTrades]=useState<RecentClosedTrade[]|null>(null),[error,setError]=useState<Failure|null>(null),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;setTrades(null);setError(null);api.GET('/api/stats/recent-trades').then(result=>{if(!active)return;if(result.response.ok&&result.data)setTrades(result.data.trades);else setError(apiFailure(result.error,t('failed')));}).catch(()=>{if(active)setError(apiFailure(null,t('connection')));});return()=>{active=false;};},[attempt]);
 const options=[...new Map([...(trades??[]),...value].map(trade=>[trade.id,trade])).values()];
 return <section className="quick-related-trades" aria-label={l.title}><h3>{l.title}</h3><p className="muted">{l.hint}</p><p role="status">{l.selected}: {value.length}</p>{error?<><FailureNotice failure={error} id="quick-trades-error"/><button type="button" className="secondary" onClick={()=>setAttempt(attempt+1)}>{t('retry')}</button></>:trades===null?<p role="status">{t('loading')}</p>:!options.length?<p>{l.empty}</p>:null}{options.map(trade=><label className="related-trade-option" key={trade.id}><input type="checkbox" checked={value.some(item=>item.id===trade.id)} onChange={event=>onChange(event.target.checked?[...value.filter(item=>item.id!==trade.id),trade]:value.filter(item=>item.id!==trade.id))}/><span><strong>{trade.symbol}</strong> · {trade.sellDate.slice(0,10)}<span>{l.quantity}: {trade.sellQuantity}</span><span>{l.pnl}: {trade.realizedPnL} · {l.pct}: {trade.realizedPnLPct}%</span></span></label>)}</section>;
}
