import { useEffect,useRef,useState } from 'react';
import { useUi } from './ui';
type Recognition={lang:string;continuous:boolean;interimResults:boolean;onresult:((event:{resultIndex:number;results:{length:number;[index:number]:{isFinal:boolean;0:{transcript:string}}}})=>void)|null;onerror:((event:{error:string})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void;abort:()=>void};
type SpeechWindow=Window&{SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};
export function VoiceCapture({append}:{append:(text:string)=>void}){const {locale}=useUi(),index=locale==='en'?0:locale==='zh-TW'?1:2,c={start:['Start voice input','開始語音輸入','开始语音输入'],stop:['Stop voice input','停止語音輸入','停止语音输入'],unsupported:['Voice input is unavailable in this browser. You can keep typing.','此瀏覽器不支援語音輸入，仍可繼續打字。','此浏览器不支持语音输入，仍可继续打字。'],error:['Microphone input failed or permission was denied. Check browser permission and retry, or keep typing.','無法使用麥克風或權限被拒絕。請檢查瀏覽器權限後重試，或繼續打字。','无法使用麦克风或权限被拒绝。请检查浏览器权限后重试，或继续打字。']};const [supported,setSupported]=useState(false),[listening,setListening]=useState(false),[failed,setFailed]=useState(false),ref=useRef<Recognition|null>(null),appendRef=useRef(append);appendRef.current=append;
 useEffect(()=>{const w=window as SpeechWindow;setSupported(!!(w.SpeechRecognition||w.webkitSpeechRecognition));return()=>{ref.current?.abort();};},[]);
 function start(){const w=window as SpeechWindow,Constructor=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Constructor)return;setFailed(false);const r=new Constructor();ref.current=r;r.lang=locale;r.continuous=true;r.interimResults=true;r.onresult=event=>{for(let i=event.resultIndex;i<event.results.length;i++){const result=event.results[i];if(result?.isFinal&&result[0].transcript.trim())appendRef.current(result[0].transcript.trim());}};r.onerror=()=>{setFailed(true);setListening(false);};r.onend=()=>setListening(false);try{r.start();setListening(true);}catch{setFailed(true);}}
 return <div className="quick-voice">{supported?<button type="button" className="secondary" onClick={()=>listening?ref.current?.stop():start()}>{c[listening?'stop':'start'][index]}</button>:<p className="muted">{c.unsupported[index]}</p>}{failed&&<p className="error" role="alert">{c.error[index]}</p>}</div>;
}
export function CaptureReminder({accountId}:{accountId:string}){const {locale}=useUi(),i=locale==='en'?0:locale==='zh-TW'?1:2,key=`diary-quick-reminder:${accountId}`,c={title:['Capture reminder','記錄提醒','记录提醒'],tomorrow:['Tomorrow','明天','明天'],week:['Next week','下週','下周'],month:['Next month','下月','下月'],custom:['Custom reminder time','自訂提醒時間','自定义提醒时间'],set:['Set reminder','設定提醒','设置提醒'],clear:['Clear reminder','清除提醒','清除提醒'],due:['Time to record a quick diary.','是時候記下快速日記了。','是时候记下快速日记了。'],error:['Unable to save this reminder on the device.','無法在此裝置儲存提醒。','无法在此设备保存提醒。']};const [time,setTime]=useState<string|null>(()=>{try{const value=localStorage.getItem(key);return value&&Number.isFinite(Date.parse(value))?value:null;}catch{return null;}}),[custom,setCustom]=useState(''),[due,setDue]=useState(false),[error,setError]=useState(false);
 function save(value:string|null){setTime(value);setDue(false);try{if(value)localStorage.setItem(key,value);else localStorage.removeItem(key);setError(false);}catch{setError(true);}}
 useEffect(()=>{function check(){if(time&&Date.parse(time)<=Date.now()){setDue(true);setTime(null);try{localStorage.removeItem(key);}catch{setError(true);}}}check();const timer=setInterval(check,30000);const clear=()=>{setTime(null);setDue(false);};window.addEventListener('diary-quick-saved',clear);return()=>{clearInterval(timer);window.removeEventListener('diary-quick-saved',clear);};},[time,key]);
 function preset(days:number,month=false){const target=new Date();if(month)target.setMonth(target.getMonth()+1);else target.setDate(target.getDate()+days);save(target.toISOString());}
 return <details><summary>{c.title[i]}</summary><div className="actions"><button type="button" className="secondary" onClick={()=>preset(1)}>{c.tomorrow[i]}</button><button type="button" className="secondary" onClick={()=>preset(7)}>{c.week[i]}</button><button type="button" className="secondary" onClick={()=>preset(0,true)}>{c.month[i]}</button></div><label>{c.custom[i]}<input type="datetime-local" value={custom} onChange={event=>setCustom(event.target.value)}/></label><div className="actions"><button type="button" disabled={!custom||!Number.isFinite(Date.parse(custom))} onClick={()=>save(new Date(custom).toISOString())}>{c.set[i]}</button>{time&&<button type="button" className="secondary" onClick={()=>save(null)}>{c.clear[i]}</button>}</div>{time&&<p role="status">{new Date(time).toLocaleString(locale)}</p>}{due&&<p role="status">{c.due[i]}</p>}{error&&<p role="alert" className="error">{c.error[i]}</p>}</details>;
}
