export type Locale = 'zh-TW' | 'zh-CN' | 'en'

export type ResearchCopy = typeof copy.en

const copy = {
  en: {
    title: 'Research Studio',
    intro: 'Prepare evidence first, then move a reviewed research draft through its own checkpoints.',
    newRun: 'New research run',
    settings: 'Research settings',
    refresh: 'Refresh',
    retry: 'Try again',
    loading: 'Loading research runs…',
    failed: 'Research Studio is temporarily unavailable.',
    connection: 'The research service could not be reached. Your saved work is preserved.',
    denied: 'You do not have permission to manage research.',
    empty: 'No research runs yet.',
    emptyHint: 'Prepare a supported instrument to validate its evidence before generation becomes available.',
    prepareFirst: 'Prepare the first run',
    filters: 'Filter runs',
    instrument: 'Instrument',
    status: 'Execution status',
    quality: 'Quality',
    review: 'Review',
    all: 'All',
    clear: 'Clear filters',
    referenceSession: 'Reference session',
    lastChanged: 'Last changed',
    open: 'Open run',
    method: 'Method',
    profile: 'Research profile',
    supported: 'US Equity Swing Research · v1.0.0',
    symbol: 'Instrument symbol',
    symbolHint: 'Use an enabled US equity or ETF symbol. SOXX is the first acceptance fixture.',
    timezone: 'Display timezone',
    asOf: 'As of',
    asOfHint: 'Leave blank to use the server clock and latest available completed session.',
    synthetic: 'Use controlled synthetic evidence',
    syntheticHint: 'Keeps browser and QA checks offline. It does not claim a live market source.',
    prepare: 'Prepare evidence',
    preparing: 'Preparing…',
    preparation: 'Preparation',
    identity: 'Instrument identity',
    benchmarks: 'Benchmarks',
    peers: 'Peers',
    coverage: 'Coverage',
    rows: 'Rows',
    completeOhlc: 'Complete OHLC rows',
    closeRows: 'Close rows',
    volumeRows: 'Volume rows',
    missing: 'Missing sessions',
    warnings: 'Warnings',
    noWarnings: 'No warnings recorded.',
    blocked: 'Blocked',
    blockedHint: 'This dependency is not ready. Resolve the reason before continuing.',
    unavailable: 'Unavailable',
    incompleteMethod: 'The method bundle is traceable but incomplete. Generation is blocked until the calculator and appendices are verified.',
    sourceUnavailable: 'No approved live source is connected for this run. Synthetic evidence is clearly labelled and cannot be promoted to FULL.',
    cancel: 'Cancel',
    detail: 'Research run',
    reportDate: 'Report date',
    execution: 'Execution',
    dispatch: 'Dispatch',
    currentRevision: 'Current revision',
    linkedArticle: 'Linked article',
    noArticle: 'No article draft yet',
    preview: 'Preview',
    evidence: 'Evidence',
    qa: 'QA',
    activity: 'Activity / usage',
    reportPreview: 'Report preview',
    noDraft: 'There is no report draft to preview yet.',
    generate: 'Generate draft',
    regenerate: 'Generate new revision',
    generating: 'Generating…',
    revise: 'Revise draft',
    saveRevision: 'Save revision',
    saving: 'Saving…',
    approve: 'Approve exact revision',
    approving: 'Approving…',
    handoff: 'Create article draft',
    handingOff: 'Creating article…',
    nextAction: 'Next action',
    limitations: 'Limitations',
    noLimitations: 'No additional limitations recorded.',
    revisionEditor: 'Markdown revision',
    revisionHint: 'Saving creates a new immutable revision. Approval applies to this exact body hash.',
    markdownPreview: 'Markdown preview',
    showPreview: 'Show preview',
    showEditor: 'Show editor',
    access: 'Article access',
    member: 'Members only',
    public: 'Public',
    category: 'Category',
    tags: 'Tags',
    articleTitle: 'Article title (optional)',
    handoffHint: 'Handoff creates an unpublished article draft. Publication remains a separate admin action.',
    source: 'Source',
    retrieved: 'Retrieved',
    dataAsOf: 'Data as of',
    sourceRights: 'Source use',
    readSource: 'Open source',
    noEvidence: 'Evidence has not been prepared yet.',
    gate: 'Gate',
    severity: 'Severity',
    gateStatus: 'Status',
    reason: 'Reason',
    remediation: 'Next step',
    reviewer: 'Reviewer',
    noQa: 'QA has not been recorded yet.',
    qaReviewTitle: 'Human QA review',
    qaReviewHint: 'Review G07–G10 against this exact immutable revision. Saving creates a new QA revision; the server records your identity and review time. G07/G08 may be not applicable only when there are no applicable plan or event claims and you record a limitation.',
    qaGateG07: 'Trade plans and reward/risk',
    qaGateG08: 'Events and calendar claims',
    qaGateG09: 'Citation support',
    qaGateG10: 'Cross-section consistency',
    qaReviewStatus: 'Review result',
    qaReviewEvidence: 'Evidence note',
    qaReviewReason: 'Reason or limitation',
    qaReviewRemediation: 'Next step',
    qaReviewChoose: 'Choose a result',
    qaReviewIncomplete: 'Choose a result and provide an evidence note for G07–G10. Not applicable also requires a limitation; a failure requires a reason. Save report edits as a revision before reviewing QA.',
    qaReviewSaved: 'QA review saved as a new immutable revision.',
    qaReviewCurrent: 'These controls apply to the latest saved report revision. Save Markdown or structured edits before reviewing QA.',
    saveQaReview: 'Save QA review revision',
    attempt: 'Attempt',
    model: 'Model',
    usage: 'Usage',
    reserved: 'Reserved cost',
    diagnostics: 'Diagnostics',
    noAttempts: 'No generation attempts yet.',
    runtime: 'Runtime',
    featureSwitch: 'Research Studio enabled',
    generationSwitch: 'Generation enabled',
    worker: 'Worker',
    workerAvailable: 'Available',
    workerUnavailable: 'Unavailable',
    provider: 'Writer provider',
    providerHint: 'Research uses a purpose-scoped OpenRouter route. Tests are limited to openrouter/free.',
    baseUrl: 'Base URL',
    modelFixed: 'Model',
    inputLimit: 'Input token limit',
    outputLimit: 'Output token limit',
    timeout: 'Timeout (ms)',
    secret: 'Credential',
    secretPresent: 'Configured · masked',
    secretMissing: 'Not configured',
    saveSettings: 'Save settings',
    savingSettings: 'Saving…',
    settingsSaved: 'Research settings saved.',
    budget: 'Budget',
    budgetUnknown: 'Unknown outcome reservations remain counted.',
    settingsUnavailable: 'Research settings are temporarily unavailable.',
    stale: 'Stale',
    limited: 'Limited',
    full: 'Full',
    failedStatus: 'Failed',
    draft: 'Draft',
    changesRequired: 'Changes required',
    approved: 'Approved',
    created: 'Created',
    collecting: 'Collecting',
    dataReady: 'Data ready',
    generatingStatus: 'Generating',
    draftReady: 'Draft ready',
    blockedStatus: 'Blocked',
    cancelled: 'Cancelled',
    notSent: 'Not sent',
    dispatchIntent: 'Dispatch intent',
    sent: 'Sent',
    succeeded: 'Succeeded',
    failedDispatch: 'Failed',
    unknownOutcome: 'Outcome unknown',
    pass: 'Pass',
    warn: 'Warn',
    fail: 'Fail',
    notChecked: 'Not checked',
    notApplicable: 'Not applicable',
    conflict: 'This run changed elsewhere. Refresh to load the current version before trying again.',
    actionFailed: 'The action could not be completed. Refresh and try again.',
    refreshed: 'Saved state refreshed.',
    prepareComplete: 'Evidence preparation finished.',
    revisionSaved: 'Revision saved.',
    approvedNotice: 'The exact revision is approved.',
    handoffComplete: 'An article draft was created.',
    back: 'Back to Research Studio',
    signIn: 'Sign in',
    openArticle: 'Open article draft',
    requestId: 'Request ID',
  },
  'zh-TW': {
    title: '研究工作室',
    intro: '先準備證據，再讓已檢閱的研究草稿逐步通過各個檢查點。',
    newRun: '新增研究執行', settings: '研究設定', refresh: '重新整理', retry: '重試', loading: '正在載入研究執行…', failed: '研究工作室暫時無法使用。', connection: '無法連線到研究服務，已儲存的工作仍然保留。', denied: '你沒有管理研究的權限。', empty: '尚未有研究執行。', emptyHint: '先為支援的標的準備證據，驗證後才會提供生成。', prepareFirst: '準備第一個執行', filters: '篩選執行', instrument: '標的', status: '執行狀態', quality: '品質', review: '檢閱', all: '全部', clear: '清除篩選', referenceSession: '參考交易日', lastChanged: '最近變更', open: '開啟執行', method: '方法', profile: '研究設定檔', supported: '美股波段研究 · v1.0.0', symbol: '標的代號', symbolHint: '使用已啟用的美股或 ETF 代號。SOXX 是第一個驗收 fixture。', timezone: '顯示時區', asOf: '資料截至', asOfHint: '留空會使用伺服器時間及最近完成的交易日。', synthetic: '使用受控合成證據', syntheticHint: '讓瀏覽器及 QA 檢查保持離線，不代表已連接即時市場來源。', prepare: '準備證據', preparing: '準備中…', preparation: '準備結果', identity: '標的身份', benchmarks: '基準', peers: '同業', coverage: '覆蓋情況', rows: '資料列', completeOhlc: '完整 OHLC 資料列', closeRows: '收市價資料列', volumeRows: '成交量資料列', missing: '缺少交易日', warnings: '警告', noWarnings: '沒有記錄警告。', blocked: '已阻擋', blockedHint: '這項依賴尚未準備好，請先處理原因。', unavailable: '無法使用', incompleteMethod: '方法束可追溯但尚未完整。計算器及附冊驗證前會阻擋生成。', sourceUnavailable: '這次執行沒有已批准的即時來源。合成證據會清楚標示，也不能升級為 FULL。', cancel: '取消', detail: '研究執行', reportDate: '報告日期', execution: '執行', dispatch: '派送', currentRevision: '目前版本', linkedArticle: '已連結文章', noArticle: '尚未有文章草稿', preview: '預覽', evidence: '證據', qa: 'QA', activity: '活動／用量', reportPreview: '報告預覽', noDraft: '尚未有可預覽的報告草稿。', generate: '生成草稿', regenerate: '生成新版本', generating: '生成中…', revise: '修訂草稿', saveRevision: '儲存修訂', saving: '儲存中…', revisionEditor: 'Markdown 修訂', revisionHint: '儲存會建立不可變更的新版本，批准只套用於這個 body hash。', markdownPreview: 'Markdown 預覽', showPreview: '顯示預覽', showEditor: '顯示編輯器', access: '文章存取', member: '僅限會員', public: '公開', category: '分類', tags: '標籤', articleTitle: '文章標題（選填）', handoffHint: '交接會建立未發佈的文章草稿，發佈仍是獨立的管理操作。', source: '來源', retrieved: '取得時間', dataAsOf: '資料截至', sourceRights: '來源用途', readSource: '開啟來源', noEvidence: '尚未準備證據。', gate: '檢查門', severity: '嚴重性', gateStatus: '狀態', reason: '原因', remediation: '下一步', reviewer: '檢閱者', noQa: '尚未記錄 QA。', qaReviewTitle: '人工 QA 審核', qaReviewHint: '請針對目前這個不可變修訂檢閱 G07–G10。儲存會建立新的 QA 修訂；伺服器會記錄你的身分與時間。只有在沒有適用的計劃或事件主張且寫明限制時，G07/G08 才可標示不適用。', qaGateG07: '交易計劃與風險報酬', qaGateG08: '事件與行事曆主張', qaGateG09: '引用支持度', qaGateG10: '跨章節一致性', qaReviewStatus: '檢閱結果', qaReviewEvidence: '證據註記', qaReviewReason: '原因或限制', qaReviewRemediation: '下一步', qaReviewChoose: '選擇結果', qaReviewIncomplete: '請為 G07–G10 選擇結果並提供證據註記。不適用也需要填寫限制；失敗需要填寫原因。檢閱 QA 前，請先將報告修改儲存為修訂。', qaReviewSaved: 'QA 檢閱已儲存為新的不可變修訂。', qaReviewCurrent: '這些欄位套用於最新已儲存的報告修訂。請先儲存 Markdown 或結構化修改，再檢閱 QA。', saveQaReview: '儲存 QA 檢閱修訂', attempt: '嘗試', model: '模型', usage: '用量', reserved: '預留成本', diagnostics: '診斷', noAttempts: '尚未有生成嘗試。', runtime: '執行環境', featureSwitch: '啟用研究工作室', generationSwitch: '啟用生成', worker: 'Worker', workerAvailable: '可用', workerUnavailable: '無法使用', provider: '寫作供應商', providerHint: '研究使用獨立的 OpenRouter 路由，測試只允許 openrouter/free。', baseUrl: '基礎 URL', modelFixed: '模型', inputLimit: '輸入 token 上限', outputLimit: '輸出 token 上限', timeout: '逾時（毫秒）', secret: '憑證', secretPresent: '已設定・已遮罩', secretMissing: '尚未設定', saveSettings: '儲存設定', savingSettings: '儲存中…', settingsSaved: '研究設定已儲存。', budget: '預算', budgetUnknown: '未知結果的預留成本仍會計入。', settingsUnavailable: '研究設定暫時無法使用。', stale: '過期', limited: '有限', full: '完整', failedStatus: '失敗', draft: '草稿', changesRequired: '需要修改', approved: '已批准', created: '已建立', collecting: '收集中', dataReady: '資料就緒', generatingStatus: '生成中', draftReady: '草稿就緒', blockedStatus: '已阻擋', cancelled: '已取消', notSent: '尚未派送', dispatchIntent: '派送意圖', sent: '已派送', succeeded: '成功', failedDispatch: '失敗', unknownOutcome: '結果未知', pass: '通過', warn: '警告', fail: '失敗', notChecked: '尚未檢查', notApplicable: '不適用', conflict: '這個執行已在其他地方變更，請重新整理後載入目前版本。', actionFailed: '操作未完成，請重新整理後再試。', refreshed: '已重新載入儲存狀態。', prepareComplete: '證據準備完成。', revisionSaved: '修訂已儲存。', approvedNotice: '指定版本已批准。', handoffComplete: '已建立文章草稿。', back: '返回研究工作室', signIn: '登入', openArticle: '開啟文章草稿', requestId: '請求 ID',
  },
  'zh-CN': {
    title: '研究工作室', intro: '先准备证据，再让已审核的研究草稿逐步通过各个检查点。', newRun: '新增研究执行', settings: '研究设置', refresh: '刷新', retry: '重试', loading: '正在加载研究执行…', failed: '研究工作室暂时无法使用。', connection: '无法连接到研究服务，已保存的工作仍然保留。', denied: '你没有管理研究的权限。', empty: '尚无研究执行。', emptyHint: '先为支持的标的准备证据，验证后才会提供生成。', prepareFirst: '准备第一个执行', filters: '筛选执行', instrument: '标的', status: '执行状态', quality: '质量', review: '审核', all: '全部', clear: '清除筛选', referenceSession: '参考交易日', lastChanged: '最近更改', open: '打开执行', method: '方法', profile: '研究配置', supported: '美股波段研究 · v1.0.0', symbol: '标的代码', symbolHint: '使用已启用的美股或 ETF 代码。SOXX 是第一个验收 fixture。', timezone: '显示时区', asOf: '数据截至', asOfHint: '留空会使用服务器时间及最近完成的交易日。', synthetic: '使用受控合成证据', syntheticHint: '让浏览器及 QA 检查保持离线，不代表已连接实时市场来源。', prepare: '准备证据', preparing: '准备中…', preparation: '准备结果', identity: '标的身份', benchmarks: '基准', peers: '同业', coverage: '覆盖情况', rows: '数据行', completeOhlc: '完整 OHLC 数据行', closeRows: '收盘价数据行', volumeRows: '成交量数据行', missing: '缺少交易日', warnings: '警告', noWarnings: '没有记录警告。', blocked: '已阻挡', blockedHint: '这项依赖尚未准备好，请先处理原因。', unavailable: '无法使用', incompleteMethod: '方法包可追溯但尚未完整。计算器及附册验证前会阻挡生成。', sourceUnavailable: '这次执行没有已批准的实时来源。合成证据会清楚标记，也不能升级为 FULL。', cancel: '取消', detail: '研究执行', reportDate: '报告日期', execution: '执行', dispatch: '派送', currentRevision: '当前版本', linkedArticle: '已关联文章', noArticle: '尚无文章草稿', preview: '预览', evidence: '证据', qa: 'QA', activity: '活动／用量', reportPreview: '报告预览', noDraft: '尚无可预览的报告草稿。', generate: '生成草稿', regenerate: '生成新版本', generating: '生成中…', revise: '修改草稿', saveRevision: '保存修改', saving: '保存中…', revisionEditor: 'Markdown 修改', revisionHint: '保存会创建不可变更的新版本，批准只应用于这个 body hash。', markdownPreview: 'Markdown 预览', showPreview: '显示预览', showEditor: '显示编辑器', access: '文章访问', member: '仅限会员', public: '公开', category: '分类', tags: '标签', articleTitle: '文章标题（选填）', handoffHint: '交接会创建未发布的文章草稿，发布仍是独立的管理操作。', source: '来源', retrieved: '取得时间', dataAsOf: '数据截至', sourceRights: '来源用途', readSource: '打开来源', noEvidence: '尚未准备证据。', gate: '检查门', severity: '严重性', gateStatus: '状态', reason: '原因', remediation: '下一步', reviewer: '审核者', noQa: '尚未记录 QA。', qaReviewTitle: '人工 QA 审核', qaReviewHint: '请针对当前这个不可变修改审核 G07–G10。保存会创建新的 QA 修改；服务器会记录你的身份和时间。只有在没有适用的计划或事件主张且写明限制时，G07/G08 才可标记为不适用。', qaGateG07: '交易计划与风险回报', qaGateG08: '事件与日历主张', qaGateG09: '引用支持度', qaGateG10: '跨章节一致性', qaReviewStatus: '审核结果', qaReviewEvidence: '证据说明', qaReviewReason: '原因或限制', qaReviewRemediation: '下一步', qaReviewChoose: '选择结果', qaReviewIncomplete: '请为 G07–G10 选择结果并提供证据说明。不适用也需要填写限制；失败需要填写原因。审核 QA 前，请先将报告修改保存为修改。', qaReviewSaved: 'QA 审核已保存为新的不可变修改。', qaReviewCurrent: '这些字段应用于最新已保存的报告修改。请先保存 Markdown 或结构化修改，再审核 QA。', saveQaReview: '保存 QA 审核修改', attempt: '尝试', model: '模型', usage: '用量', reserved: '预留成本', diagnostics: '诊断', noAttempts: '尚无生成尝试。', runtime: '运行环境', featureSwitch: '启用研究工作室', generationSwitch: '启用生成', worker: 'Worker', workerAvailable: '可用', workerUnavailable: '无法使用', provider: '写作供应商', providerHint: '研究使用独立的 OpenRouter 路由，测试只允许 openrouter/free。', baseUrl: '基础 URL', modelFixed: '模型', inputLimit: '输入 token 上限', outputLimit: '输出 token 上限', timeout: '超时（毫秒）', secret: '凭证', secretPresent: '已设置・已遮罩', secretMissing: '尚未设置', saveSettings: '保存设置', savingSettings: '保存中…', settingsSaved: '研究设置已保存。', budget: '预算', budgetUnknown: '未知结果的预留成本仍会计入。', settingsUnavailable: '研究设置暂时无法使用。', stale: '过期', limited: '有限', full: '完整', failedStatus: '失败', draft: '草稿', changesRequired: '需要修改', approved: '已批准', created: '已创建', collecting: '收集中', dataReady: '数据就绪', generatingStatus: '生成中', draftReady: '草稿就绪', blockedStatus: '已阻挡', cancelled: '已取消', notSent: '尚未派送', dispatchIntent: '派送意图', sent: '已派送', succeeded: '成功', failedDispatch: '失败', unknownOutcome: '结果未知', pass: '通过', warn: '警告', fail: '失败', notChecked: '尚未检查', notApplicable: '不适用', conflict: '这个执行已在其他地方更改，请刷新后加载当前版本。', actionFailed: '操作未完成，请刷新后再试。', refreshed: '已刷新保存状态。', prepareComplete: '证据准备完成。', revisionSaved: '修改已保存。', approvedNotice: '指定版本已批准。', handoffComplete: '已创建文章草稿。', back: '返回研究工作室', signIn: '登录', openArticle: '打开文章草稿', requestId: '请求 ID',
  },
} as const

export function researchCopy(locale: Locale): ResearchCopy {
  return { ...copy.en, ...copy[locale] } as ResearchCopy
}

export function dateLocale(locale: Locale) {
  return locale === 'zh-TW' ? 'zh-TW' : locale === 'zh-CN' ? 'zh-CN' : 'en-US'
}

export function statusLabel(value: string, c: ResearchCopy) {
  const map: Record<string, keyof ResearchCopy> = {
    FULL: 'full', LIMITED: 'limited', STALE: 'stale', FAILED: 'failedStatus',
    DRAFT: 'draft', CHANGES_REQUIRED: 'changesRequired', APPROVED: 'approved',
    CREATED: 'created', COLLECTING: 'collecting', DATA_READY: 'dataReady', GENERATING: 'generatingStatus', DRAFT_READY: 'draftReady', BLOCKED: 'blockedStatus', CANCELLED: 'cancelled',
    NOT_SENT: 'notSent', DISPATCH_INTENT: 'dispatchIntent', SENT: 'sent', SUCCEEDED: 'succeeded', OUTCOME_UNKNOWN: 'unknownOutcome',
    PASS: 'pass', WARN: 'warn', FAIL: 'fail', NOT_CHECKED: 'notChecked', N_A: 'notApplicable',
  }
  const key = map[value]
  return key ? c[key] : value
}

export function formatDate(value: string | null | undefined, locale: Locale, withTime = false) {
  if (!value) return '—'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return new Intl.DateTimeFormat(dateLocale(locale), withTime ? { dateStyle: 'medium', timeStyle: 'short' } : { dateStyle: 'medium' }).format(date)
}

export function randomIdempotencyKey() {
  return `research-${crypto.randomUUID()}`
}

const configurationCopy = {
  en: {
    loadingProfiles: 'Loading supported profiles…',
    settingsSources: 'Source policies',
    sourceAvailability: 'Availability',
    sourceReadyLabel: 'Ready',
    sourceNotConfiguredLabel: 'Not configured',
    sourcePolicyUnknownLabel: 'Policy unknown',
    sourcePolicyRestrictedLabel: 'Policy restricted',
    sourceBudgetNotConfiguredLabel: 'Budget not configured',
    sourceReady: 'The source adapter is configured. Each operation still follows its own permission status below.',
    sourceNotConfigured: 'The source adapter is not configured.',
    sourcePolicyUnknown: 'At least one required operation has an unknown permission.',
    sourcePolicyRestricted: 'At least one required operation is restricted by the recorded source policy.',
    sourceBudgetNotConfigured: 'The source budget is not configured.',
    configuredLabel: 'Configured',
    configuredYes: 'Yes',
    configuredNo: 'No',
    searchConfiguration: 'Search configuration',
    searchCredentialLabel: 'Search credential',
    searchConfiguredReady: 'Search is configured and available; each run records its own search coverage.',
    searchBudgetLimit: 'Budget limit',
    searchBudgetReserved: 'Reserved',
    searchBudgetConsumed: 'Consumed',
    searchBudgetUnknown: 'Unknown',
    profilesUnavailable: 'Research profiles could not be loaded.',
    noProfiles: 'No active research profiles are configured.',
    chooseProfile: 'Research profile',
    chooseInstrument: 'Configured instrument',
    noInstruments: 'No enabled instruments are configured for this profile.',
    methodStatus: 'Profile status',
    methodVersion: 'Version',
    completeMethod: 'Complete',
    incompleteMethodStatus: 'Incomplete',
    retiredMethod: 'Retired',
    bundle: 'Method bundle',
    instrumentDetails: 'Instrument details',
    exchange: 'Exchange',
    currency: 'Currency',
    assetType: 'Asset type',
    noneConfigured: 'None configured',
    purpose: 'Purpose',
    permissionStatus: 'Permission status',
    conditions: 'Conditions',
    basis: 'Basis',
    checkedAt: 'Checked on',
    noConditions: 'No conditions recorded.',
    noBasis: 'No basis recorded.',
    notRecorded: 'Not recorded',
    sourceDetails: 'Rights and retrieval details',
    sourceId: 'Source ID',
    requestedUrl: 'Requested URL',
    resolvedUrl: 'Resolved URL',
    readRange: 'Read range',
    evidenceLocator: 'Evidence locator',
    contentHash: 'Content hash',
    sourceLimitations: 'Source limitations',
    showAllLimitations: 'Show all source notes',
    allowed: 'Allowed',
    restricted: 'Restricted',
    unknownPermission: 'Unknown',
    automatedFetch: 'Automated fetch',
    evidenceStorage: 'Evidence storage',
    llmInference: 'LLM inference',
    publicationOfAnalysisAndExcerpts: 'Publication of analysis and excerpts',
    rawDataRedistribution: 'Raw-data redistribution',
    searchNotConfigured: 'Search is not configured. No search request was made, and no results are available.',
    searchStatus: 'Search status',
    searchReadyLabel: 'Ready',
    searchQuotaExceededLabel: 'Quota exhausted',
    searchBudgetNotConfiguredLabel: 'Budget not configured',
    searchNotConfiguredLabel: 'Not configured',
    searchUnknownLabel: 'Unknown',
    searchReady: 'Search completed; results are discovery leads, not reviewed evidence.',
    searchQuotaExceeded: 'The configured search quota is exhausted. This is not a no-news result.',
    searchBudgetNotConfigured: 'Search budget is not configured. No search request was made.',
    searchQuery: 'Query',
    searchRetrievedAt: 'Retrieved',
    searchLeadCount: 'Discovery leads returned',
    searchNoLeads: 'No discovery leads were returned. This does not establish that no relevant news exists.',
    searchNoResultsRecorded: 'No result list was recorded, so result coverage is unknown.',
    searchOpenResult: 'Open result',
    searchPublished: 'Published',
    searchUsage: 'Search usage',
    searchCalls: 'calls',
    searchCredits: 'billed credits',
    searchStatusUnknown: 'Search status was not recorded. No search coverage is claimed.',
    loadLinkedDraft: 'Load linked draft into revision',
    linkedDraftLoaded: 'The linked article draft was loaded into the revision editor.',
    importLinkedDraft: 'Import edited draft for review',
    linkedDraftImported: 'The edited article draft is now an immutable research revision. Review its QA gates before approval.',
    importLinkedDraftHint: 'The article draft differs from the latest research revision. Import its exact saved title and body to start a fresh QA review.',
    updateArticleDraft: 'Update article draft',
    qaUnchecked: 'Core QA gates still need review before this revision can be approved.',
    qaFailed: 'A core QA gate failed. Resolve the issue before approving this revision.',
    linkedArticleUnavailable: 'The linked article cannot be updated because it is no longer a Draft.',
    attemptAlreadyUsed: 'A provider dispatch has already been used for this run. Start a new run for another attempt.',
    unknownOutcomeRetryBlocked: 'The provider outcome is unknown. Do not retry this run; resolve the uncertain outcome before creating a new run.',
    structuredReport: 'Structured report and QA JSON',
    syntheticRun: 'Synthetic evidence is for offline engineering checks. Its quality remains Limited and it must not be published as current research.',
  },
  'zh-TW': {
    settingsSources: '來源政策',
    sourceAvailability: '可用狀態',
    sourceReadyLabel: '可用',
    sourceNotConfiguredLabel: '尚未設定',
    sourcePolicyUnknownLabel: '權限未知',
    sourcePolicyRestrictedLabel: '政策限制',
    sourceBudgetNotConfiguredLabel: '尚未設定預算',
    sourceReady: '來源介面已設定；各項用途仍須遵守下方個別權限狀態。',
    sourceNotConfigured: '尚未設定來源介面。',
    sourcePolicyUnknown: '至少一項必要用途的權限仍未知。',
    sourcePolicyRestricted: '記錄的來源政策限制了至少一項必要用途。',
    sourceBudgetNotConfigured: '尚未設定來源預算。',
    configuredLabel: '已設定',
    configuredYes: '是',
    configuredNo: '否',
    searchConfiguration: '搜尋設定',
    searchCredentialLabel: '搜尋憑證',
    searchConfiguredReady: '搜尋服務已設定且可用；每次執行會記錄自己的搜尋涵蓋情況。',
    searchBudgetLimit: '預算上限',
    searchBudgetReserved: '預留',
    searchBudgetConsumed: '已使用',
    searchBudgetUnknown: '未知用量',
    loadingProfiles: '正在載入支援的設定檔…',
    profilesUnavailable: '無法載入研究設定檔。',
    noProfiles: '尚未設定可用的研究設定檔。',
    chooseProfile: '研究設定檔',
    chooseInstrument: '已設定的標的',
    noInstruments: '這個設定檔尚未設定可用的標的。',
    methodStatus: '設定檔狀態',
    methodVersion: '版本',
    completeMethod: '完整',
    incompleteMethodStatus: '未完整',
    retiredMethod: '已停用',
    bundle: '方法套件',
    instrumentDetails: '標的資料',
    exchange: '交易所',
    currency: '幣別',
    assetType: '資產類型',
    noneConfigured: '未設定',
    purpose: '用途',
    permissionStatus: '使用權限',
    conditions: '條件',
    basis: '依據',
    checkedAt: '查核日期',
    noConditions: '沒有記錄條件。',
    noBasis: '沒有記錄依據。',
    notRecorded: '未記錄',
    sourceDetails: '權利與擷取詳情',
    sourceId: '來源 ID',
    requestedUrl: '要求網址',
    resolvedUrl: '解析網址',
    readRange: '讀取範圍',
    evidenceLocator: '證據定位',
    contentHash: '內容雜湊',
    sourceLimitations: '來源限制',
    showAllLimitations: '顯示所有來源附註',
    allowed: '允許',
    restricted: '受限制',
    unknownPermission: '未知',
    automatedFetch: '自動擷取',
    evidenceStorage: '證據儲存',
    llmInference: 'LLM 推論',
    publicationOfAnalysisAndExcerpts: '分析及摘錄的發佈',
    rawDataRedistribution: '原始資料再散佈',
    searchNotConfigured: '尚未設定搜尋服務。沒有送出搜尋請求，也沒有可用的搜尋結果。',
    searchStatus: '搜尋狀態',
    searchReadyLabel: '已完成',
    searchQuotaExceededLabel: '額度已用完',
    searchBudgetNotConfiguredLabel: '尚未設定預算',
    searchNotConfiguredLabel: '尚未設定',
    searchUnknownLabel: '未知',
    searchReady: '搜尋已完成；結果只是待查線索，並非已檢閱的證據。',
    searchQuotaExceeded: '搜尋額度已用完。這不代表沒有相關消息。',
    searchBudgetNotConfigured: '尚未設定搜尋預算。沒有送出搜尋請求。',
    searchQuery: '搜尋字詞',
    searchRetrievedAt: '取得時間',
    searchLeadCount: '找到的待查線索',
    searchNoLeads: '沒有找到待查線索；這不能證明不存在相關消息。',
    searchNoResultsRecorded: '沒有記錄結果清單，因此無法確認搜尋涵蓋範圍。',
    searchOpenResult: '開啟結果',
    searchPublished: '發佈日期',
    searchUsage: '搜尋用量',
    searchCalls: '次呼叫',
    searchCredits: '計費點數',
    searchStatusUnknown: '未記錄搜尋狀態，因此不宣稱搜尋覆蓋情況。',
    loadLinkedDraft: '載入已連結草稿作為修訂',
    linkedDraftLoaded: '已載入已連結的文章草稿至修訂編輯器。',
    importLinkedDraft: '匯入已修改草稿並重新檢閱',
    linkedDraftImported: '已將修改後的文章草稿匯入為不可變研究修訂。請先重新檢閱 QA，再批准。',
    importLinkedDraftHint: '文章草稿與最近的研究修訂不同。匯入已儲存的標題與正文，開始新一輪 QA 檢閱。',
    updateArticleDraft: '更新文章草稿',
    qaUnchecked: '核心 QA 檢查仍需檢閱，才能批准這個版本。',
    qaFailed: '有核心 QA 檢查未通過。請先處理問題，再批准這個版本。',
    linkedArticleUnavailable: '已連結文章已不是草稿，無法更新。',
    attemptAlreadyUsed: '這個執行已使用一次供應商派送。如要再試，請建立新的研究執行。',
    unknownOutcomeRetryBlocked: '供應商結果未知。請勿重試這個執行；先查明不確定結果，再建立新的執行。',
    structuredReport: '結構化報告及 QA JSON',
    syntheticRun: '合成證據只供離線工程檢查使用。品質會維持「有限」，不可當作即時研究發佈。',
  },
  'zh-CN': {
    settingsSources: '来源政策',
    sourceAvailability: '可用状态',
    sourceReadyLabel: '可用',
    sourceNotConfiguredLabel: '尚未配置',
    sourcePolicyUnknownLabel: '权限未知',
    sourcePolicyRestrictedLabel: '政策受限',
    sourceBudgetNotConfiguredLabel: '尚未配置预算',
    sourceReady: '来源接口已配置；各项用途仍须遵守下方单独的权限状态。',
    sourceNotConfigured: '尚未配置来源接口。',
    sourcePolicyUnknown: '至少一项必要用途的权限仍未知。',
    sourcePolicyRestricted: '记录的来源政策限制了至少一项必要用途。',
    sourceBudgetNotConfigured: '尚未配置来源预算。',
    configuredLabel: '已配置',
    configuredYes: '是',
    configuredNo: '否',
    searchConfiguration: '搜索配置',
    searchCredentialLabel: '搜索凭据',
    searchConfiguredReady: '搜索服务已配置且可用；每次执行会记录自己的搜索覆盖情况。',
    searchBudgetLimit: '预算上限',
    searchBudgetReserved: '预留',
    searchBudgetConsumed: '已使用',
    searchBudgetUnknown: '未知用量',
    loadingProfiles: '正在加载支持的配置…',
    profilesUnavailable: '无法加载研究配置。',
    noProfiles: '尚未配置可用的研究配置。',
    chooseProfile: '研究配置',
    chooseInstrument: '已配置的标的',
    noInstruments: '此配置尚未配置可用的标的。',
    methodStatus: '配置状态',
    methodVersion: '版本',
    completeMethod: '完整',
    incompleteMethodStatus: '未完整',
    retiredMethod: '已停用',
    bundle: '方法包',
    instrumentDetails: '标的信息',
    exchange: '交易所',
    currency: '币种',
    assetType: '资产类型',
    noneConfigured: '未配置',
    purpose: '用途',
    permissionStatus: '使用权限',
    conditions: '条件',
    basis: '依据',
    checkedAt: '核查日期',
    noConditions: '没有记录条件。',
    noBasis: '没有记录依据。',
    notRecorded: '未记录',
    sourceDetails: '权利与检索详情',
    sourceId: '来源 ID',
    requestedUrl: '请求网址',
    resolvedUrl: '解析网址',
    readRange: '读取范围',
    evidenceLocator: '证据定位',
    contentHash: '内容哈希',
    sourceLimitations: '来源限制',
    showAllLimitations: '显示所有来源说明',
    allowed: '允许',
    restricted: '受限',
    unknownPermission: '未知',
    automatedFetch: '自动获取',
    evidenceStorage: '证据存储',
    llmInference: 'LLM 推理',
    publicationOfAnalysisAndExcerpts: '分析及摘录的发布',
    rawDataRedistribution: '原始数据再分发',
    searchNotConfigured: '尚未配置搜索服务。没有发送搜索请求，也没有可用的搜索结果。',
    searchStatus: '搜索状态',
    searchReadyLabel: '已完成',
    searchQuotaExceededLabel: '额度已用完',
    searchBudgetNotConfiguredLabel: '尚未配置预算',
    searchNotConfiguredLabel: '尚未配置',
    searchUnknownLabel: '未知',
    searchReady: '搜索已完成；结果只是待查线索，并非已审核的证据。',
    searchQuotaExceeded: '搜索额度已用完。这不代表没有相关消息。',
    searchBudgetNotConfigured: '尚未配置搜索预算。没有发送搜索请求。',
    searchQuery: '搜索词',
    searchRetrievedAt: '获取时间',
    searchLeadCount: '返回的待查线索',
    searchNoLeads: '没有返回待查线索；这不能证明不存在相关消息。',
    searchNoResultsRecorded: '没有记录结果列表，因此无法确认搜索覆盖范围。',
    searchOpenResult: '打开结果',
    searchPublished: '发布日期',
    searchUsage: '搜索用量',
    searchCalls: '次调用',
    searchCredits: '计费点数',
    searchStatusUnknown: '未记录搜索状态，因此不宣称搜索覆盖情况。',
    loadLinkedDraft: '加载已关联草稿作为修改',
    linkedDraftLoaded: '已将关联的文章草稿加载到修改编辑器。',
    importLinkedDraft: '导入已修改草稿并重新审核',
    linkedDraftImported: '已将修改后的文章草稿导入为不可变研究修改。请先重新审核 QA，再批准。',
    importLinkedDraftHint: '文章草稿与最近的研究修改不同。导入已保存的标题和正文，开始新一轮 QA 审核。',
    updateArticleDraft: '更新文章草稿',
    qaUnchecked: '核心 QA 检查仍需审核，才能批准此版本。',
    qaFailed: '有核心 QA 检查未通过。请先处理问题，再批准此版本。',
    linkedArticleUnavailable: '关联文章已不是草稿，无法更新。',
    attemptAlreadyUsed: '此执行已使用一次供应商派送。如需再次尝试，请创建新的研究执行。',
    unknownOutcomeRetryBlocked: '供应商结果未知。请勿重试此执行；先查明不确定结果，再创建新的执行。',
    structuredReport: '结构化报告及 QA JSON',
    syntheticRun: '合成证据仅供离线工程检查。质量会保持“有限”，不可作为最新研究发布。',
  },
} as const

export function researchConfigurationCopy(locale: Locale) {
  return configurationCopy[locale]
}

export type ResearchConfigurationCopy = ReturnType<typeof researchConfigurationCopy>

export const researchSourcePurposeKeys = [
  'automatedFetch',
  'evidenceStorage',
  'llmInference',
  'publicationOfAnalysisAndExcerpts',
  'rawDataRedistribution',
] as const

export function permissionStatusLabel(status: string, c: ResearchConfigurationCopy) {
  if (status === 'allowed') return c.allowed
  if (status === 'restricted') return c.restricted
  return c.unknownPermission
}
