import { index, route, type RouteConfig } from '@react-router/dev/routes';
export default [
  index('routes/home.tsx'),
  route('login', 'routes/login.tsx'),
  route('register', 'routes/register.tsx'),
  route('timeline', 'routes/timeline.tsx'),
  route('diaries', 'routes/diary-list.tsx'),
  route('diaries/new', 'routes/new.tsx'),
  route('diaries/quick', 'routes/quick.tsx'),
  route('diaries/:id/edit', 'routes/diary-edit.tsx'),
  route('diaries/:id/review', 'routes/diary-review.tsx'),
  route('diaries/:id', 'routes/diary.tsx'),
  route('partners/compare', 'routes/partner-compare.tsx'),
  route('partners', 'routes/partners.tsx'),
  route('alerts', 'routes/alerts.tsx'),
  route('reviews', 'routes/reviews.tsx'),
  route('calendar', 'routes/calendar.tsx'),
  route('trade-plans', 'routes/trade-plans.tsx'),
  route('trade-plans/new', 'routes/trade-plan-new.tsx'),
  route('trade-plans/:id', 'routes/trade-plan.tsx'),
  route('strategy-performance', 'routes/performance.tsx'),
  route('stocks', 'routes/holdings.tsx'),
  route('stocks/watchlist', 'routes/watchlist.tsx'),
  route('stocks/:symbol/thesis', 'routes/thesis.tsx'),
  route('stocks/:symbol', 'routes/company-market.tsx'),
  route('tools/etf', 'routes/etf-research.tsx'),
  route('tools/market-rotation', 'routes/market-rotation.tsx'),
  route('etf/watchlist', 'routes/etf-watchlist.tsx'),
  route('admin/etf', 'routes/etf-admin.tsx'),
  route('settings', 'routes/settings.tsx'),
  route('settings/api-keys', 'routes/api-keys.tsx'),
  route('settings/security', 'routes/account-security.tsx'),
  route('tools/financial-freedom', 'routes/fire.tsx'),
  route('design-preview', 'routes/preview.tsx'),
] satisfies RouteConfig;
