import { index, route, type RouteConfig } from '@react-router/dev/routes';
export default [
  index('routes/home.tsx'),
  route('about', 'routes/about.tsx'),
  route('guide', 'routes/guide.tsx'),
  route('login', 'routes/login.tsx'),
  route('register', 'routes/register.tsx'),
  route('register/complete', 'routes/registration-complete.tsx'),
  route('forgot-password', 'routes/forgot-password.tsx'),
  route('reset-password', 'routes/reset-password.tsx'),
  route('timeline', 'routes/timeline.tsx'),
  route('diaries', 'routes/diary-list.tsx'),
  route('diaries/new', 'routes/new.tsx'),
  route('diaries/quick', 'routes/quick.tsx'),
  route('diaries/:id/edit', 'routes/diary-edit.tsx'),
  route('diaries/:id/review', 'routes/diary-review.tsx'),
  route('diaries/:id', 'routes/diary.tsx'),
  route('discipline/share', 'routes/discipline-share.tsx'),
  route('partners/compare', 'routes/partner-compare.tsx'),
  route('partners', 'routes/partners.tsx'),
  route('discipline', 'routes/discipline.tsx'),
  route('alerts', 'routes/alerts.tsx'),
  route('reviews', 'routes/reviews.tsx'),
  route('reviews/ai-reports', 'routes/ai-reports.tsx'),
  route('calendar', 'routes/calendar.tsx'),
  route('trade-plans', 'routes/trade-plans.tsx'),
  route('trade-plans/new', 'routes/trade-plan-new.tsx'),
  route('trade-plans/:id', 'routes/trade-plan.tsx'),
  route('strategy-performance', 'routes/performance.tsx'),
  route('stocks', 'routes/holdings.tsx'),
  route('stocks/watchlist', 'routes/watchlist.tsx'),
  route('stocks/alerts', 'routes/price-alerts.tsx'),
  route('stocks/:symbol/gurus', 'routes/stock-gurus.tsx'),
  route('stocks/:symbol/thesis', 'routes/thesis.tsx'),
  route('stocks/:symbol', 'routes/company-market.tsx'),
  route('gurus', 'routes/gurus.tsx'),
  route('gurus/activity', 'routes/guru-research.tsx', { id: 'gurus-activity' }),
  route('gurus/notifications', 'routes/guru-notifications.tsx'),
  route('gurus/consensus', 'routes/guru-intelligence.tsx', { id: 'guru-consensus' }),
  route('gurus/stocks', 'routes/guru-intelligence.tsx', { id: 'guru-stocks' }),
  route('gurus/sectors', 'routes/guru-intelligence.tsx', { id: 'guru-sectors' }),
  route('gurus/compare', 'routes/guru-comparison.tsx'),
  route('gurus/:slug/portfolio', 'routes/guru-research.tsx', { id: 'guru-portfolio' }),
  route('gurus/:slug/changes', 'routes/guru-research.tsx', { id: 'guru-changes' }),
  route('gurus/:slug/history', 'routes/guru-research.tsx', { id: 'guru-history' }),
  route('gurus/:slug/filings', 'routes/guru-research.tsx', { id: 'guru-filings' }),
  route('gurus/:slug/analysis', 'routes/guru-analysis.tsx'),
  route('gurus/:slug', 'routes/guru-overview.tsx'),
  route('tools/etf', 'routes/etf-research.tsx'),
  route('tools', 'routes/tools.tsx'),
  route('tools/market-rotation', 'routes/market-rotation.tsx'),
  route('tools/relative-value', 'routes/relative-value.tsx'),
  route('tools/seasonality', 'routes/seasonality.tsx'),
  route('tools/sec-filings', 'routes/sec-filings.tsx'),
  route('tools/sec-filings/:cik/:accession', 'routes/sec-filing-detail.tsx'),
  route('etf/watchlist', 'routes/etf-watchlist.tsx'),
  route('admin/etf', 'routes/etf-admin.tsx'),
  route('admin/email-settings', 'routes/admin-email.tsx'),
  route('admin/users', 'routes/admin-users.tsx'),
  route('admin/gurus', 'routes/admin-gurus.tsx'),
  route('admin/gurus/:id', 'routes/admin-guru-detail.tsx'),
  route('admin/institutional', 'routes/admin-institutional.tsx'),
  route('admin/institutional/filings/:id', 'routes/admin-institutional-filing.tsx'),
  route('admin/institutional/mappings', 'routes/admin-institutional-mappings.tsx'),
  route('admin/ai', 'routes/admin-ai.tsx'),
  route('admin/ai/prompts', 'routes/admin-prompts.tsx'),
  route('admin/article-translations', 'routes/admin-article-translations.tsx'),
  route('admin/research', 'routes/admin-research.tsx'),
  route('admin/research/new', 'routes/admin-research-new.tsx'),
  route('admin/research/settings', 'routes/admin-research-settings.tsx'),
  route('admin/research/:id', 'routes/admin-research-detail.tsx'),
  route('settings', 'routes/settings.tsx'),
  route('achievements', 'routes/achievements.tsx'),
  route('settings/api-keys', 'routes/api-keys.tsx'),
  route('settings/security', 'routes/account-security.tsx'),
  route('tools/financial-freedom', 'routes/fire.tsx'),
  route('tools/position-sizing', 'routes/position-sizing.tsx'),
  route('design-preview', 'routes/preview.tsx'),
  route('articles', 'routes/articles.tsx'),
  route('articles/:slug', 'routes/article.tsx'),
  route('sitemap.xml', 'routes/sitemap.ts'),
  route('robots.txt', 'routes/robots.ts'),
  route('blog', 'routes/blog-index-redirect.tsx'),
  route('blog/:slug', 'routes/blog-redirect.tsx'),
  route('admin/blog', 'routes/admin-blog.tsx'),
  route('admin/blog/new', 'routes/admin-blog-new.tsx'),
  route('admin/blog/:id/edit', 'routes/admin-blog-edit.tsx'),
] satisfies RouteConfig;
