export const timelineCopy={
 en:{title:'Activity timeline',intro:'Diaries, trades and completed reviews in the order they happened.',filter:'Date range',allDates:'All dates',from:'From date',to:'Through date',apply:'Apply dates',reset:'Clear dates',clear:'Clear date filters',empty:'No activity in this date range.',more:'Load more activity',loaded:'records loaded',read:'Read full diary',entries:'records',transactions:'transactions',alerts:'alerts',reviewed:'Reviewed',INTACT:'Thesis intact',PARTIAL:'Partly confirmed',INVALIDATED:'Thesis invalidated',UNCLEAR:'Unclear',invalid:'Check the date range.',noContent:'No written content.',all:'You have reached the end of this range.',
  kinds:'Record type',kindAll:'All',kindDiary:'Diaries',kindTrade:'Trades',kindReview:'Reviews',
  diaryLabel:'Diary',tradeLabel:'Trade',reviewLabel:'Review',thesisReviewLabel:'Thesis review',
  buy:'Buy',sell:'Sell',at:'at',openDiary:'Open the diary',openThesis:'Open the thesis',
  fromDiary:'Recorded in',reviewOf:'Reviewed the judgment of',noOutcome:'No outcome recorded',
  HOLD:'Hold',ADD:'Add',REDUCE:'Reduce',EXIT:'Exit',CONTINUE_WATCHING:'Keep watching',
  invalidationTriggered:'Invalidation condition met'},
 'zh-TW':{title:'活動時間軸',intro:'日記、買賣與已完成的複盤，按發生順序排列。',filter:'日期範圍',allDates:'所有日期',from:'起始日期',to:'結束日期',apply:'套用日期',reset:'清除日期',clear:'清除日期篩選',empty:'此日期範圍沒有活動。',more:'載入更多記錄',loaded:'筆記錄已載入',read:'閱讀完整日記',entries:'筆記錄',transactions:'筆交易',alerts:'個提醒',reviewed:'已複盤',INTACT:'論點仍成立',PARTIAL:'部分確認',INVALIDATED:'論點已失效',UNCLEAR:'尚未明確',invalid:'請檢查日期範圍。',noContent:'尚未填寫內容。',all:'已讀取此範圍的所有記錄。',
  kinds:'記錄類型',kindAll:'全部',kindDiary:'日記',kindTrade:'買賣',kindReview:'複盤',
  diaryLabel:'日記',tradeLabel:'買賣',reviewLabel:'複盤',thesisReviewLabel:'論點複盤',
  buy:'買入',sell:'賣出',at:'成交價',openDiary:'開啟日記',openThesis:'開啟論點',
  fromDiary:'記錄於',reviewOf:'複盤了這天的判斷',noOutcome:'未記錄結論',
  HOLD:'繼續持有',ADD:'加碼',REDUCE:'減碼',EXIT:'退出',CONTINUE_WATCHING:'繼續觀察',
  invalidationTriggered:'已觸發失效條件'},
 'zh-CN':{title:'活动时间轴',intro:'日记、买卖与已完成的复盘，按发生顺序排列。',filter:'日期范围',allDates:'所有日期',from:'起始日期',to:'结束日期',apply:'应用日期',reset:'清除日期',clear:'清除日期筛选',empty:'此日期范围没有活动。',more:'加载更多记录',loaded:'条记录已加载',read:'阅读完整日记',entries:'条记录',transactions:'笔交易',alerts:'个提醒',reviewed:'已复盘',INTACT:'论点仍成立',PARTIAL:'部分确认',INVALIDATED:'论点已失效',UNCLEAR:'尚未明确',invalid:'请检查日期范围。',noContent:'尚未填写内容。',all:'已读取此范围的所有记录。',
  kinds:'记录类型',kindAll:'全部',kindDiary:'日记',kindTrade:'买卖',kindReview:'复盘',
  diaryLabel:'日记',tradeLabel:'买卖',reviewLabel:'复盘',thesisReviewLabel:'论点复盘',
  buy:'买入',sell:'卖出',at:'成交价',openDiary:'打开日记',openThesis:'打开论点',
  fromDiary:'记录于',reviewOf:'复盘了这天的判断',noOutcome:'未记录结论',
  HOLD:'继续持有',ADD:'加仓',REDUCE:'减仓',EXIT:'退出',CONTINUE_WATCHING:'继续观察',
  invalidationTriggered:'已触发失效条件'},
};
