export const watchlistCopy = {
  en: {
    title: 'Watchlist', hint: 'Keep companies close while you develop your investment view.', holdings: 'View holdings', tracked: 'Companies', researched: 'With research', unresearched: 'Not yet researched', addTitle: 'Quick add', placeholder: 'e.g. AAPL, MSFT, 2330', symbol: 'Stock symbol', add: 'Add company', listTitle: 'Watchlist', sortLabel: 'Order', sortOrder: 'Custom order', byResearch: 'Latest research', bySymbol: 'Symbol', search: 'Search companies', filterLabel: 'Research filter', all: 'All companies', hasResearch: 'With research', noResearch: 'Not yet researched', moveUp: 'Move up', moveDown: 'Move down', pinned: 'Pin', unpinned: 'Unpin', records: 'Research records', latest: 'Latest research', none: 'No research records yet.', more: 'More actions', viewResearch: 'View research', editOrder: 'Edit order', remove: 'Remove', undo: 'Undo remove', refresh: 'Refresh watchlist', empty: 'No companies match this view. Add a symbol to start your research.', saved: 'Watchlist updated.', removed: 'Removed from your watchlist.', restored: 'Restored to your watchlist.', limit: 'Showing up to 100 companies. Custom order supports Move up and Move down.', invalid: 'Use 1–32 letters, numbers or dots.', updateFailed: 'This row could not be updated. Other rows remain available.', refreshFailed: 'The latest watchlist could not be loaded. Your confirmed list is still shown.', refreshing: 'Updating watchlist…', customHint: 'Move up and down is available in custom order.', pinnedHint: 'Pinned items stay above other items in custom order.',
  },
  'zh-TW': {
    title: '關注清單', hint: '追蹤公司，逐步建立你的投資判斷。', holdings: '查看持倉', tracked: '關注公司', researched: '有研究記錄', unresearched: '尚未研究', addTitle: '快速加入關注標的', placeholder: '例如：AAPL、MSFT、2330', symbol: '股票代號', add: '加入公司', listTitle: '關注清單', sortLabel: '排序方式', sortOrder: '自訂排序', byResearch: '最近研究', bySymbol: '代號', search: '搜尋關注公司', filterLabel: '研究篩選', all: '全部公司', hasResearch: '有研究記錄', noResearch: '尚未研究', moveUp: '上移', moveDown: '下移', pinned: '置頂', unpinned: '取消置頂', records: '研究記錄', latest: '最近研究', none: '尚未有研究記錄。', more: '更多動作', viewResearch: '查看研究', editOrder: '編輯排序', remove: '移除', undo: '復原移除', refresh: '重新整理關注清單', empty: '沒有符合目前檢視的公司。加入股票代號，開始研究。', saved: '已更新關注清單。', removed: '已從關注清單移除。', restored: '已復原至關注清單。', limit: '最多顯示 100 間公司。自訂排序可用上移及下移。', invalid: '請輸入 1–32 個英文字母、數字或句點。', updateFailed: '這一列未能更新，其他列仍可繼續操作。', refreshFailed: '未能載入最新關注清單，畫面仍保留上次確認的內容。', refreshing: '正在更新關注清單…', customHint: '自訂排序時可使用上移及下移。', pinnedHint: '置頂項目在自訂排序時會排在其他項目前。',
  },
  'zh-CN': {
    title: '关注清单', hint: '追踪公司，逐步建立你的投资判断。', holdings: '查看持仓', tracked: '关注公司', researched: '有研究记录', unresearched: '尚未研究', addTitle: '快速加入关注标的', placeholder: '例如：AAPL、MSFT、2330', symbol: '股票代码', add: '加入公司', listTitle: '关注清单', sortLabel: '排序方式', sortOrder: '自定义排序', byResearch: '最近研究', bySymbol: '代码', search: '搜索关注公司', filterLabel: '研究筛选', all: '全部公司', hasResearch: '有研究记录', noResearch: '尚未研究', moveUp: '上移', moveDown: '下移', pinned: '置顶', unpinned: '取消置顶', records: '研究记录', latest: '最近研究', none: '尚未有研究记录。', more: '更多操作', viewResearch: '查看研究', editOrder: '编辑排序', remove: '移除', undo: '恢复移除', refresh: '刷新关注清单', empty: '没有符合当前视图的公司。加入股票代码，开始研究。', saved: '已更新关注清单。', removed: '已从关注清单移除。', restored: '已恢复到关注清单。', limit: '最多显示 100 间公司。自定义排序可用上移和下移。', invalid: '请输入 1–32 个英文字母、数字或句点。', updateFailed: '这一行未能更新，其他行仍可继续操作。', refreshFailed: '未能载入最新关注清单，画面仍保留上次确认的内容。', refreshing: '正在更新关注清单…', customHint: '自定义排序时可使用上移和下移。', pinnedHint: '置顶项目在自定义排序时会排在其他项目之前。',
  },
} as const

export type WatchlistCopy = (typeof watchlistCopy)[keyof typeof watchlistCopy]
