const en = {
  pending: 'Processing prompt operation…', testRequired: 'Run a successful synthetic test for this version before activating it.', providerModel: 'Provider / Model', system: 'System', title: 'Prompt registry', intro: 'Review source defaults, publish tested overrides, and inspect their history.',
  prompt: 'Prompt', weekly: 'Weekly report', monthly: 'Monthly report', version: 'Prompt version', default: 'System Default',
  source: 'Effective source', override: 'Database override', revision: 'Registry revision', name: 'Version name', template: 'User template',
  immutable: 'The System Default, guardrails, variables, output schema, and model defaults are owned by source code and are read-only.',
  create: 'Create from default', save: 'Save new version', duplicate: 'Duplicate', activate: 'Activate', rollback: 'Roll back to version',
  archive: 'Archive', disable: 'Disable override', archived: 'Archived', active: 'Active', preview: 'Preview', test: 'Run synthetic test',
  playground: 'Playground', sample: 'Registered synthetic input', rendered: 'Rendered prompts', schema: 'Output schema', variables: 'Allowed variables',
  guardrails: 'Immutable guardrails', models: 'Default model settings', result: 'Output and validation', usage: 'Test usage',
  audit: 'Audit history', actor: 'Admin', action: 'Action', time: 'Time', noAudit: 'No prompt actions recorded.',
  failed: 'The operation failed. Reload the registry and retry.', conflict: 'This registry changed. Your draft is retained; reload before saving.',
  reload: 'Reload registry', saved: 'Prompt operation completed.', forbidden: 'Admin access required.', loading: 'Loading prompt registry…',
  dirty: 'Save this draft before testing or activating it.', close: 'Cancel', confirm: 'Confirm',
  confirmArchive: 'Archive this version? It will remain in history and cannot be activated.',
  confirmDisable: 'Disable the current override? New reports will use the source default.',
  confirmActivate: 'Change the active prompt? New reports will use this tested version.',
  testHint: 'Tests use registered synthetic input and the published provider. Costs share the global budget; test attempts are recorded separately from production reports.',
  noProvider: 'No published provider', notRun: 'Preview only · validation not run', passed: 'Output validation passed',
  systemVersion: 'System version', versionId: 'Override version', output: 'Validated output',
}
export const promptCopy = {
  en,
  'zh-TW': {
    pending: '正在處理提示詞…', testRequired: '請先完成此版本的合成測試，再啟用。', providerModel: '供應商／模型', system: '系統', title: '提示詞管理', intro: '檢視系統預設、發布已測試的自訂版本，並追蹤操作紀錄。',
    prompt: '提示詞', weekly: '每週報告', monthly: '每月報告', version: '提示詞版本', default: '系統預設',
    source: '目前生效來源', override: '資料庫自訂版本', revision: '管理版本', name: '版本名稱', template: '使用者範本',
    immutable: '系統預設、保護規則、變數、輸出格式與模型預設由原始碼管理，僅供檢視。',
    create: '從預設建立', save: '儲存新版本', duplicate: '複製版本', activate: '啟用', rollback: '回退至此版本',
    archive: '封存', disable: '停用自訂版本', archived: '已封存', active: '生效中', preview: '預覽', test: '執行合成測試',
    playground: '測試工作台', sample: '已登錄的合成輸入', rendered: '實際提示詞', schema: '輸出格式', variables: '允許的變數',
    guardrails: '固定保護規則', models: '模型預設', result: '輸出與驗證', usage: '測試用量',
    audit: '操作紀錄', actor: '管理員', action: '操作', time: '時間', noAudit: '尚無提示詞操作紀錄。',
    failed: '操作未完成。請重新載入後重試。', conflict: '管理版本已變更。草稿仍然保留，請重新載入後儲存。',
    reload: '重新載入', saved: '提示詞操作已完成。', forbidden: '需要管理員權限。', loading: '正在載入提示詞…',
    dirty: '請先儲存草稿，再執行測試或啟用。', close: '取消', confirm: '確認',
    confirmArchive: '封存此版本？操作紀錄會保留，此版本將無法啟用。',
    confirmDisable: '停用目前自訂版本？新報告將使用系統預設。',
    confirmActivate: '變更生效提示詞？新報告將使用此已測試版本。',
    testHint: '測試使用登錄的合成輸入及已發布的供應商。費用共用全域預算，測試紀錄與正式報告分開保存。',
    noProvider: '尚無已發布的供應商', notRun: '僅預覽・未驗證輸出', passed: '輸出驗證通過',
    systemVersion: '系統版本', versionId: '自訂版本', output: '已驗證輸出',
  },
  'zh-CN': {
    pending: '正在处理提示词…', testRequired: '请先完成此版本的合成测试，再启用。', providerModel: '供应商／模型', system: '系统', title: '提示词管理', intro: '查看系统默认、发布已测试的自定义版本，并追踪操作记录。',
    prompt: '提示词', weekly: '每周报告', monthly: '每月报告', version: '提示词版本', default: '系统默认',
    source: '当前生效来源', override: '数据库自定义版本', revision: '管理版本', name: '版本名称', template: '用户模板',
    immutable: '系统默认、保护规则、变量、输出格式与模型默认由源代码管理，仅供查看。',
    create: '从默认建立', save: '保存新版本', duplicate: '复制版本', activate: '启用', rollback: '回退至此版本',
    archive: '归档', disable: '停用自定义版本', archived: '已归档', active: '生效中', preview: '预览', test: '执行合成测试',
    playground: '测试工作台', sample: '已登记的合成输入', rendered: '实际提示词', schema: '输出格式', variables: '允许的变量',
    guardrails: '固定保护规则', models: '模型默认', result: '输出与验证', usage: '测试用量',
    audit: '操作记录', actor: '管理员', action: '操作', time: '时间', noAudit: '暂无提示词操作记录。',
    failed: '操作未完成。请重新加载后重试。', conflict: '管理版本已变更。草稿仍然保留，请重新加载后保存。',
    reload: '重新加载', saved: '提示词操作已完成。', forbidden: '需要管理员权限。', loading: '正在加载提示词…',
    dirty: '请先保存草稿，再执行测试或启用。', close: '取消', confirm: '确认',
    confirmArchive: '归档此版本？操作记录会保留，此版本将无法启用。',
    confirmDisable: '停用当前自定义版本？新报告将使用系统默认。',
    confirmActivate: '变更生效提示词？新报告将使用此已测试版本。',
    testHint: '测试使用登记的合成输入及已发布的供应商。费用共用全局预算，测试记录与正式报告分开保存。',
    noProvider: '暂无已发布的供应商', notRun: '仅预览・未验证输出', passed: '输出验证通过',
    systemVersion: '系统版本', versionId: '自定义版本', output: '已验证输出',
  },
} satisfies Record<string, Record<keyof typeof en, string>>
