import type { Locale } from '../destinations'

const copy = {
  en: {
    title: 'Institutional operations', intro: 'Ingestion, parser, mapping, partial-quarter, and AI state for every tracked manager. Actions queue existing jobs; they never delete preserved source data.',
    mappings: 'Mapping queue', diagnostics: 'Download diagnostics', gurus: 'Guru profiles',
    scheduler: 'Shared SEC scheduler', nextAllowed: 'Next request allowed', lastRequest: 'Last request', requests: 'Requests', failures: 'Failures',
    queues: 'Queues and backlogs', versions: 'Processing versions',
    queueLabels: {
      filingsPending: 'Filings awaiting ingestion', filingsPartial: 'Partial filings', filingsError: 'Filing errors',
      snapshotRebuildsPending: 'Snapshot rebuilds', analyticsEventsPending: 'Analytics events', analyticsEventsFailed: 'Analytics retries',
      consensusRebuildsPending: 'Consensus rebuilds', mappingRefreshJobsPending: 'Mapping refresh jobs',
      unresolvedMappings: 'Unresolved holdings', ambiguousMappings: 'Ambiguous holdings',
      partialQuarters: 'Partial quarters', errorQuarters: 'Error quarters',
      analysisQueued: 'AI queued', analysisRunning: 'AI running', analysisFailed: 'AI failed', analysisInvalidated: 'AI invalidated',
    },
    versionLabels: {
      parser: 'Parser', resolver: 'Amendment resolver', securityMapping: 'Security mapping', analytics: 'Portfolio analytics',
      consensus: 'Consensus', analysisContext: 'AI context', analysisSchema: 'AI output schema',
    },
    managers: 'Tracked managers', manager: 'Manager', cik: 'CIK', discovery: 'SEC check', filings: 'Filings', quarters: 'Quarters',
    coverage: 'Mapping coverage', ai: 'AI analyses', latestFiling: 'Latest filing', nextCheck: 'Next check', lastSuccess: 'Last success',
    noManagers: 'No tracked managers yet.', profile: 'Profile', inspect: 'Inspect filings',
    filingState: 'State', period: 'Reported quarter', search: 'Search accession, CIK, or Guru', allStates: 'All states',
    accession: 'Accession', form: 'Form', filed: 'Filed', rows: 'Rows', coverageShort: 'Coverage', error: 'Error', open: 'Inspect',
    noFilings: 'No filings match these filters.', loading: 'Loading institutional operations…', failed: 'Institutional operations could not be loaded.',
    retry: 'Try again', forbidden: 'This administration view is restricted to administrators.', unauthorized: 'Sign in with an administrator account to continue.',
    previous: 'Previous', next: 'Next', inactive: 'Inactive',
  },
  'zh-TW': {
    title: '機構資料運維', intro: '每位追蹤管理人的匯入、解析、映射、季度不完整與 AI 狀態。操作只會排入既有工作，不會刪除已保存的來源資料。',
    mappings: '映射佇列', diagnostics: '下載診斷檔', gurus: '大師檔案',
    scheduler: 'SEC 共用排程器', nextAllowed: '下次可請求時間', lastRequest: '最後請求', requests: '請求數', failures: '失敗數',
    queues: '佇列與待辦', versions: '處理版本',
    queueLabels: {
      filingsPending: '待匯入申報', filingsPartial: '不完整申報', filingsError: '申報錯誤',
      snapshotRebuildsPending: '快照重建', analyticsEventsPending: '分析事件', analyticsEventsFailed: '分析重試',
      consensusRebuildsPending: '共識重建', mappingRefreshJobsPending: '映射重整工作',
      unresolvedMappings: '未解決持倉', ambiguousMappings: '有歧義持倉',
      partialQuarters: '不完整季度', errorQuarters: '錯誤季度',
      analysisQueued: 'AI 排隊中', analysisRunning: 'AI 執行中', analysisFailed: 'AI 失敗', analysisInvalidated: 'AI 已失效',
    },
    versionLabels: {
      parser: '解析器', resolver: '修訂解析器', securityMapping: '證券映射', analytics: '組合分析',
      consensus: '共識', analysisContext: 'AI 輸入結構', analysisSchema: 'AI 輸出結構',
    },
    managers: '追蹤管理人', manager: '管理人', cik: 'CIK', discovery: 'SEC 檢查', filings: '申報', quarters: '季度',
    coverage: '映射覆蓋率', ai: 'AI 分析', latestFiling: '最新申報', nextCheck: '下次檢查', lastSuccess: '最後成功',
    noManagers: '尚未有追蹤管理人。', profile: '檔案', inspect: '檢視申報',
    filingState: '狀態', period: '申報季度', search: '搜尋 accession、CIK 或大師', allStates: '全部狀態',
    accession: 'Accession', form: '表格', filed: '申報時間', rows: '列數', coverageShort: '覆蓋率', error: '錯誤', open: '檢視',
    noFilings: '沒有符合條件的申報。', loading: '正在載入機構運維資料…', failed: '暫時無法載入機構運維資料。',
    retry: '重試', forbidden: '此管理畫面只供管理員使用。', unauthorized: '請使用管理員帳戶登入後繼續。',
    previous: '上一頁', next: '下一頁', inactive: '已停用',
  },
  'zh-CN': {
    title: '机构数据运维', intro: '每位追踪管理人的导入、解析、映射、季度不完整与 AI 状态。操作只会排入既有任务，不会删除已保存的源数据。',
    mappings: '映射队列', diagnostics: '下载诊断文件', gurus: '大师档案',
    scheduler: 'SEC 共享调度器', nextAllowed: '下次可请求时间', lastRequest: '最后请求', requests: '请求数', failures: '失败数',
    queues: '队列与待办', versions: '处理版本',
    queueLabels: {
      filingsPending: '待导入申报', filingsPartial: '不完整申报', filingsError: '申报错误',
      snapshotRebuildsPending: '快照重建', analyticsEventsPending: '分析事件', analyticsEventsFailed: '分析重试',
      consensusRebuildsPending: '共识重建', mappingRefreshJobsPending: '映射刷新任务',
      unresolvedMappings: '未解决持仓', ambiguousMappings: '有歧义持仓',
      partialQuarters: '不完整季度', errorQuarters: '错误季度',
      analysisQueued: 'AI 排队中', analysisRunning: 'AI 执行中', analysisFailed: 'AI 失败', analysisInvalidated: 'AI 已失效',
    },
    versionLabels: {
      parser: '解析器', resolver: '修订解析器', securityMapping: '证券映射', analytics: '组合分析',
      consensus: '共识', analysisContext: 'AI 输入结构', analysisSchema: 'AI 输出结构',
    },
    managers: '追踪管理人', manager: '管理人', cik: 'CIK', discovery: 'SEC 检查', filings: '申报', quarters: '季度',
    coverage: '映射覆盖率', ai: 'AI 分析', latestFiling: '最新申报', nextCheck: '下次检查', lastSuccess: '最后成功',
    noManagers: '尚无追踪管理人。', profile: '档案', inspect: '查看申报',
    filingState: '状态', period: '申报季度', search: '搜索 accession、CIK 或大师', allStates: '全部状态',
    accession: 'Accession', form: '表格', filed: '申报时间', rows: '行数', coverageShort: '覆盖率', error: '错误', open: '查看',
    noFilings: '没有符合条件的申报。', loading: '正在加载机构运维数据…', failed: '暂时无法加载机构运维数据。',
    retry: '重试', forbidden: '此管理页面仅供管理员使用。', unauthorized: '请使用管理员账户登录后继续。',
    previous: '上一页', next: '下一页', inactive: '已停用',
  },
}

const inspector = {
  en: {
    title: 'Filing inspector', back: 'Institutional operations', source: 'SEC source',
    summary: 'Filing', documents: 'Documents and preserved artifacts', parsed: 'Parsed rows', effective: 'Effective snapshot',
    amendments: 'Filings for this quarter', analytics: 'Prepared analytics',
    manager: 'Manager', accession: 'Accession', form: 'Form', period: 'Reported quarter', filed: 'Filed', state: 'State',
    parser: 'Parser version', rows: 'Parsed rows', rejected: 'Rejected rows', coverage: 'Mapping coverage', error: 'Error',
    discovered: 'Discovered', ingested: 'Ingested', amendment: 'Amendment',
    basename: 'Document', digest: 'Content digest', length: 'Bytes', fetched: 'Fetched', reason: 'Reason', retained: 'Raw retained',
    retainUntil: 'Retain until', supersedes: 'Supersedes', yes: 'Yes', no: 'No',
    rowNumber: 'Row', issuer: 'Issuer', titleOfClass: 'Class', cusip: 'CUSIP', quantity: 'Quantity', value: 'Reported value',
    unit: 'Value unit', unitSource: 'Unit source', mapping: 'Mapping', warnings: 'Warnings', sample: (shown: number, total: number) => `Showing ${shown} of ${total} parsed rows`,
    snapshotId: 'Snapshot', snapshotHash: 'Snapshot digest', replayKey: 'Replay key', manifest: 'Source manifest', resolver: 'Resolver',
    holdings: 'Effective holdings', publication: 'Publication', periodState: 'Quarter state', created: 'Built',
    operation: 'Operation', ordinal: 'Order', noSnapshot: 'No active effective snapshot exists for this quarter yet.',
    noDocuments: 'No source documents are recorded.', noRows: 'No parsed rows are stored for this filing.',
    actions: 'Operations', reprocess: 'Reprocess filing', rebuild: 'Rebuild quarter analytics',
    reprocessConfirm: 'Return this filing to the ingestion queue? Preserved artifacts are reused and parsed rows are replaced only when a new parse succeeds.',
    rebuildConfirm: 'Request another effective-snapshot rebuild for this quarter? Downstream analytics and consensus republish from the rebuild.',
    confirm: 'Confirm', cancel: 'Cancel', queued: 'Queued.', alreadyQueued: 'Already queued; nothing was duplicated.', running: 'A worker already holds this job.',
    actionFailed: 'The operation could not be queued.', noPeriod: 'This filing has no reported quarter, so an analytics rebuild cannot be requested.',
    loading: 'Loading the filing…', failed: 'The filing could not be loaded.', retry: 'Try again', notFound: 'Filing not found.',
    analyticsStatus: 'State', analyticsVersion: 'Analytics version', comparison: 'Comparison', calculated: 'Calculated', holdingCount: 'Positions',
  },
  'zh-TW': {
    title: '申報檢視器', back: '機構資料運維', source: 'SEC 來源',
    summary: '申報', documents: '文件與保存的原始檔', parsed: '解析列', effective: '有效快照',
    amendments: '本季度申報', analytics: '已整理分析',
    manager: '管理人', accession: 'Accession', form: '表格', period: '申報季度', filed: '申報時間', state: '狀態',
    parser: '解析器版本', rows: '解析列數', rejected: '拒絕列數', coverage: '映射覆蓋率', error: '錯誤',
    discovered: '發現時間', ingested: '匯入時間', amendment: '修訂',
    basename: '文件', digest: '內容摘要', length: '位元組', fetched: '下載時間', reason: '原因', retained: '保留原文',
    retainUntil: '保留至', supersedes: '取代', yes: '是', no: '否',
    rowNumber: '列', issuer: '發行人', titleOfClass: '類別', cusip: 'CUSIP', quantity: '數量', value: '申報價值',
    unit: '價值單位', unitSource: '單位來源', mapping: '映射', warnings: '警示', sample: (shown: number, total: number) => `顯示 ${total} 列中的 ${shown} 列`,
    snapshotId: '快照', snapshotHash: '快照摘要', replayKey: '重放鍵', manifest: '來源清單', resolver: '解析器',
    holdings: '有效持倉', publication: '發布狀態', periodState: '季度狀態', created: '建立時間',
    operation: '操作', ordinal: '順序', noSnapshot: '本季度尚未有啟用中的有效快照。',
    noDocuments: '沒有記錄任何來源文件。', noRows: '這份申報沒有已保存的解析列。',
    actions: '運維操作', reprocess: '重新處理申報', rebuild: '重建本季度分析',
    reprocessConfirm: '要將這份申報放回匯入佇列嗎？已保存的原始檔會重複使用，解析列只有在新解析成功後才會替換。',
    rebuildConfirm: '要再請求一次本季度的有效快照重建嗎？下游分析與共識會依重建結果重新發布。',
    confirm: '確認', cancel: '取消', queued: '已排入佇列。', alreadyQueued: '已在佇列中，未重複建立。', running: '已有工作程序持有這項工作。',
    actionFailed: '無法排入這項操作。', noPeriod: '這份申報沒有申報季度，無法請求分析重建。',
    loading: '正在載入申報…', failed: '暫時無法載入這份申報。', retry: '重試', notFound: '找不到這份申報。',
    analyticsStatus: '狀態', analyticsVersion: '分析版本', comparison: '比較狀態', calculated: '計算時間', holdingCount: '持倉數',
  },
  'zh-CN': {
    title: '申报查看器', back: '机构数据运维', source: 'SEC 来源',
    summary: '申报', documents: '文件与保存的原始档', parsed: '解析行', effective: '有效快照',
    amendments: '本季度申报', analytics: '整理完成的分析',
    manager: '管理人', accession: 'Accession', form: '表格', period: '申报季度', filed: '申报时间', state: '状态',
    parser: '解析器版本', rows: '解析行数', rejected: '拒绝行数', coverage: '映射覆盖率', error: '错误',
    discovered: '发现时间', ingested: '导入时间', amendment: '修订',
    basename: '文件', digest: '内容摘要', length: '字节', fetched: '下载时间', reason: '原因', retained: '保留原文',
    retainUntil: '保留至', supersedes: '取代', yes: '是', no: '否',
    rowNumber: '行', issuer: '发行人', titleOfClass: '类别', cusip: 'CUSIP', quantity: '数量', value: '申报价值',
    unit: '价值单位', unitSource: '单位来源', mapping: '映射', warnings: '警示', sample: (shown: number, total: number) => `显示 ${total} 行中的 ${shown} 行`,
    snapshotId: '快照', snapshotHash: '快照摘要', replayKey: '重放键', manifest: '来源清单', resolver: '解析器',
    holdings: '有效持仓', publication: '发布状态', periodState: '季度状态', created: '创建时间',
    operation: '操作', ordinal: '顺序', noSnapshot: '本季度暂无启用中的有效快照。',
    noDocuments: '没有记录任何来源文件。', noRows: '这份申报没有已保存的解析行。',
    actions: '运维操作', reprocess: '重新处理申报', rebuild: '重建本季度分析',
    reprocessConfirm: '要把这份申报放回导入队列吗？已保存的原始档会复用，解析行只有在新解析成功后才会替换。',
    rebuildConfirm: '要再请求一次本季度的有效快照重建吗？下游分析与共识会依重建结果重新发布。',
    confirm: '确认', cancel: '取消', queued: '已排入队列。', alreadyQueued: '已在队列中，未重复创建。', running: '已有工作进程持有此任务。',
    actionFailed: '无法排入此操作。', noPeriod: '这份申报没有申报季度，无法请求分析重建。',
    loading: '正在加载申报…', failed: '暂时无法加载这份申报。', retry: '重试', notFound: '找不到这份申报。',
    analyticsStatus: '状态', analyticsVersion: '分析版本', comparison: '比较状态', calculated: '计算时间', holdingCount: '持仓数',
  },
}

export type InstitutionalOperationsCopy = typeof copy['en']
export type FilingInspectorCopy = typeof inspector['en']
export const institutionalOperationsCopy = (locale: Locale): InstitutionalOperationsCopy => copy[locale]
export const filingInspectorCopy = (locale: Locale): FilingInspectorCopy => inspector[locale]
