export const guruCopy = {
  en: {
    directoryKicker: 'Institutional intelligence', directoryTitle: 'Discover great investors', directoryIntro: 'See what tracked managers disclosed, how their portfolios changed, and which ideas they share.',
    search: 'Search investors, funds, or styles', searchAction: 'Search', clear: 'Clear', style: 'Investment style', managerType: 'Fund type', sector: 'Sector focus', all: 'All', featured: 'Featured investors', featuredOnly: 'Featured only', featuredToggle: 'Show all', sort: 'Sort by', custom: 'Featured and custom order', concentration: 'Most concentrated', turnover: 'Highest turnover', activity: 'Most active', latestFiling: 'Latest filing', followers: 'Most followed', az: 'A–Z',
    loading: 'Loading tracked investors…', failed: 'Investor data is temporarily unavailable.', retry: 'Try again', noMatches: 'No investors match these filters.', empty: 'No investors have been added yet.', resultCount: (count: number) => `${count} investors`, featuredLabel: 'Featured', manager: 'Manager / fund', cik: 'SEC CIK', reportedValue: 'Reported portfolio', holdings: 'Positions', topPosition: 'Largest position', latestQuarter: 'Reported quarter', filed: 'Filed', actions: 'Latest reported actions', new: 'New', add: 'Add', reduce: 'Reduce', exit: 'Exit', noActions: 'No comparable position changes', source: 'SEC Form 13F', statusReady: 'Ready', statusPartial: 'Partial data', statusError: 'Data error', statusPending: 'Awaiting filing data', viewProfile: 'View overview', followerCount: (count: number) => `${count} followers`, follow: 'Follow', unfollow: 'Following', signIn: 'Sign in to follow',
    consensus: 'Guru consensus', mostOwned: 'Most-owned stocks', sectorDirection: 'Sector direction', compare: 'Compare Gurus',
    warning: '13F filings are delayed quarter-end disclosures and may not reflect the manager’s current or complete portfolio.', overview: 'Overview', portfolio: 'Portfolio', changes: 'Changes', history: 'History', analysis: 'AI analysis', filings: 'Filings', back: 'All investors', philosophy: 'Investment philosophy', about: 'About this investor', metrics: 'Portfolio snapshot', topFive: 'Top 5 concentration', topTen: 'Top 10 concentration', turnoverLabel: 'Disclosed-weight churn', hhi: 'Concentration index', sectorAllocation: 'Sector allocation', topHoldings: 'Top holdings', latestMoves: 'Latest moves', historicalDirection: 'Historical direction', quarter: 'Quarter', valueHistory: 'Reported value', positionHistory: 'Position count', noData: 'No prepared filing data for this period yet.', noHoldings: 'No holdings available for this quarter.', noMoves: 'No comparable position changes for this quarter.', noHistory: 'Historical portfolio data will appear after filings are processed.', aiSummary: 'AI summary', aiNotGenerated: 'No AI report has been generated for this quarter.', aiPending: 'AI analysis is being prepared.', aiFailed: 'AI analysis could not be generated.', readFiling: 'View SEC filing', filingSource: 'Source: SEC Form 13F', latestReported: 'Latest reported period', action: 'Action', shares: 'Shares', weight: 'Weight', value: 'Reported value', rank: 'Rank', company: 'Company', rankChange: 'Rank', reported: 'Reported', focus: 'Editorial profile', noSector: 'Sector classification is not available.', stale: 'The latest quarter is not ready. Metrics and moves stay hidden until prepared data is ready.',
    statusLabel: (status: string) => status === 'READY' ? 'Ready' : status === 'PARTIAL' ? 'Partial data' : status === 'ERROR' ? 'Data error' : 'Awaiting filing data',
  },
  'zh-TW': {
    directoryKicker: '機構投資情報', directoryTitle: '發掘投資大師', directoryIntro: '查看追蹤中的管理人所披露的持倉、組合變化，以及彼此持有的投資方向。',
    search: '搜尋投資人、基金或風格', searchAction: '搜尋', clear: '清除', style: '投資風格', managerType: '基金類型', sector: '產業焦點', all: '全部', featured: '精選投資人', featuredOnly: '只看精選', featuredToggle: '顯示全部', sort: '排序', custom: '精選與自訂順序', concentration: '集中度最高', turnover: '換手幅度最高', activity: '近期最活躍', latestFiling: '最新申報', followers: '最多人追蹤', az: '名稱 A–Z',
    loading: '正在載入投資大師…', failed: '暫時無法載入投資人資料。', retry: '重試', noMatches: '沒有投資人符合這些篩選條件。', empty: '尚未新增投資大師。', resultCount: (count: number) => `${count} 位投資人`, featuredLabel: '精選', manager: '管理人／基金', cik: 'SEC CIK', reportedValue: '申報組合價值', holdings: '持倉數', topPosition: '最大持倉', latestQuarter: '申報季度', filed: '申報日期', actions: '最新申報動作', new: '新建', add: '增加', reduce: '減少', exit: '退出', noActions: '沒有可比較的持倉變化', source: '來源：SEC Form 13F', statusReady: '資料就緒', statusPartial: '資料不完整', statusError: '資料錯誤', statusPending: '等待申報資料', viewProfile: '查看總覽', followerCount: (count: number) => `${count} 人追蹤`, follow: '追蹤', unfollow: '已追蹤', signIn: '登入後追蹤',
    consensus: '大師共識', mostOwned: '大師持倉排行', sectorDirection: '板塊方向', compare: '比較大師',
    warning: '13F 是延遲發布的季末持倉披露，未必反映管理人目前或完整的投資組合。', overview: '總覽', portfolio: '持倉', changes: '變化', history: '歷史', analysis: 'AI 分析', filings: '申報', back: '所有投資大師', philosophy: '投資理念', about: '投資人介紹', metrics: '組合概況', topFive: '前五大持倉集中度', topTen: '前十大持倉集中度', turnoverLabel: '申報權重變動', hhi: '集中度指數', sectorAllocation: '產業配置', topHoldings: '主要持倉', latestMoves: '最新動作', historicalDirection: '歷史方向', quarter: '季度', valueHistory: '申報組合價值', positionHistory: '持倉數', noData: '本季度尚無已整理的申報資料。', noHoldings: '本季度沒有可顯示的持倉。', noMoves: '本季度沒有可比較的持倉變化。', noHistory: '完成申報處理後，這裡會顯示歷史組合資料。', aiSummary: 'AI 摘要', aiNotGenerated: '本季度尚未產生 AI 報告。', aiPending: 'AI 分析準備中。', aiFailed: '無法產生 AI 分析。', readFiling: '查看 SEC 申報', filingSource: '資料來源：SEC Form 13F', latestReported: '最新申報期間', action: '動作', shares: '股數', weight: '組合權重', value: '申報價值', rank: '排名', company: '公司', rankChange: '排名', reported: '申報', focus: '編輯資料', noSector: '目前沒有產業分類資料。', stale: '最新季度資料尚未就緒。資料準備完成前會隱藏指標與持倉變化。',
    statusLabel: (status: string) => status === 'READY' ? '資料就緒' : status === 'PARTIAL' ? '資料不完整' : status === 'ERROR' ? '資料錯誤' : '等待申報資料',
  },
  'zh-CN': {
    directoryKicker: '机构投资信息', directoryTitle: '发现投资大师', directoryIntro: '查看追踪中的管理人披露了哪些持仓、组合如何变化，以及共同持有的投资方向。',
    search: '搜索投资人、基金或风格', searchAction: '搜索', clear: '清除', style: '投资风格', managerType: '基金类型', sector: '行业焦点', all: '全部', featured: '精选投资人', featuredOnly: '只看精选', featuredToggle: '显示全部', sort: '排序', custom: '精选与自定义顺序', concentration: '集中度最高', turnover: '换手幅度最高', activity: '近期最活跃', latestFiling: '最新申报', followers: '最多人追踪', az: '名称 A–Z',
    loading: '正在加载投资大师…', failed: '暂时无法加载投资人资料。', retry: '重试', noMatches: '没有投资人符合这些筛选条件。', empty: '尚未添加投资大师。', resultCount: (count: number) => `${count} 位投资人`, featuredLabel: '精选', manager: '管理人／基金', cik: 'SEC CIK', reportedValue: '申报组合价值', holdings: '持仓数', topPosition: '最大持仓', latestQuarter: '申报季度', filed: '申报日期', actions: '最新申报动作', new: '新建', add: '增加', reduce: '减少', exit: '退出', noActions: '没有可比较的持仓变化', source: '来源：SEC Form 13F', statusReady: '数据就绪', statusPartial: '数据不完整', statusError: '数据错误', statusPending: '等待申报数据', viewProfile: '查看总览', followerCount: (count: number) => `${count} 人追踪`, follow: '追踪', unfollow: '已追踪', signIn: '登录后追踪',
    consensus: '大师共识', mostOwned: '大师持仓排行', sectorDirection: '板块方向', compare: '比较大师',
    warning: '13F 是延迟发布的季末持仓披露，不一定反映管理人当前或完整的投资组合。', overview: '总览', portfolio: '持仓', changes: '变化', history: '历史', analysis: 'AI 分析', filings: '申报', back: '所有投资大师', philosophy: '投资理念', about: '投资人介绍', metrics: '组合概况', topFive: '前五大持仓集中度', topTen: '前十大持仓集中度', turnoverLabel: '申报权重变动', hhi: '集中度指数', sectorAllocation: '行业配置', topHoldings: '主要持仓', latestMoves: '最新动作', historicalDirection: '历史方向', quarter: '季度', valueHistory: '申报组合价值', positionHistory: '持仓数', noData: '本季度尚无整理完成的申报数据。', noHoldings: '本季度没有可显示的持仓。', noMoves: '本季度没有可比较的持仓变化。', noHistory: '申报处理完成后，这里会显示历史组合资料。', aiSummary: 'AI 摘要', aiNotGenerated: '本季度尚未生成 AI 报告。', aiPending: 'AI 分析准备中。', aiFailed: '无法生成 AI 分析。', readFiling: '查看 SEC 申报', filingSource: '资料来源：SEC Form 13F', latestReported: '最新申报期间', action: '动作', shares: '股数', weight: '组合权重', value: '申报价值', rank: '排名', company: '公司', rankChange: '排名', reported: '申报', focus: '编辑资料', noSector: '目前没有行业分类资料。', stale: '最新季度资料尚未就绪。数据准备完成前会隐藏指标和持仓变化。',
    statusLabel: (status: string) => status === 'READY' ? '数据就绪' : status === 'PARTIAL' ? '数据不完整' : status === 'ERROR' ? '数据错误' : '等待申报数据',
  },
} as const

export type GuruCopy = {
  [Key in keyof typeof guruCopy.en]: typeof guruCopy.en[Key] extends (...args: infer Args) => unknown
    ? (...args: Args) => string
    : string
}
