import { useMemo,useState,type FormEvent } from 'react';
import { Link,useSearchParams } from 'react-router';
import { diaryExcerpt,groupTimelineEntries } from '@diary/domain';
import { useUi } from '../ui';
import { useTimeline } from '../use-timeline';
import { timelineCopy } from '../timeline-copy';
import { FailureNotice,invalidField } from '../api-error';
import { signInPath } from '../session';
import { Markdown } from '../markdown';
import '../timeline.css';
function EntryBody({content,summary}:{content:string|null;summary:string}){const [expanded,setExpanded]=useState(false);return <details onToggle={event=>setExpanded(event.currentTarget.open)}><summary>{summary}</summary>{expanded&&<Markdown>{content??''}</Markdown>}</details>;}
export default function TimelinePage(){const {locale,t}=useUi(),c=timelineCopy[locale],[params,setParams]=useSearchParams(),timeline=useTimeline(params.toString()),groups=useMemo(()=>groupTimelineEntries(timeline.entries),[timeline.entries]);
 function filter(event:FormEvent<HTMLFormElement>){event.preventDefault();const next=new URLSearchParams();for(const [key,value] of new FormData(event.currentTarget))if(typeof value==='string'&&value)next.set(key,value);setParams(next);}
 const monthLabel=(period:string)=>new Intl.DateTimeFormat(locale,{year:'numeric',month:'long',timeZone:'UTC'}).format(new Date(`${period}-01T00:00:00Z`));
 return <section className="diary-timeline"><header className="page-heading"><div><h1>{c.title}</h1><p className="muted">{c.intro}</p></div><Link className="button" to="/diaries/quick">{t('quick')}</Link></header><form key={params.toString()} className="timeline-filters" onSubmit={filter}><label>{c.from}<input name="dateFrom" type="date" defaultValue={params.get('dateFrom')??''} aria-invalid={invalidField(timeline.error,'dateFrom')} aria-describedby={timeline.error?'timeline-error':undefined}/></label><label>{c.to}<input name="dateTo" type="date" defaultValue={params.get('dateTo')??''} aria-invalid={invalidField(timeline.error,'dateTo')} aria-describedby={timeline.error?'timeline-error':undefined}/></label><div className="actions"><button type="submit">{c.apply}</button><button type="button" className="secondary" onClick={()=>setParams({})}>{c.reset}</button></div></form>
 {timeline.loading?<p role="status">{t('loading')}</p>:<><p className="muted" role="status">{timeline.entries.length} {locale==='en'&&timeline.entries.length===1?'diary loaded':c.loaded}</p>{groups.map(group=><section className="timeline-month" key={group.period} aria-label={monthLabel(group.period)}><header><h2>{monthLabel(group.period)}</h2><span className="muted">{group.entries.length} {locale==='en'&&group.entries.length===1?'entry':c.entries}</span></header><ol>{group.entries.map(entry=><li key={entry.id} data-testid="timeline-entry"><time dateTime={entry.date}>{entry.date}</time><article><h3><Link to={`/diaries/${entry.id}`}>{entry.title}</Link></h3><ul className="timeline-meta" aria-label={c.entries}>{entry.tags.map(tag=><li key={tag}>{tag}</li>)}{entry.transactionCount>0&&<li>{entry.transactionCount} {c.transactions}</li>}{entry.alertCount>0&&<li>{entry.alertCount} {c.alerts}</li>}{entry.reviewed&&<li>{c.reviewed}{entry.reviewOutcome&&entry.reviewOutcome in c?` · ${c[entry.reviewOutcome as 'INTACT']}`:''}</li>}</ul><p className="timeline-excerpt">{diaryExcerpt(entry.content)||c.noContent}</p>{entry.content&&<EntryBody content={entry.content} summary={c.expand}/>}</article></li>)}</ol></section>)}{!timeline.error&&timeline.entries.length===0&&<div className="timeline-empty"><p>{c.empty}</p><Link className="button secondary" to="/diaries/new">{t('write')}</Link></div>}</>}
 {timeline.error&&<div className="timeline-recovery"><FailureNotice failure={timeline.error} id="timeline-error"/><div className="actions"><button type="button" onClick={timeline.retry}>{t('retry')}</button>{timeline.error.code?.startsWith('AUTH_')&&<Link to={signInPath('/timeline')}>{t('login')}</Link>}</div></div>}{!timeline.error&&!timeline.loading&&timeline.hasMore&&<button type="button" className="secondary timeline-more" disabled={timeline.loadingMore} onClick={timeline.loadMore}>{timeline.loadingMore?t('loading'):c.more}</button>}{!timeline.loading&&!timeline.error&&timeline.entries.length>0&&!timeline.hasMore&&<p className="muted">{c.all}</p>}</section>;
}
