import { useEffect,useRef,useState } from 'react';
import { Link,useSearchParams } from 'react-router';
import { TRADE_PLAN_STATUSES,tradePlanListQuerySchema,tradePlanListResponseSchema } from '@diary/contracts/trade-plan';
import type { z } from 'zod';
import { api,useUi } from '../ui';
import { apiFailure,FailureNotice,type Failure } from '../api-error';
import { signInPath } from '../session';
import { planCopy } from '../trade-plan-copy';
import '../trade-plan.css';
export default function TradePlans(){const {locale,t}=useUi(),c=planCopy[locale];const [params,setParams]=useSearchParams(),[attempt,retry]=useState(0),[data,setData]=useState<z.infer<typeof tradePlanListResponseSchema>|null>(null),[error,setError]=useState<Failure|null>(null);const query=params.toString();const translate=useRef(t);translate.current=t;
 useEffect(()=>{const controller=new AbortController();setData(null);setError(null);const parsed=tradePlanListQuerySchema.safeParse(Object.fromEntries(new URLSearchParams(query)));if(!parsed.success){setError({message:translate.current('failed'),code:'SYS_VALIDATION_ERROR',fields:[]});return;}api.GET('/api/trade-plans',{params:{query:parsed.data},signal:controller.signal}).then(r=>{if(controller.signal.aborted)return;const value=tradePlanListResponseSchema.safeParse(r.data);if(value.success)setData(value.data);else setError(apiFailure(r.error,translate.current('failed')));}).catch(()=>{if(!controller.signal.aborted)setError(apiFailure(null,translate.current('connection')));});return()=>controller.abort();},[query,attempt]);
 function turn(page:number){const next=new URLSearchParams(params);next.set('page',String(page));setParams(next);}
 return <section className="plan-page"><header className="plan-header"><div><h1>{c.title}</h1><p className="lede">{c.hint}</p></div><Link className="button" to="/trade-plans/new">{c.new}</Link></header><form key={query} className="plan-filters" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget),next=new URLSearchParams();for(const key of ['symbol','status','sortBy']){const value=String(form.get(key)||'').trim();if(value)next.set(key,value);}setParams(next);}}><label>{c.symbol}<input name="symbol" maxLength={32} defaultValue={params.get('symbol')||''}/></label><label>{c.status}<select name="status" defaultValue={params.get('status')||''}><option value="">{c.all}</option>{TRADE_PLAN_STATUSES.map(s=><option key={s} value={s}>{c[s]}</option>)}</select></label><label>{c.sort}<select name="sortBy" defaultValue={params.get('sortBy')||'updatedAt-desc'}><option value="updatedAt-desc">{c.updated}</option><option value="createdAt-desc">{c.created}</option><option value="symbol-asc">{c.symbols}</option></select></label><button>{c.filter}</button></form>{error?<><FailureNotice failure={error}/>{error?.code?.startsWith('AUTH_')&&<Link to={signInPath('/trade-plans')}>{t('login')}</Link>}<button onClick={()=>retry(v=>v+1)}>{t('retry')}</button></>:!data?<p role="status">{t('loading')}</p>:<>{data.data.length?<ul className="plan-list">{data.data.map(plan=><li key={plan.id}><header className="plan-header"><h2><Link to={`/trade-plans/${plan.id}`}>{plan.symbol}{plan.setupType?` · ${plan.setupType}`:''}</Link></h2><span>{c[plan.status]}</span></header><dl>{(['entryZoneLow','entryZoneHigh','stopLoss','targetPrice'] as const).map(key=><div key={key}><dt>{c[key]}</dt><dd>{plan[key]??'—'}</dd></div>)}</dl>{plan.diary&&<Link to={`/diaries/${plan.diary.id}`}>{plan.diary.title} · {plan.diary.date}</Link>}</li>)}</ul>:<p>{c.empty}</p>}<nav className="plan-pagination" aria-label={c.title}><button disabled={data.pagination.page<=1} onClick={()=>turn(data.pagination.page-1)}>{c.previous}</button><span>{data.pagination.page} / {Math.max(1,data.pagination.totalPages)}</span><button disabled={data.pagination.page>=data.pagination.totalPages} onClick={()=>turn(data.pagination.page+1)}>{c.next}</button></nav></>}</section>;
}
