import { useEffect,useRef,useState } from 'react';
import { Link,useBlocker,useNavigate,useParams,useSearchParams } from 'react-router';
import { TRADE_PLAN_STATUSES,tradePlanInputSchema,tradePlanResponseSchema,type TradePlanResponse } from '@diary/contracts/trade-plan';
import { api,useUi } from '../ui';
import { apiFailure,FailureNotice,invalidField,type Failure } from '../api-error';
import { useSessionState,signInPath } from '../session';
import { planCopy } from '../trade-plan-copy';
import '../trade-plan.css';
const fields=['symbol','status','setupType','entryPrice','entryZoneLow','entryZoneHigh','stopLoss','targetPrice','maxPositionSize','diaryId','invalidationCondition','notes'] as const;
type Form=Record<typeof fields[number],string>;
function formFrom(plan?:TradePlanResponse):Form{return Object.fromEntries(fields.map(key=>[key,plan?.[key]??(key==='status'?'draft':'')])) as Form;}
function readPositionSizingPrefill(raw:string|null):Partial<Form>|null{if(!raw)return null;try{const value:unknown=JSON.parse(raw);if(!value||typeof value!=='object')return null;const record=value as Record<string,unknown>;const patch:Partial<Form>={};for(const key of ['symbol','status','entryPrice','maxPositionSize','notes'] as const)if(typeof record[key]==='string')patch[key]=record[key];return patch;}catch{return null;}}
export default function TradePlan(){const {id}=useParams(),navigate=useNavigate(),[params]=useSearchParams(),prefill=params.get('prefill'),{locale,t}=useUi(),c=planCopy[locale],session=useSessionState();const [form,setForm]=useState<Form>(formFrom),[plan,setPlan]=useState<TradePlanResponse|null>(null),[loading,setLoading]=useState(!!id),[error,setError]=useState<Failure|null>(null),[pending,setPending]=useState(false),[attempt,retry]=useState(0),[saved,setSaved]=useState(false);const active=useRef(true),dirty=useRef(false);const [diaries,setDiaries]=useState<{id:string;title:string;date:string}[]>([]),[diaryPage,setDiaryPage]=useState(1),[diaryMore,setDiaryMore]=useState(false),[diaryError,setDiaryError]=useState<Failure|null>(null),[diaryAttempt,diaryRetry]=useState(0);
 const translate=useRef(t);translate.current=t;
 useEffect(()=>{if(id||prefill!=='position-sizing'||typeof window==='undefined')return;const patch=readPositionSizingPrefill(sessionStorage.getItem('tradePlanPrefill'));sessionStorage.removeItem('tradePlanPrefill');if(patch)setForm(current=>({...current,...patch}));},[id,prefill]);
 const blocker=useBlocker(()=>dirty.current&&session.authenticated!==false);useEffect(()=>{if(blocker.state==='blocked'){if(window.confirm(c.discard))blocker.proceed();else blocker.reset();}},[blocker,c.discard]);useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(dirty.current){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[]);
 useEffect(()=>{active.current=true;const controller=new AbortController();setError(null);if(id){setLoading(true);api.GET('/api/trade-plans/{id}',{params:{path:{id}},signal:controller.signal}).then(r=>{if(controller.signal.aborted)return;const parsed=tradePlanResponseSchema.safeParse(r.data);if(parsed.success){setPlan(parsed.data);setForm(formFrom(parsed.data));dirty.current=false;}else setError(apiFailure(r.error,translate.current('failed')));setLoading(false);}).catch(()=>{if(!controller.signal.aborted){setError(apiFailure(null,translate.current('connection')));setLoading(false);}});}return()=>{active.current=false;controller.abort();};},[id,attempt]);
 useEffect(()=>{const controller=new AbortController();setDiaryError(null);api.GET('/api/diaries',{params:{query:{page:diaryPage,limit:20,sortBy:'date-desc'}},signal:controller.signal}).then(r=>{if(controller.signal.aborted)return;if(r.data){setDiaries(old=>[...new Map([...old,...r.data!.data].map(d=>[d.id,{id:d.id,title:d.title,date:d.date}])).values()]);setDiaryMore(r.data.pagination.page<r.data.pagination.totalPages);}else setDiaryError(apiFailure(r.error,t('failed')));}).catch(()=>{if(!controller.signal.aborted)setDiaryError(apiFailure(null,t('connection')));});return()=>controller.abort();},[diaryPage,diaryAttempt,t]);
 async function save(){setError(null);setSaved(false);const input=Object.fromEntries(fields.map(key=>[key,form[key]===''&&key!=='symbol'&&key!=='status'?null:form[key]])),parsed=tradePlanInputSchema.safeParse(input);if(!parsed.success){setError({message:t('failed'),code:'SYS_VALIDATION_ERROR',fields:parsed.error.issues.map(issue=>issue.path.join('.'))});return;}setPending(true);try{const r=id?await api.PUT('/api/trade-plans/{id}',{params:{path:{id}},body:parsed.data}):await api.POST('/api/trade-plans',{body:parsed.data});if(!active.current)return;const result=tradePlanResponseSchema.safeParse(r.data);if(!result.success){setError(apiFailure(r.error,t('failed')));return;}dirty.current=false;setPlan(result.data);setForm(formFrom(result.data));setSaved(true);if(!id)navigate(`/trade-plans/${result.data.id}`,{replace:true});}catch{if(active.current)setError(apiFailure(null,t('connection')));}finally{if(active.current)setPending(false);}}
 async function remove(){if(!id||!window.confirm(c.confirm))return;setPending(true);try{const r=await api.DELETE('/api/trade-plans/{id}',{params:{path:{id}}});if(!active.current)return;if(r.data?.success){dirty.current=false;navigate('/trade-plans');}else setError(apiFailure(r.error,t('failed')));}catch{if(active.current)setError(apiFailure(null,t('connection')));}finally{if(active.current)setPending(false);}}
 function change(key:typeof fields[number],value:string){dirty.current=true;setSaved(false);setForm(old=>({...old,[key]:value}));}
 function input(key:typeof fields[number],large=false){return <label key={key} className={large?'plan-wide':undefined}>{c[key]}{large?<textarea aria-label={c[key]} value={form[key]} rows={key==='notes'?5:3} maxLength={key==='notes'?10000:5000} onChange={e=>change(key,e.target.value)} aria-invalid={invalidField(error,key)} aria-describedby={invalidField(error,key)?'plan-error':undefined}/>:<input aria-label={c[key]} required={key==='symbol'} inputMode={key==='symbol'||key==='setupType'?'text':'decimal'} maxLength={key==='symbol'?32:key==='setupType'?100:32} value={form[key]} onChange={e=>change(key,e.target.value)} aria-invalid={invalidField(error,key)} aria-describedby={invalidField(error,key)?'plan-error':undefined}/>}</label>;}
 if(loading)return <p role="status">{t('loading')}</p>;if(id&&!plan)return <><FailureNotice failure={error}/>{error?.code?.startsWith('AUTH_')&&<Link to={signInPath(`/trade-plans/${id}`)}>{t('login')}</Link>}<button onClick={()=>retry(v=>v+1)}>{t('retry')}</button><Link to="/trade-plans">{c.back}</Link></>;
 return <section className="plan-page"><Link to="/trade-plans">{c.back}</Link><h1>{id?`${c.edit} · ${plan?.symbol}`:c.new}</h1><p className="lede">{c.hint}</p>{saved&&<p role="status">{c.saved}</p>}{plan?.diary&&<p><Link to={`/diaries/${plan.diary.id}`}>{c.read}: {plan.diary.title} · {plan.diary.date}</Link></p>}<form className="plan-form" onSubmit={event=>{event.preventDefault();void save();}}><fieldset disabled={pending}><div className="plan-grid">{input('symbol')}<label>{c.status}<select aria-label={c.status} value={form.status} onChange={e=>change('status',e.target.value)}>{TRADE_PLAN_STATUSES.map(s=><option key={s} value={s}>{c[s]}</option>)}</select></label>{input('setupType')}</div></fieldset><fieldset disabled={pending}><legend>{c.levels}</legend><p className="muted">{c.precision}</p><div className="plan-grid">{(['entryPrice','entryZoneLow','entryZoneHigh','stopLoss','targetPrice','maxPositionSize'] as const).map(key=>input(key))}</div></fieldset><fieldset disabled={pending}><legend>{c.context}</legend><div className="plan-grid"><label className="plan-wide">{c.diaryId}<select aria-label={c.diaryId} value={form.diaryId} onChange={e=>change('diaryId',e.target.value)}><option value="">{c.none}</option>{plan?.diary&&!diaries.some(d=>d.id===plan.diary!.id)&&<option value={plan.diary.id}>{plan.diary.title} · {plan.diary.date}</option>}{diaries.map(d=><option value={d.id} key={d.id}>{d.title} · {d.date}</option>)}</select></label>{diaryMore&&!diaryError&&<button type="button" onClick={()=>setDiaryPage(v=>v+1)}>{c.diaries}</button>}{diaryError&&<div className="plan-wide"><FailureNotice failure={diaryError} id="diary-lookup-error"/><button type="button" onClick={()=>diaryRetry(v=>v+1)}>{t('retry')}</button></div>}{input('invalidationCondition',true)}{input('notes',true)}</div></fieldset><FailureNotice failure={error} id="plan-error"/>{error?.code?.startsWith('AUTH_')&&<Link to={signInPath(id?`/trade-plans/${id}`:'/trade-plans/new')}>{t('login')}</Link>}<div className="actions"><button disabled={pending}>{pending?t('pending'):c.save}</button>{id&&<button className="secondary" type="button" disabled={pending} onClick={()=>void remove()}>{c.delete}</button>}</div></form></section>;
}
